### ISSUE TITLE
Purge varnish cache on deployment

### ISSUE THREAD

**Issue by timwood** [acquia/blt#1083]
When deploying to Acquia environment(s) can BLT automatically purge the varnish cache so changes are reflected on the site to anonymous users?

**Comment by grasmash** [comment]
I believe that you want the the [acquia purge](https://www.drupal.org/project/acquia_purge) module for this.

**Comment by seanhamlin** [comment]
[The Cloud API](https://cloudapi.acquia.com/#DELETE__sites__site_envs__env_domains__domain_cache-instance_route) can also be used to script this (and is a lot quicker at doing this, then the acquia_purge module). This API command kicks off a hosting task, that takes maybe 10-30 seconds to completely delete the Varnish cache for the site.

It would be useful, if this behaviour was opt in, rather than forced on you, as for some sites, this is suicide in production.

**Comment by grasmash** [comment]
@seanhamlin My assumption is that the Acquia purge module has integration with cache contexts and cache tags,  manually invoking a cloud API command does not seem like a substitute for that integration. Or is my assumption incorrect?

**Comment by dpagini** [comment]
It feels like this thread is discussing 2 different concepts...
1. The original poster is asking about purging varnish for an environment after a deploy of (presumably) code. I've done this with a cloud hook and the cloud API, [here](https://gist.github.com/dpagini/58e2d283ec393809ced4b58c3f3b190a) is an example. I could see this being available in BLT... when this function is invoked, it gets a list of all domains from the API, and clears varnish for each domain.
1. The Acquia Purge module, at least to my understanding, is a mechanism to clear varnish caches based on Drupal contexts/tags, as @grasmash just mentioned. Acquia Purge _sort of_ makes varnish invisible to the Drupal user where, presumably, if your caching works correctly with no varnish, it should work the same with varnish and purge.

**Comment by greylabel** [comment]
@dpagini Correct.

If Acquia Purge is working correctly, this an ideal setup, especially since it will work when there are multiple reverse proxies in play which would make a command to clear just Acquia Varnish of limited use. There are still situations when Varnish/CDN may need to be cleared wholesale, but as @seanhamlin mentioned this can be a terrible idea for perf and stability on some sites. Obviously @grasmash's call, but seems like BLT providing support for Cloud API could be a pretty big undertaking -- not sure it would be worth adding support for just this one command or at all. This may be better addressed in a separate project. @geerlingguy and I were playing with that idea at one point in (Acquia Cloud API scripts for CI/CD)[https://github.com/geerlingguy/acquia-cloud-api-scripts].

**Comment by grasmash** [comment]
I agree with @greylabel's summary. Using Acquia Purge seems to cover most use cases.

I do not think that it would be a good idea to automatically purge the entire varnish cash after each deployment. If you'd like to do that, I think it would be best to create a custom cloud hook.

**Comment by kkanku** [comment]
Guys, do you have any idea why Acquia caching a page and serving it from varnish without node tpl content?
