### ISSUE TITLE
Don't always overwrite files when doing a "composer update"

### ISSUE THREAD

**Issue by mike-potter** [acquia/blt#1202]
We are using BLT on a project, but not using Lightning.  Also, we have our own modifications to our .gitignore.  However, today when running "composer update" to get the latest Drupal 8.2.7, it overwrote several of our files, including composer.json (adding Lightning back in) and .gitignore.

This needs to be improved.  I can foresee many cases where I'd want to use BLT but want to make some project-specific changes.  BLT should only update these files the first time it runs (a fresh install) and not just when doing an update.

Or maybe some project-specific option could control this.

It's going to be a problem for us when the client takes over management of this site and can't just do a "composer update" to update their Drupal core version.

**Comment by grasmash** [comment]
@mike-potter There are configuration options to permit you to:
1. Opt out of updates to your files
2. Exclude specific composer requirements
http://blt.readthedocs.io/en/stable/readme/updating-blt/#modifying-update-behavior

See: 

Additionally, I've very recently change the composer file management strategy in 8.x so that the https://github.com/wikimedia/composer-merge-plugin is now used to manage composer dependencies. See updated docs:
http://blt.readthedocs.io/en/8.x/readme/updating-blt/#modifying-blts-default-composer-values

**Comment by mike-potter** [comment]
Thanks for the quick answer.  

We definitely want to keep BLT itself updated, so locking it doesn't seem like a good idea.  Not sure "merging" will help us since I'd assume that would still add stuff like Lightning and cog back into the composer.json file.  Also not clear how you omit certain files from the update (like .gitignore).  

I'll try the update:false option and see how that works.

**Comment by bobbygryzynger** [comment]
@mike-potter there is an open issue (#915) regarding `.gitignore` getting overridden during updates. It might be nice to get some additional input there regarding how projects can retain `.gitignore` customizations while still allowing BLT to provide some sensible defaults.

**Comment by justinlevi** [comment]
Yeah, I'm running into a similar situation where I definitely don't want lightning to be re-downloaded when I run $ `composer update` but I also want to keep BLT itself updated. Not overwriting our .gitignore is pretty important too.
