### ISSUE TITLE
Config splits cannot be applied to Acquia Cloud environments

### ISSUE THREAD

**Issue by arknoll** [acquia/blt#1298]
Issue on d.o.: https://www.drupal.org/node/2865912

We have to wait for this to be fixed before merging in the config-split default CM strategy.

@danepowell ^

**Comment by danepowell** [comment]
tl;dr: because of the way that Acquia Cloud defines the `/config/default` directory to be the `vcs` config directory, whereas most modules (including config_filter/config_split) assume you are using the default `sync` directory, there's currently no way to define config splits for Acquia Cloud environments.

A quick workaround might be to redefine the `sync` directory to be `/config/default` and pass this as the deploy config directory key instead of `vcs`. Or try the custom Drush command bircher suggested. Not sure what the best long-term solution is yet.

**Comment by grasmash** [comment]
@arknoll @danepowell this is resolved by #1299, right?

**Comment by danepowell** [comment]
It should be.

**Comment by arknoll** [comment]
yes. this can be closed
