### ISSUE TITLE
Upon trying to deploy, getting an error from git on the remote server

### ISSUE THREAD

**Issue by kevinquillen** [acquia/blt#1458]
Running the blt deploy command, the final step (pushing to remote build branch) fails with this output:

```
     [exec] remote: error: refusing to update checked out branch: refs/heads/develop-build
     [exec] remote: error: By default, updating the current branch in a non-bare repository
     [exec] remote: error: is denied, because it will make the index and work tree inconsistent
     [exec] remote: error: with what you pushed, and will require 'git reset --hard' to match
     [exec] remote: error: the work tree to HEAD.
     [exec] remote: error:
     [exec] remote: error: You can set 'receive.denyCurrentBranch' configuration variable to
     [exec] remote: error: 'ignore' or 'warn' in the remote repository to allow pushing into
     [exec] remote: error: its current branch; however, this is not recommended unless you
     [exec] remote: error: arranged to update its work tree to match what you pushed in some
     [exec] remote: error: other way.
     [exec] remote: error:
     [exec] remote: error: To squelch this message and still keep the default behaviour, set
     [exec] remote: error: 'receive.denyCurrentBranch' configuration variable to 'refuse'.
```

On the remote server, I tried setting `git config receive.denyCurrentBranch ignore`, but I still get this error.

How can I resolve this?

**Comment by grasmash** [comment]
Well this is a new one for me. It seems like a git issue rather than a BLT issue. I could be due to some the specific configuration that you have for your repo, or it could be due to some aberration in your git history. 

Here's what I would suggest:
* Execute `blt deploy --deploy.dryRun=true` on your local machine. This will generate the artifact locally and do everything but push.
* `cd` into the `deploy` directory and manually attempt to `git push` to your intended remote. You can then debug the push issue directly, without having BLT as an intermediary.

Did this problem just begin on a previously working repo, or is this a new repo that has never worked? I wonder if you can just remove the upstream branch manually and replace it with the build artifact.

**Comment by kevinquillen** [comment]
It sounds like for servers (not Acquia or not similar to Acquia) where this stuff is automatically handled, you have to create the workflow yourself, like:

https://www.digitalocean.com/community/tutorials/how-to-set-up-automatic-deployment-with-git-with-a-vps

**Comment by grasmash** [comment]
Hm. This seems outside the context of BLT. Please feel free to update issue if you find a resolution, but I'm going to mark the issue as closed.
