### ISSUE TITLE
Trying to onboard a developer, blt version bumps to 8.8.3

### ISSUE THREAD

**Issue by kevinquillen** [acquia/blt#1469]
* BLT version: 8.6.15

Using a project in-flight that was built with BLT 8.6.15, when he picks up the project and checks it out, and runs `composer install`, he is upgraded to BLT 8.8.3 which introduces architectural changes we are not expecting, such as this change to composer.json:

```
@@ -6,12 +6,6 @@
     "prefer-stable": true,
     "require": {
         "acquia/blt": "^8.3",
-        "drupal/core": "^8.0",
-        "drupal/features": "^3.0.0",
-        "drupal/memcache": "2.x-dev",
-        "drupal/seckit": "^1.0.0-alpha2",
-        "drupal/security_review": "*",
-        "drupal/shield": "^1.0.0",
         "drush/drush": "^8.1.8",
         "drupal/colorbutton": "^1.0",
         "drupal/admin_toolbar": "^1.18",
@@ -43,14 +37,7 @@
         "drupal/webform": "5.0.0-beta11"
     },
     "require-dev": {
-        "behat/behat": "^3.1",
-        "behat/mink": "~1.7",
-        "behat/mink-selenium2-driver": "^1.3.1",
         "drupal/console": "^1.0.0-rc13",
-        "drupal/drupal-extension": "^3.2",
-        "drupal-composer/drupal-scaffold": "^2.1.0",
-        "jarnaiz/behat-junit-formatter": "^1.3.2",
-        "se/selenium-server-standalone": "^2.53",
         "jakoch/phantomjs-installer": "^2.1.1-p07",
         "geerlingguy/drupal-vm": "~4.2",
         "drupal/twig_xdebug": "^1.0",
```

along with many contrib modules being removed from the require block.

Should we go back and specify the exact version in composer.json for BLT to stay compatible, or what sort of change are we looking at here? I don't quite grok the multiple composer files yet.

**Comment by grasmash** [comment]
Did you commit a composer.lock that locks BLT to 8.6.15?

**Comment by kevinquillen** [comment]
Nope - will that interfere with additions to composer.json later by committing the lock file?

**Comment by grasmash** [comment]
I'd suggest reading https://getcomposer.org/doc/01-basic-usage.md#installing-dependencies

If you do not have a composer.lock file, `composer install` effectively acts the same as `composer update`. Composer will download the latest version of BLT that is compatible with your version constraint. 

To ensure that 8.6.15 is installed, you'd need to have previously run `composer install` at a time when 8.6.15 was the latest version and then commit `composer.lock`. Then, during onboarding, your new dev would have gotten 8.6.15 when running `composer install`. 

Since you did not, you must specify 8.6.15 as the version constraint in composer.json and then run `composer install` to ensure that 8.6.15 is installed.

It is expected that you will commit composer.lock.

**Comment by grasmash** [comment]
> Nope - will that interfere with additions to composer.json later by committing the lock file?

You'll need to run `composer update` after each change to composer.json.
