### ISSUE TITLE
Twig Lint is not maintained and fails valid twig code

### ISSUE THREAD

**Issue by sarahjean** [acquia/blt#1543]
My system information:
* Operating system type: OSX/drupal-vm
* Operating system version: Sierra/drupal-vm 4.3
* BLT version: 8.7

When I run this command:
```
blt validate:twig
```

I get the following output:
(Removed some project specific paths and file names)
```
blt > validate:twig:
     [echo] Validating twig syntax for all custom modules and themes...
KO in [path/to/]templates/content/node--[somecontenttype].html.twig (line 22)
   20           #}
   21           {% for image in node.field_product_offering_images %}
>> 22             {% set isRowEnd = loop.index is divisible by(4) %}
>> Unexpected token "name" of value "by" ("end of statement block" expected).
   23             {% set imageUrl = image.url %}
   24             {% set imageTitle = image.title %}
```

And I expected this to happen:
`divisible by(4)` is valid twig syntax and should not fail https://twig.sensiolabs.org/doc/1.x/tests/divisibleby.html

There's an issue on the twig lint project and a couple of PRs that haven't been updated since 2015 for this problem

https://github.com/asm89/twig-lint/issues/25
https://github.com/asm89/twig-lint/issues/33

PR that would address:
https://github.com/asm89/twig-lint/pull/23

Filing this as it looks like we should probably patch this somehow, or find another linter that is being more actively maintained.

**Comment by grasmash** [comment]
@sarahjean Do you have another linter you'd suggest?

**Comment by sarahjean** [comment]
@grasmash Not currently, doing some research

**Comment by grasmash** [comment]
Would love for someone to close the loop on this, initial work was piloted here: https://github.com/grasmash/bolt/commit/20560e81099319c51be1b7bde642f39fd2bc8b6c  but reverted due to failed tests. Needs testing and re-factoring.

**Comment by wu-edward** [comment]
Spent some time on this one. The Symfony linter kept failing on Drupal's link() Twig function, but there's not a good way I've found to get the linter to be aware of those filters and functions without bootstrapping Drupal. Never mind any custom functions or filters that might be created. I just added the current Drupal filters and functions manually to the linter's Twig environment so that they'd be ignored, and created config that can be updated for any custom filters and functions.
