### ISSUE TITLE
Some files are not removed from build artifact

### ISSUE THREAD

**Issue by grasmash** [acquia/blt#157]
The following bug exists:
* Add `test.md` to repo root.
* Build deployment artifact. `test.md` is committed to artifact.
* Delete `test.md` from repo root.
* Build deployment artifact. `test.md` is not removed from artifact.

The current process for creating a deployment artifact is:

* Delete and recreate `deploy`
* `git init` in `deploy` dir.
* Add upstream remotes and `git fetch` upstream changes.
* `git checkout -b <destination-branch>` and `git merge <source-branch>`
* **review** Remove specific dirs from `deploy`. E.g., config, docroot, hooks, factory-hooks, patches, vendor, though I understand needing to remove `vendor` before `composer install`.
* **review** Copy specific files from `deploy/../` to `deploy`. E.g., config, docroot, hooks, factory-hooks, patches (ignoring contrib dirs).
* Execute `composer install` in `deploy`. 
* Build the make file for the active profile in `deploy`. 
* Build front end artifacts.
* Sanitize `deploy` dir.

The whole "delete & copy"  paradigm seems flawed to me. 

Possible alternatives:
* Use `rsync` with a delete flag.
* ...

**Comment by damontgomery** [comment]
This will be an issue with class renaming. The old class files won't get deleted. :(

**Comment by damontgomery** [comment]
The original goal was to prevent issues when the local site was not up to date. I recommend having the task fail in that case rather than do this weird work around.

- Create deploy directory
- Pull in the most recent version of the artifact branch
- Wipe the directory outside of .git folder
- Copy in the files as necessary
- Attempt a commit / push

This will ensure that the build artifact is clean and there isn't extra stuff in there from before.

We could create an optional flag for the deploy task that force pushes in case something goes wrong.

**Comment by danepowell** [comment]
To be clear, I'm pretty sure this is only a problem for files that exist in the repo root or outside of the "standard" directories (i.e. docroot, config, hooks, etc...). Which begs the question... why are files being created outside of these directories? Seems like an edge case that could be handled with a custom deploy step.

On the other hand, I don't see a problem in just nuking the deploy directory before copying files there, or using `rsync --delete`. Although we'd want to make sure to leave the git directory intact.

**Comment by grasmash** [comment]
https://github.com/acquia/blt/pull/162

**Comment by CashWilliams** [comment]
Used rsync --delete in the past, so ++ to that idea

**Comment by danepowell** [comment]
Seems like we can close this via #162
