### ISSUE TITLE
How to add scripts to VM build/provision process.

### ISSUE THREAD

**Issue by justclint** [acquia/blt#1781]
My system information:
* Operating system type: osx
* Operating system version: 10.12.5
* BLT version: 8.8.6

Not sure if this question has been asked but I did find this https://github.com/acquia/blt/pull/1754 which might be what I need.

The closest thing Ive found is box/config.yml:post_provision_tasks_dir and :post_provision_scripts but this doesnt seem like its what Im looking for.

Is there currently a method to add scripts to the VM build/provision process? 

Thanks!

**Comment by dpagini** [comment]
hey @justclint - saw your comment referenced on my PR, so I clicked through... let me see if I can help...

I haven't done this, but I think it should work... BLT copies a default `box/config.yml` into your project. I would just add a script to the "post_provision_scripts" YAML key.

So you're `box/config.yml` would look like...
```yml
post_provision_scripts:
  - "../../../acquia/blt/scripts/drupal-vm/post-provision.sh"
  - "../../../../path/to/script.sh"
```
I think the above command is running in the `vendor/geerlingguy/drupal-vm` folder, which is why there are so many "../.." in the path. You might have to play with that....

Does that help?

**Comment by grasmash** [comment]
I think this is a question better suited for the Drupal VM issue queue. Any post provision scripts will be executed by DVM itself. Please feel free to re-open if there's a BLT-related wrinkle to it.

**Comment by justclint** [comment]
Hi @dpagini , finally got this working. Adding a script to post_provision_scripts: is what I was doing before but it kept failing. But as you pointed out, that path got it working. So adding script to box directory worked like:

post_provision_scripts:
  - "../../../acquia/blt/scripts/drupal-vm/post-provision.sh"
  - "../../../../box/scripts/custom-provision.sh"

Thanks!
