### ISSUE TITLE
Provide Default Platform Configuration in Composer

### ISSUE THREAD

**Issue by mikemadison13** [acquia/blt#1888]
Currently the composer configuration in BLT is based on the host machine. This can be problematic for newer systems (running PHP 7) or systems that rely on their VMs to match production / cloud configuration.

I would propose that we add default platform settings to the composer.required.json file so that BLT defaults all composer dependencies to PHP 5.6. See: https://getcomposer.org/doc/06-config.md#platform

```
"config": {
  "platform": {
    "php": "5.6"
  }
},
```

**Comment by grasmash** [comment]
Why not default to 7?

**Comment by mikemadison13** [comment]
I'm not opposed to that as long as we document how to override it. The issue we are having on my project is that we are running PHP 5.6 but when we generate composer items on the hosts (which is running PHP 7) we are getting requirements problems.

**Comment by danepowell** [comment]
I've also been seeing this problem a ton lately. Usually it manifests itself like this:

* Create a BLT project on a local machine running php 7
* Push to github
* Composer install fails on Travis because doctrine libraries require php 7, while Travis only runs 5.6 by default
* Bang head against wall
* Pin all of the doctrine libraries to their older versions that support both php 5.6 and 7

So yeah, that's something we need to fix. Whatever solution we choose, though, it needs to be override able on a per-project basis, _and_ on a per-machine basis. In other words, if my host machine runs php7, but the project I'm developing for uses 5.6, I should still be able to run composer install from my host machine.

**Comment by mikemadison13** [comment]
@danepowell that's why i was suggesting we default to PHP 5.6, since I think most people are running PHP 5.6 still to match the cloud (but maybe I'm mistaken @grasmash ?)

**Comment by grasmash** [comment]
PHP 7 is available on Acquia Cloud and Travis CI.  I would prefer to default Drupal VM, Travis CI, Pipelines, and Composer to version 7.  We can then document how  this can be overridden.

**Comment by geerlingguy** [comment]
I'd prefer we default to 7.1 as well—two main things that gives us:

  1. Incentive for people to manually update cloud env's as soon as possible.
  2. 30-50% faster builds across the board (I wonder if we could get some stats from Travis on the project defaults?).

**Comment by danepowell** [comment]
I agree in most cases 7.1 is better, but my understanding is that it was still somewhat experimental on ACE:
https://docs.acquia.com/article/support-php-71-acquia-cloud

Although, the public documentation seems to conflict, since here 7.1 is "recommended":
https://docs.acquia.com/acquia-cloud/manage/php#php-version

/me shrugs, let's go with 7

**Comment by greylabel** [comment]
I am not sure 7 is any less experimental on ACE as it's not even a GA offering at this point.

+1 to 7.1 from me.
