### ISSUE TITLE
Versioning, backwards compatibility, and upgrade effort

### ISSUE THREAD

**Issue by danielnitschelc** [acquia/blt#1919]
Firstly, thanks for all the effort put into this project -- it's very much appreciated.

I've just attempted to upgrade from 8.9.0 to 8.9.2, and I've found that I'm now getting a bunch of code sniffing errors. This is partly because previously I was excluding my test files from being sniffed via a custom Filesets hook. Now that there is a `phpcs.xml.dist` file, this is no longer working. There also seems to be some new sniffs that weren't there previously (eg. DrupalPractice, and were yaml files previously sniffed?).

Is this not a breaking change that should be reserved for a more major release? (Or was I incorrectly overriding the filesets?)

I ask because I've also seen this with the switch from selenium to chrome driver (#1743) and the general switch from phing to robo (although I'm unsure if either of those were part of a major release or not).

I don't expect major upgrades to require no time/testing, but I do expect minimal changes on minor point releases.

Thoughts?

**Comment by grasmash** [comment]
This is a good conversation, thanks for bringing it up.

First of all, in regards to the issue that you're encountering, you can very easily override the PHPCS configuration for your application by following the instructions here: http://blt.readthedocs.io/en/8.x/readme/extending-blt/#validatephpcs. This change was considered a "backwards compatible" change because the workaround does not require any changes to your application, only changes to your project's BLT configuration.  Unfortunately the configuration modifications are not automatable because they are application-specific.

Regarding breaking changes in general, we are in a bit of a tricky situation. Unfortunately BLT does not use true semantic versioning because it reserves the first digit in its release number as an indication of the Drupal core major version that it is compatible with. E.g, in 8.9.0 the 8 indicates compatibility with Drupal 8 and we are left with only two digits to express major, minor, and patch releases of BLT itself.

As a result, we basically use the last digit to represent both patch releases and minor releases. We lose some flexibility there. This means that so-called patch updates can include changes that require manual configuration modifications.

I am open to changing this, as I imagine there is a good bit of interest in this issue. Improving the upgrade experience is definitely a priority for this project.

As I see it, there are a couple options:

1. We can stop reserving the first digit and start incrementing its to indicate major BLT version changes. Basically, this would allow us to use real semantic versioning. However, I don't really know how we are going to handle Drupal 9 and beyond. Is there even going to be one? I'm not sure how the new release cadence in core affects future major versioning of core.

2. We can become more strict by considering any backwards compatible change, major new feature, or any change requiring manual configuration updates to be a major version change. If we do this, we need to consider our release cadence. This would result in either making major version changes much more often, or else letting more changes pile up and effectively making major version releases larger.

I am very open to suggestions and ultimately interested in doing what is best for users.

Bringing a few more key contributors into this conversation to weigh-in: @danepowell @geerlingguy @arknoll @jrbeeman.

**Comment by danepowell** [comment]
If there's any way to bite the bullet and switch to true semantic versioning, I think that would be worthwhile. We don't even have to go all the way back down to 1.x.x, we could just start number from 8.x.x, right? So the next major release would be 9.0.0, etc...

I just don't know that it makes sense to tie our version to closely to hypothetical future Drupal releases. When that time comes, hopefully we can either be compatible with both Drupal 8.x and 9.x, or have a brief period where we distinguish between the two branches some other way.

That will free us up to have a true distinction between patch releases and minor releases, which will help a lot.

Finally, even for minor releases, I think we need to find better ways of documenting or automating changes. I was also surprised when PHPCS started failing after upgrading from 8.9.0 to 8.9.1, and while it was a relatively easy fix, I would have preferred to not be surprised in the first place.

**Comment by grasmash** [comment]
That is also my preferred option.  Composer makes the assumption that a given package utilizes semantic versioning. It would be best to follow the built in assumptions. Glad to have other people on the same page. 

For the next major release, we will start with 9.0.0.  There are some commits in the current development branch which I have been reserving for a major release, mostly relating to a default requirement for PHP 7.x.  That will provide a good opportunity for switching to the new approach.

**Comment by dpagini** [comment]
I liked @danepowell's point the most about supporting Drupal 8 AND 9 in the future as a great reason to go semver. I would assume "support tools" (thinking drush) would be mostly backwards compatible with D8. It will be interesting when that day comes what kinds of differences the project would need to implement to work with both... ideally just some composer packages, right? Maybe different versions of `composer.required.json`. I'm sure it will be more than that...

**Comment by danielnitschelc** [comment]
Thanks for the discussion. I agree with a lot that's been said, and it seems like some good decisions have been made. I especially agree with:

> It's really important (IMO) to be able to use the minor vs. patch difference—e.g. 8.9.0 has a critical bug, so release 8.9.1 with that fix and people know it's perfectly safe to update.

> Anything that would require any changes or manual settings reversions would be at least a minor (8.10.0), and any major features (like Phing to Robo, or switching out Drupal VM for something else) would warrant a 9.x bump.

I don't agree with this however:

> This change was considered a "backwards compatible" change because the workaround does not require any changes to your application, only changes to your project's BLT configuration.

because:

1. We did have to make changes to our application to support the new coding standards.
2. I'm assuming any previous config would probably stop working (https://github.com/acquia/blt/commit/daed7b265d7d5a74008723db31d59c52370cb358)

This change could probably have been better described in the release notes as well, as it's referenced around "haltonwarning no longer available" rather than filesets being removed: https://github.com/acquia/blt/releases/tag/8.9.2
