### ISSUE TITLE
Validation doesn't occur in multisite paths

### ISSUE THREAD

**Issue by bobbygryzynger** [acquia/blt#2061]
My system information:
* BLT version: `8.x`

When I run this command:
```
blt validate:*
```
I get no warning/errors when code style violations exist in multisite paths.

BLT should ensure the following paths are sniffed:
- `sites/*/themes/custom` 
- `sites/*/modules/custom`

**Comment by grasmash** [comment]
I've added these paths to PHPCS config. However, these paths are not evaluated for yaml, twig, or any other validations. That is more tricky because the paths need to exist in order for Symfony's Finder component to be able to scan them.

However, I feel that the use of such directories is a bit outdated now that we manage packages centrally with Composer and enable/disable via CM.

**Comment by grasmash** [comment]
Yikes, it looks like we can't set default paths for PHPCS to scan unless they exist.

I'm going to mark this as "won't fix" for now. Feel free to make the argument that there's a valid use case for the "sites/*/[modules|themes]" dirs and we can revisit.

We could workaround the limitations of Symfony and PHPCS by adding a default "sites/default/modules" dir or something similar.

**Comment by bobbygryzynger** [comment]
I guess my use case argument for this would be that often (at least for my team) there are small bits of functionality we need that we create a `<project>_core` module for to extend existing functionality. This module has no broader usage outside of a particular project and therefore it doesn't make sense that we would add it as a globally available module - nonetheless, we still want it to adhere to all coding standards. 

The same thing applies to themes in that there are often small project-specific themes that introduce small overrides that are only necessary for a single project.
