### ISSUE TITLE
Documentation- release notes script page not found

### ISSUE THREAD

**Issue by sjayanths** [acquia/blt#2216]
The link in Release process (http://blt.readthedocs.io/en/latest/readme/release-process/),
http://blt.readthedocs.io/en/latest/readme/scripts/release-notes/README.md this link is leading to 404.
Can you please point me to the right place to find this script.

**Comment by danepowell** [comment]
It looks like that release notes script no longer exists.

The closest thing that BLT has now is the release notes commands here, but they are really meant for releases of _BLT_, not releases of downstream projects.

I've removed the reference to that script for now: https://github.com/acquia/blt/blob/9.1.x/readme/release-process.md

Here is the script as it used to exist, but I have no idea if it still works, since it's two years old: https://github.com/acquia/blt/tree/2da54a3c5df4fcf1c8b8c5ea1f9252130565a679/template/scripts/release-notes
