### ISSUE TITLE
Use Docker for DrupalVM

### ISSUE THREAD

**Issue by danepowell** [acquia/blt#2310]
https://www.jeffgeerling.com/blog/2017/drupal-vm-does-docker

**Comment by geerlingguy** [comment]
LMK what I can do to help support this; there are basically two ways to use Drupal VM with Docker:

  1. Use the pre-built Drupal VM image, which is inflexible but includes all the default stuff (kind of like beet/box, but a Docker image instead of a Vagrant box).
  2. Use BLT to build a custom Docker image for the project, then that image is hosted somewhere (could even be Google Drive or Dropbox) and shared between the project team.

One note: There are a number of minor but potentially-irritating changes that ride along with using Docker instead of Vagrant:

  - No auto-networking stuff (harder (not impossible) to do ngrok, public IP, specialized networking setups, some sorts of proxy setups, etc.
  - No auto-hosts file updating (so user would need to do extra work if user wants to use something like `local.myproject.com`).
  - Currently limited to 1 project actively running within Docker at a time (though this can be worked around by not using Drupal VM in Docker exactly as the docs say).

**Comment by grasmash** [comment]
It sounds like this switch would come with a number of pitfalls. I'd prefer not to add this to the roadmap, but I'd be open to reviewing a PR.

Ideally, we'd make this switch when Drupal VM makes it the default VM provider. We shouldn't support multiple Drupal VM approaches in BLT. 

Remember that our VM integration has no test coverage and is a major source of support requests. We need to keep the scope of it as small as we can.
