### ISSUE TITLE
Deploying code from local to acquia cloud - what command(s) should I run?

### ISSUE THREAD

**Issue by therobyouknow** [acquia/blt#2329]
How do I actually deploy a website running locally on a BLT/Drupal VM to a remote acquia cloud?
- How do I deploy both the code and the db? (I know about blt deploy and remote in project.yml but it still fails insisting I create a Robo command - https://github.com/acquia/blt/issues/2323 )
- Do I have to write a Robo command to deploy the code and db? This is a common task - why would one have to do this?

My system information:
* Operating system type: Mac OS X
* Operating system version: 10.12.6
* BLT version: BLT 8.9.10

Output of `blt doctor`: 
```
n/a
```

When I run this command:
```
n/a
```

I get the following output:
```
n/a
```

And I expected this to happen:
n/a

**Comment by smutek** [comment]
Not sure if this helps you but what I did for initial setup was to use `blt deploy` to get my local code base up. This creates a master-build branch on the cloud instance.  

Next I switched my cloud instance (develop) to the master-build branch, then used `drush sql-sync` to push my db, then `drush rsync` to push the files. I tried `drush rsync @mylocal.alias:%files/ @myremote.alias:%files` and ran into [this issue](https://github.com/drush-ops/drush/issues/2613). I finally got my local files up by passing the local path and the remote alias, like `drush rsync path/to/mylocal/files/ @myremote.alias:%files` 

Once that was done I did `drush @myremote.alias cr` and also `drush @myremote.alias updatedb` and my remote was not in sync to my local. 

From here general deployment workflow would just be via the `blt` commands. If I understand correctly there's no blt command to sync database and files from local to production, but you'd use `blt sync` to get your remote code and database. You can get the files with `blt sync:files` and you can enable files to run by default by setting `sync.files` to true in your project.yml. ([more info here](https://www.google.com/search?q=blt+sync+files&ie=utf-8&oe=utf-8&client=firefox-b-1-ab))

Also, it seems that `blt deploy` deploys to the dev machine by default, but `blt sync` pulls from the stage machine (aka test) on cloud. This threw me off at one point when I did a sync but had not yet moved my code and db from dev to stage on AC.

Hope that helps.

**Comment by therobyouknow** [comment]
Thank you very much @smutek this looks really informative. I will go through it and feedback.

**Comment by therobyouknow** [comment]
Setting up drush aliases, in particular were they should be located, seems to be a secretive art, as there is (almost) no quick easy read definitive guide.

However, I did find this, which seems to cover it: http://e9p.net/drush-aliases

**Comment by danepowell** [comment]
@therobyouknow did you read http://blt.readthedocs.io/en/latest/readme/deploy/?

The command to deploy your codebase is simply `blt deploy`, although there is some minimal configuration required for that to work.

There is no built-in command to deploy files or db (this is the first time I've heard anyone request such a feature). But it should be fairly easy to do this with Drush commands, you don't even really need BLT for it, unless you want to create an all-in-one wrapper command that pushes codebase, files, and DB all at once.

Theoretically, I suppose you could "trick" the `sync` command into pushing files instead of pulling them by simply swapping the local and remote Drush aliases, but this isn't really supported. Something like:
`blt sync -D drush.aliases.remote=@my-project.local -D drush.aliases.local=@my-project.remote`

**Comment by grasmash** [comment]
This issue combination of problems, as addressed in #2323 and #2330.  

I agree that there is a documentation issue. We should document how you can go about pushing a database and drupal-managed files to an upstream endpoint.  I have opened #2360 to address this.
