### ISSUE TITLE
environment config file and travis run_tests script

### ISSUE THREAD

**Issue by dpagini** [acquia/blt#2343]
I have two related issues I wanted to bring up, and potentially get some feedback on before I submit potential PRs.

I'm currently on BLT v**8.9.10** and I'm trying to set up some unique Travis behavior for testing on a custom domain & subdomain instead of http://127.0.0.1.
One minor question I have is: I'm wondering if there's any reason BLT uses localhost IP out of the box instead of setting up some kind of [custom hostname in Travis](https://docs.travis-ci.com/user/hostname)? It's working so far for me, but just wondering if I'm overlooking some gremlin that will bite me in the future...?

Anyways, since I'm using this custom domain, I need to set `tests.server.url` and `project.local.hostname` to get this to run correctly. I first tried editing my `blt/ci.yml` file, but I realized that it seems on 8.9.10, this file [is not being included](https://github.com/acquia/blt/blob/8.9.x/bin/blt-robo-run.php#L34).
When I run this command...
`$ blt config:get --define environment=ci project.local.hostname`
I am expecting to get the value in my `blt/ci.yml` file, but I don't get that. This, to me, feels like a 🐞 bug in 8.9.10 (I see this whole process was tweaked in 9.x), but I don't know offhand how to fix this. Would calling this a bug in 8.9 be fair?

Second, I realized that even if I _could_ set these properties in my `blt/ci.yml` file, it wouldn't completely help me with my problem. This is because the `vendor/acquia/blt/scripts/travis/run_tests` script does not pass `--define environment=ci` into the `$ blt tests:all` command. 
Is there any reason this script shouldn't be using that file when invoking this command? I'd like to propose a PR to fix that. What branches should I fix this against?

Thanks!

_j/w - what is the ETA around a 9.x release? Anywhere to monitor the status of that?_

**Comment by danepowell** [comment]
I think BLT uses localhost/127.0.0.1 for automated tests only because that was what worked out of the box, and it will work in pretty much any environment. I'm not sure you could always set a hostname in Travis, and there may be other places where you still can't.

Indeed it seems like a bug that ci.yml is not being loaded at all. Your proposal to also load it for tests makes sense, I think we didn't do that before simply because we only expected people to use it for defining setup strategies. I'll open a PR.

I'm guessing you're looking for the 9.1.x release. 9.x won't have any new features, it will just be compatible with Drush 9, whereas 9.1.x will have a lot more improvements especially around ACSF and DrupalVM. The best ETA I can give you is sometime in the next month or so. Basically watch this milestone, when the open issues drop to zero we'll probably release 9.1.0: https://github.com/acquia/blt/milestone/6
