### ISSUE TITLE
Command organization and naming

### ISSUE THREAD

**Issue by danepowell** [acquia/blt#2452]
My system information:
* BLT version: 9.1.x

The organization of BLT commands has grown organically over time, and I think it's worth taking a holistic view of the organization and naming convention (such as it is), and considering if we want to make any changes before the 9.1.x stable release.

I'm mainly concerned with the top-level organization of commands, and that we seem to have a mix of naming things based on what they _do_ and naming them based on what they're _related to_. I'm also concerned about the accessibility for newcomers who might be overwhelmed by the ever-growing quantity of commands.

For instance, we're starting to see a lot of generators that set up specific integrations and/or config files based on templates, such as `generate:aliases:acquia`, `generate:multisite`, etc... I would call this a "verb-first" naming convention, for lack of a better term.

But we have a lot of commands that basically just generate config files that are part of other namespaces, such as `acsf:init` and `vm`. These are organized around a noun first, i.e. what they relate to (acsf, vm, etc...). And then there's real oddballs like `setup:cloud-hooks`, that are just totally out of place.

It doesn't make sense to me that we use both types of naming conventions, and it makes it hard sometimes to predict where to find a given command.

I'm thinking a verb-first approach is best, since I tend to think in terms of what I want to _do_ (setup, test, deploy) first. This also can help to distinguish between commands with fundamentally different purposes, and meant for different project roles. For instance, all of the commands that set up specific integrations and modify the codebase (generate, vm, cloud hooks, etc...) generally only need to be run once per project, and serve a fundamentally different purpose from day-to-day commands like `setup` and `test` that are non-mutative, and would most often be run by devs and QA teams, respectively.

## Current Proposal
```
 help
 list
 
artifact
 artifact:build
 artifact:build:simplesamlphp:config
 artifact:deploy

blt
 blt:cleanup
 blt:config:dump
 blt:config:get
 blt:doctor
 blt:init
 blt:init:git-hooks
 blt:init:hash-salt
 blt:init:settings
 blt:init:shell-alias
 blt:update
 
drupal
 drupal:config-import
 drupal:install
 drupal:sql-import
 drupal:sync
 drupal:sync:db
 drupal:sync:db:all
 drupal:sync:files
 drupal:toggle-modules
 drupal:update
 
recipes
 recipes:acsf:init
 recipes:acsf:init:drush
 recipes:aliases:acquia
 recipes:ci:gitlab:init
 recipes:ci:pipelines:init
 recipes:ci:probo:init
 recipes:ci:travis:init
 recipes:cloud-hooks:init
 recipes:config-splits:init
 recipes:drupalvm:destroy
 recipes:drupalvm:init
 recipes:multisite:init
 recipes:simplesamlphp:init
 
source
 source:build
 source:build:composer
 source:build:frontend
 source:build:frontend:assets
 source:build:frontend:reqs
 source:build:simplesamlphp:config
 source:fix:phpcbf
 
tests
 tests:all
 tests:behat
 tests:behat:definitions
 tests:behat:init
 tests:behat:init:phantomjs
 tests:frontend
 tests:phpunit
 tests:security:updates
 tests:validate
 tests:validate:composer
 tests:validate:php-lint
 tests:validate:phpcs
 tests:validate:phpcs:files
 tests:validate:twig
 tests:validate:twig:files
 tests:validate:yaml
 tests:validate:yaml:files
 
internal (hidden)
 internal:add-to-project
 internal:composer:install
 internal:composer:require
 internal:create-project
 internal:create-project:init-repo
 internal:git-hook:commit-msg
 internal:git-hook:pre-commit
```

**Comment by grasmash** [comment]
> I'm thinking a verb-first approach is best

Agree. Actually, @damontgomery, @TravisCarden, and I were just discussing this last week.

**Comment by TravisCarden** [comment]
Thanks, @grasmash! I've been thinking about this, and I, too, imagined a verb-first approach. When I started trying to map it out, however, I began to question my intuition because verbs are so context-sensitive that they proliferate and lead to a wide, shallow hierarchy. Then I considered that Drush commands tend to be noun-first, as is the Drupal API, and REST provides a good precedent. So I took a crack at that. It's not perfect (or probably even complete), but here's what I came up with:

* `help`
* `list`
* `app`
  * `app:config-import`
  * `app:install`
  * `app:refresh`
  * `app:refresh:all`
  * `app:sql-import`
  * `app:sync:db`
  * `app:sync:db:all`
  * `app:sync:files`
  * `app:toggle-modules`
  * `app:update`
* `blt`
  * `blt:cleanup`
  * `blt:config:dump`
  * `blt:config:get`
  * `blt:doctor`
  * `blt:generate-settings`
  * `blt:init`
    * `blt:init:bash-alias`
    * `blt:init:frontend`
    * `blt:init:git-hooks`
    * `blt:init:hash-salt`
  * `blt:update`
* `code`
  * `code:artifact`
    * `code:artifact:build`
    * `code:artifact:deploy`
  * `code:build`
    * `code:build:composer`
    * `code:build:frontend`
  * `code:fix:phpcbf`
  * `code:validate`
    * `app:validate:composer`
    * `app:validate:php-lint`
    * `app:validate:phpcs`
    * `app:validate:phpcs:files`
    * `app:validate:twig`
    * `app:validate:twig:files`
    * `app:validate:yaml`
    * `app:validate:yaml:files`
* `recipes`
  * `recipes:acsf:init`
  * `recipes:acsf:init:drush`
  * `recipes:ci:gitlab:init`
  * `recipes:ci:pipelines:init`
  * `recipes:ci:probo:init`
  * `recipes:ci:travis:init`
  * `recipes:cloud-hooks:init`
  * `recipes:simplesamlphp:init`
  * `recipes:simplesamlphp:build:config`
  * `recipes:simplesamlphp:deploy:config`
  * `recipes:vm:init`
  * `recipes:vm:rm`
* `tests`
  * `tests:all`
  * `tests:behat`
    * `tests:behat:definitions`
    * `tests:behat:init`
    * `tests:behat:init:phantomjs`
  * `tests:frontend`
  * `tests:phpunit`
  * `tests:security-updates`
* `internal`
  * `internal:composer:install`
  * `internal:composer:require`
  * `internal:git-hook:commit-msg`
  * `internal:git-hook:pre-commit`
  * `internal:add-to-project`
  * `internal:create-project`
  * `internal:create-project:init-repo`

**Comment by grasmash** [comment]
@TravisCarden Thank you. I see your point.

Can you explain why `app:validate:composer` is nested under `code:validate`?

**Comment by TravisCarden** [comment]
@grasmash, I've added the current commands that roughly correspond to my proposals to clarify such questions. Does that help?

**Comment by grasmash** [comment]
Suggested changes:

* `help` [help]
* `list` [list]
* `app`
    * `app:config-import` [setup:config-import]
    * `app:install` [setup:drupal:install] / [deploy:drupal:install] / [internal:drupal:install]
    * `app:sql-import` [setup:import]
    * `app:sync` [sync]
        * `app:sync:db` [sync:db]
        * `app:sync:db:all` [sync:db:all]
        * `app:sync:files` [sync:files]
    * `app:toggle-modules` [setup:toggle-modules]
    * `app:update` [setup:update] / [deploy:update]
* `blt`
    * `blt:cleanup` [cleanup]
    * `blt:config:dump` [config:dump]
    * `blt:config:get` [config:get]
    * `blt:doctor` [doctor]
    * `blt:generate-settings` [setup:settings]
    * `blt:init`
        * `blt:init:shell-alias` [install-alias]
        * `blt:init:frontend` [frontend:setup]
        * `blt:init:git-hooks` [setup:git-hooks]
        * `blt:init:hash-salt` [setup:hash-salt]
    * `blt:update` [update]
* `code`
    * `code:artifact`
        * `code:artifact:build` [deploy:build]
        * `code:artifact:deploy` [deploy]
        * `code:artifact:simplesamlphp:config` [simplesamlphp:deploy:config]
    * `code:build` [setup:build]
        * `code:build:composer` [setup:composer:install]
        * `code:build:frontend` [frontend:build]
        * `code:build:simplesamlphp:config` [simplesamlphp:build:config]
    * `code:fix:phpcbf` [fix:phpcbf]
    * `code:validate`
        * `code:validate:composer` [validate:composer]
        * `code:validate:php-lint` [validate:lint]
        * `code:validate:phpcs` [validate:phpcs]
        * `code:validate:phpcs:files` [validate:phpcs:files]
        * `code:validate:twig` [validate:twig]
        * `code:validate:twig:files` [validate:twig:files]
        * `code:validate:yaml` [validate:yaml]
        * `code:validate:yaml:files` [validate:yaml:files]
* `recipes`
    * `recipes:acsf:init` [acsf:init]
    * `recipes:acsf:init:drush` [acsf:init:drush]
    * `recipes:ci:gitlab:init` [ci:gitlab:init]
    * `recipes:ci:pipelines:init` [ci:pipelines:init]
    * `recipes:ci:probo:init` [ci:probo:init]
    * `recipes:ci:travis:init` [ci:travis:init]
    * `recipes:cloud-hooks:init` [setup:cloud-hooks]
    * `recipes:simplesamlphp:init` [simplesamlphp:init]
    * `recipes:dvm:init` [vm:config]
    * `recipes:dvm:destroy` [vm:nuke]
* `tests`
    * `tests:all`
    * `tests:behat` [tests:behat]
        * `tests:behat:definitions` [tests:behat:definitions]
        * `tests:behat:init` [setup:behat]
        * `tests:behat:init:phantomjs` [tests:configure-phantomjs]
    * `tests:frontend` [frontend:test]
    * `tests:phpunit` [tests:phpunit]
    * `tests:security-updates` [tests:security-updates]
* `internal` (hidden)
    * `internal:composer:install` [setup:composer:install]
    * `internal:composer:require` [composer:require]
    * `internal:git-hook:commit-msg` [git:commit-msg]
    * `internal:git-hook:pre-commit` [git:pre-commit]
    * `internal:add-to-project` [internal:add-to-project]
    * `internal:create-project` [internal:create-project]
    * `internal:create-project:init-repo` [internal:create-project:init-repo]


Questions/Comments:
* How can we combine [setup:drupal:install] / [deploy:drupal:install] / [internal:drupal:install]?
* Where are the generate commands like `generate:aliases:acquia` and `generate:config-splits` ?
* What happened to `setup`?
* `blt:init:frontend` doesn't seem to communicate that it will install frontend dependencies by executing the value of `target-hooks.frontend-setup.command` config key. Maybe `code:build:frontend-reqs`? Perhaps this key should be renamed too. 
 * I'm a bit concerned about the length of these. It's just inconvenient to type `code:artifact:deploy` rather than `deploy`. Maybe we need to add aliases like `cad`.

**Comment by TravisCarden** [comment]
Let me take a look at the suggested changes. (It's not immediately obvious what's different.) In the meantime, in answer to your questions...

1. **How can we combine [setup:drupal:install] / [deploy:drupal:install] / [internal:drupal:install]?**

    I'm not sure what the distinctions are between those. Based on their names I would assume they're identical except in terms of their target or context, so I grouped them as made the most intuitive sense to me. I don't assume the collapse would work as-is.

1. **Where are the generate commands like generate:aliases:acquia and generate:config-splits?**

    I may have just overlooked them. They seem like `recipes`, as I scoped them.

1. **What happened to setup?**

    I moved its subcommands into the categories where they made more sense to me. I expected that `blt:init` would more or less take it over.

1. **blt:init:frontend doesn't seem to communicate that it will install frontend dependencies by executing the value of target-hooks.frontend-setup.command config key. Maybe code:build:frontend-reqs? Perhaps this key should be renamed too.**

    Yeah, I wasn't sure about the `frontend` commands, since the help text just says that they execute hooks. Is it completely arbitrary? Should we just named it accordingly, e.g., `blt:init:frontend-hook`?

1. **I'm a bit concerned about the length of these. It's just inconvenient to type code:artifact:deploy rather than deploy. Maybe we need to add aliases like cad.**

    Yeah, me, too. I considered making `artifact` a top level command. Maybe we should articulate some design goals that guide such decisions.

**Comment by grasmash** [comment]
Hm. `blt:init` as described only does a small portion of what `setup` does. `setup` is essentially a special wrapper command that will do the `blt:init` work for you` but also execute the right `app:`* commands to get a working app in place. It's kind of like a "do all the things" command, which is valuable as a development aid. I think we still need a command that serves that purpose.

**Comment by TravisCarden** [comment]
Understood. My proposal is that `blt:init` be made to serve the full function that `setup` currently does.

Re: Your suggested changes...

```diff
6,7d5
<     * `app:refresh` [sync:refresh]
<     * `app:refresh:all` [sync:refresh:all]
9,11c7,10
<     * `app:sync:db` [sync:db]
<     * `app:sync:db:all` [sync:db:all]
<     * `app:sync:files` [sync:files]
---
>     * `app:sync` [sync]
>         * `app:sync:db` [sync:db]
>         * `app:sync:db:all` [sync:db:all]
>         * `app:sync:files` [sync:files]
21c20
<         * `blt:init:bash-alias` [install-alias]
---
>         * `blt:init:shell-alias` [install-alias]
29c28,29
<         * `code:artifact:deploy`
---
>         * `code:artifact:deploy` [deploy]
>         * `code:artifact:simplesamlphp:config` [simplesamlphp:deploy:config]
32a33
>         * `code:build:simplesamlphp:config` [simplesamlphp:build:config]
52,55c53,54
<     * `recipes:simplesamlphp:build:config` [simplesamlphp:build:config]
<     * `recipes:simplesamlphp:deploy:config` [simplesamlphp:deploy:config]
<     * `recipes:vm:init` [vm:config]
<     * `recipes:vm:rm` [vm:nuke]
---
>     * `recipes:dvm:init` [vm:config]
>     * `recipes:dvm:destroy` [vm:nuke]
65c64
< * `internal`
---
> * `internal` (hidden)
```

I love all of that except that 1) I would say `drupalvm` instead of `dvm`. I heard "DVM" for the first time literally yesterday. I think we should avoid ambiguous abbreviations. And 2) are you proposing that `app:sync` do what `refresh` does today? Or do you mean for it to execute all of its children (which I wouldn't consider desirable, since the DB commands seem mutually exclusive and the files command is often not wanted.

**Comment by grasmash** [comment]
I'm suggesting that `app:sync` replace `sync:refresh`.

**Comment by damontgomery** [comment]
Here is my suggested command names with some information afterwards of why this makes sense to me.

Main commands
```
build:artifact
build:artifact:setup
build:composer
build:frontend
build:simplesamlphp

init:behat
init:blt-alias
init:drupal:settings
init:frontend
init:git-hooks
init:phantom-js
init:vm

install:acquia-hooks:cloud
install:acquia-hooks:acsf
install:acsf
install:acsf:refresh
install:drush-aliases:acquia
install:drush-aliases:multisite
install:ci:gitlab
install:ci:pipelines
install:ci:probo
install:ci:travis
install:drupal:hash-salt
install:simplesamlphp

manage:blt:cleanup
manage:composer:add-package
manage:drupal:db:import-backup
manage:drupal:db:import-remote
manage:drupal:export-config
manage:drupal:files:import-remote
manage:drupal:import-config
manage:drupal:install
manage:drupal:multi:db:import-remote
manage:drupal:multi:refresh
manage:drupal:refresh
manage:drupal:toggle-modules
manage:drupal:update-database
manage:test-webserver:start
manage:test-webserver:stop
manage:vm:destroy

test:behat
test:composer
test:deprecated
test:frontend
test:git:commit-message
test:git:staged-files
test:php-lint
test:phpcs
test:phpcs:files
test:phpunit
test:security-updates
test:twig
test:twig:files
test:yaml
test:yaml:files
```

misc commands
```
audit:blt-doctor
audit:blt-status
audit:drupal:config-variable
fix:phpcbf
help
list
```

I think the primary verbs for BLT are `install`, `initialize`, `manage`, `test`, and `build`.

I think the verbs are important because they clearly demonstrate the state changing nature of the things.

`install` is a one time command to `add` something to the repository.
`initialize` is a one time command for a local instance to set something up.
`manage` is a repeated action when you need to change the state of something outside of the code repository. You need to change the database or turn off a VM.
`test` gives you information without adding or changing state.
`build` creates something that normally only exists as instructions.

I think these names are common throughout programming tools and software. Enough that they aren't too ambiguous and are not false friends.

I think this grouping also fits well into roles that people usually take on a project. A person will start off by setting up a project and `installing` the needed components. A developer when starting will need to `initialize` their environment. After that, the developer will need to continually `manage` their environment. A CI server will focus more on `testing` and `building`.

You could argue that the names are too long, but people will mostly be running the command `manage:drupal:refresh`. If you want an alias for that, you could add one like `mdr`. No one will make assumptions about what `mdr` does since it's meaningless by itself. However, it's there if people want to type less.

**Comment by TravisCarden** [comment]
I like what you've come up with, too, @damontgomery! Per discussion with @grasmash, I'm going to put together a survey to gather wider community feedback, which I will link to here when available.

**Comment by grasmash** [comment]
Related https://github.com/acquia/blt/issues/1524

**Comment by TravisCarden** [comment]
The survey is ready at https://docs.google.com/forms/d/e/1FAIpQLSevUditb23M6NGIwfy-fQcXnguhuqiFBeWMIZ_858rJGkjtAg/viewform.

**Comment by danepowell** [comment]
I like the proposals so far, but if we're going noun-first, I'm tempted to modify the test and validate commands. They are still pseudo verb-first (I feel like we're sort of escaping on a technicality by saying "tests" instead of "test"). Would it make more sense to arrange them like this?

* code:composer:validate
* code:php:lint
* code:php:phpcs
* code:twig:validate
* code:yaml:validate
* behat:test
* behat:init
* frontend:test
* phpunit:test

**Comment by grasmash** [comment]
With 20 responses to the survey, we’re at ~50% verb and 40% noun. Not as definitive as I would have liked. It's the difference of two votes, which feels like a toss-up.

I've spent some item seriously considering the verb-first approach. However, and while I do think that it has merits, I do not feel that the verb-first commands represent their functionality as well as the noun first commands. 

Additionally, I feel that the verb-first namespaces are easily conflated. I could make arguments to move `install:acsf` to `init:acsf`, `init:frontend` to `install:frontend`, `manage:test-webserver:start` to `test:webserver:start`, `manage:drupal:install` to `install:drupal`, etc.  Many things just don't fit definitively into a given namespace.

By contrast, with the noun-first approach, things do fall more neatly and more definitively into namespaces. Not perfectly, but better.

Given the relatively even survey results and my own gut-feeling about it, I'm inclined to choose a noun first approach.

That being said, I'd still like to revise and refine the noun-first command list to incorporate some organizational principles from the verb-first proposal. 

Suggestions for the noun command list:

* Change `app` to `drupal`.
* Consider 'code:validate:*` commands to be types of tests, and move to the `test:validate:` namespace, as suggested by the verb-first proposal. They are types of tests even if what they are testing is static code rather than executed code.
* 

* `help` [help]
* `list` [list]
* `drupal`
    * `drupal:config-import` [setup:config-import]
    * `drupal:install` [setup:drupal:install] / [deploy:drupal:install] / [internal:drupal:install]
    * `drupal:sql-import` [setup:import]
    * `drupal:sync` [sync]
        * `drupal:sync:db` [sync:db]
        * `drupal:sync:db:all` [sync:db:all]
        * `drupal:sync:files` [sync:files]
    * `drupal:toggle-modules` [setup:toggle-modules]
    * `drupal:update` [setup:update] / [deploy:update]
* `blt`
    * `blt:cleanup` [cleanup]
    * `blt:config:dump` [config:dump]
    * `blt:config:get` [config:get]
    * `blt:doctor` [doctor]
    * `blt:init`
        * `blt:init:shell-alias` [install-alias]
        * `blt:init:git-hooks` [setup:git-hooks]
        * `blt:init:hash-salt` [setup:hash-salt]
        * `blt:init:settings` [setup:settings]
    * `blt:update` [update]
* `code`
    * `code:build:artifact`
        * `code:build:artifact:build` [deploy:build]
        * `code:build:artifact:deploy` [deploy]
        * `code:build:artifact:simplesamlphp:config` [simplesamlphp:deploy:config]
    * `code:build:local` [setup:build]
        * `code:build:local:composer` [setup:composer:install]
        * `code:build:local:frontend` [frontend]
            * `code:build:local:frontend:assets` [frontend:build]
            * `code:build:local:frontend:reqs` [frontend:setup]
        * `code:build:local:simplesamlphp:config` [simplesamlphp:build:config]
    * `code:fix:phpcbf` [fix:phpcbf]
* `recipes`
    * `recipes:acsf:init` [acsf:init]
    * `recipes:acsf:init:drush` [acsf:init:drush]
    * `recipes:ci:gitlab:init` [ci:gitlab:init]
    * `recipes:ci:pipelines:init` [ci:pipelines:init]
    * `recipes:ci:probo:init` [ci:probo:init]
    * `recipes:ci:travis:init` [ci:travis:init]
    * `recipes:cloud-hooks:init` [setup:cloud-hooks]
    * `recipes:simplesamlphp:init` [simplesamlphp:init]
    * `recipes:drupalvm:init` [vm:config]
    * `recipes:drupalvm:destroy` [vm:nuke]
    * `recipes:multisite:init` [generate:multisite]
    * `recipes:aliases:acquia` [generate:aliases:acquia]
    * `recipes:config-splits:init` [generate:config-splits]
* `tests`
    * `tests:all`
    * `tests:behat` [tests:behat]
        * `tests:behat:definitions` [tests:behat:definitions]
        * `tests:behat:init` [setup:behat]
        * `tests:behat:init:phantomjs` [tests:configure-phantomjs]
    * `tests:frontend` [frontend:test]
    * `tests:phpunit` [tests:phpunit]
    * `tests:security:updates` [tests:security-updates]
    * `tests:validate`
        * `tests:validate:composer` [validate:composer]
        * `tests:validate:php-lint` [validate:lint]
        * `tests:validate:phpcs` [validate:phpcs]
        * `tests:validate:phpcs:files` [validate:phpcs:files]
        * `tests:validate:twig` [validate:twig]
        * `tests:validate:twig:files` [validate:twig:files]
        * `tests:validate:yaml` [validate:yaml]
        * `tests:validate:yaml:files` [validate:yaml:files]
* `internal` (hidden)
    * `internal:composer:install` [setup:composer:install]
    * `internal:composer:require` [composer:require]
    * `internal:git-hook:commit-msg` [git:commit-msg]
    * `internal:git-hook:pre-commit` [git:pre-commit]
    * `internal:add-to-project` [internal:add-to-project]
    * `internal:create-project` [internal:create-project]
    * `internal:create-project:init-repo` [internal:create-project:init-repo]

**Comment by grasmash** [comment]
I mainly like ditching `code` just to shorten things. It'd land us here:

Commands:

* `help` [help]
* `list` [list]
* `drupal` (pattern: `drupal:[action]:*`)
    * `drupal:config-import` [setup:config-import]
    * `drupal:install` [setup:drupal:install] / [deploy:drupal:install] / [internal:drupal:install]
    * `drupal:sql-import` [setup:import]
    * `drupal:sync` [sync]
        * `drupal:sync:db` [sync:db]
        * `drupal:sync:db:all` [sync:db:all]
        * `drupal:sync:files` [sync:files]
    * `drupal:toggle-modules` [setup:toggle-modules]
    * `drupal:update` [setup:update] / [deploy:update]
* `blt` (pattern: `blt:[action]:[direct-object]`)
    * `blt:source:cleanup` [cleanup]
    * `blt:config:dump` [config:dump]
    * `blt:config:get` [config:get]
    * `blt:doctor` [doctor]
    * `blt:init`
        * `blt:init:shell-alias` [install-alias]
        * `blt:init:git-hooks` [setup:git-hooks]
        * `blt:init:hash-salt` [setup:hash-salt]
        * `blt:init:settings` [setup:settings]
    * `blt:update` [update]
* `artifact` [deploy]
    * `artifact:deploy` [deploy]
    * `artifact:build` [deploy:build]
    * `artifact:build:simplesamlphp:config` [simplesamlphp:deploy:config]
* `source:build` [setup:build]
    * `source:build:composer` [setup:composer:install]
    * `source:build:frontend` [frontend]
        * `source:build:frontend:assets` [frontend:build]
        * `source:build:frontend:reqs` [frontend:setup]
    * `source:build:simplesamlphp:config` [simplesamlphp:build:config]
* `source:fix:phpcbf` [fix:phpcbf]
* `recipes` (pattern: `recipe:[category]:*`)
    * `recipes:acsf:init` [acsf:init]
    * `recipes:acsf:init:drush` [acsf:init:drush]
    * `recipes:ci:gitlab:init` [ci:gitlab:init]
    * `recipes:ci:pipelines:init` [ci:pipelines:init]
    * `recipes:ci:probo:init` [ci:probo:init]
    * `recipes:ci:travis:init` [ci:travis:init]
    * `recipes:cloud-hooks:init` [setup:cloud-hooks]
    * `recipes:simplesamlphp:init` [simplesamlphp:init]
    * `recipes:drupalvm:init` [vm:config]
    * `recipes:drupalvm:destroy` [vm:nuke]
    * `recipes:multisite:init` [generate:multisite]
    * `recipes:aliases:acquia` [generate:aliases:acquia]
    * `recipes:config-splits:init` [generate:config-splits]
* `tests` (pattern: `test:[category]:*`)
    * `tests:all`
    * `tests:behat` [tests:behat]
        * `tests:behat:definitions` [tests:behat:definitions]
        * `tests:behat:init` [setup:behat]
        * `tests:behat:init:phantomjs` [tests:configure-phantomjs]
    * `tests:frontend` [frontend:test]
    * `tests:phpunit` [tests:phpunit]
    * `tests:security:updates` [tests:security-updates]
    * `tests:composer:validate`
    * `tests:php:lint` [validate:lint]
    * `tests:phpcs:all` [validate:phpcs]
    * `tests:phpcs:filelist` [validate:phpcs:files]
    * `tests:twig:all` [validate:twig]
    * `tests:twig:filelist` [validate:twig:files]
    * `tests:yaml` [validate:yaml]
    * `tests:yaml:filelist` [validate:yaml:files]
* `internal` (hidden)
    * `internal:composer:install` [setup:composer:install]
    * `internal:composer:require` [composer:require]
    * `internal:git-hook:commit-msg` [git:commit-msg]
    * `internal:git-hook:pre-commit` [git:pre-commit]
    * `internal:add-to-project` [internal:add-to-project]
    * `internal:create-project` [internal:create-project]
    * `internal:create-project:init-repo` [internal:create-project:init-repo]

**Comment by grasmash** [comment]
@damontgomery I think that one of the clear advantages of your proposal was the `build`
and `test` groupings. I've tried to incorporate that organization here as much as possible.

**Comment by grasmash** [comment]
> Not to make it too complex, but I think a lot of your commands have the following pattern and it might make sense to keep it throughout,

Yeah I considered that, but sometime we need a sub grouping for the first noun, so I'm moving toward:

`[group][optional-subgroup][verb][optional-direct-object]`

I've made two tokens optional because they're not always applicable. E.g., we could use `tests:php:lint:code` but it really an improvement over `tests:php:lint`. Defining the direct object becomes required only when it is possible to act upon more than one, as in the case of `drupal:sync:files` and `drupal:sync:db`.

Maybe it allows for too many permutations?

**Comment by TravisCarden** [comment]
I've updated the description with the current proposal and "closed" the survey.

@grasmash and @damontgomery, I'm super happy the two of you are talking about a name pattern beneath the top level categories. That's important for consistency--and to prevent us from getting into this situation again! Let's make sure to document the pattern once finalized, to guide new contributors.

As to the question of alternative names for `recipes`, they need to be nouns. I'm personally happy with `recipes`, but for the sake of it, here are a few other possibilities that come to mind: `blueprints`, `constructors`, `formulas`, `generators`, `installers`, and `setups`.

All in all, I'm pretty satisfied with the current proposal.

**Comment by danepowell** [comment]
I'm pretty happy with the most recent proposal. I can't think of any specific way to improve it. I agree that English is hard, but I think we're doing the best we can with it :smile:

**Comment by grasmash** [comment]
https://github.com/acquia/blt/pull/2484
https://github.com/acquia/blt/pull/2482
https://github.com/acquia/blt/pull/2480
https://github.com/acquia/blt/pull/2476
https://github.com/acquia/blt/pull/2475
https://github.com/acquia/blt/pull/2473
https://github.com/acquia/blt/pull/2472
