### ISSUE TITLE
Composer create-project gives fatal error out of memory 

### ISSUE THREAD

**Issue by judy-akers** [acquia/blt#2664]
Brand new to BLT and first attempt to use it.  I am attempting to follow the instructions on http://blt.readthedocs.io/en/latest/readme/creating-new-project/ to Create a new project with BLT. The first command to create-project gives this response

```
~ }  » composer create-project acquia/blt-project MY-PROJECT --no-interaction
PHP Fatal error:  Out of memory (allocated 78643200) (tried to allocate 2121925 bytes) in phar:///cygdrive/c/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Util/RemoteFilesystem.php on line 403

Fatal error: Out of memory (allocated 78643200) (tried to allocate 2121925 bytes) in phar:///cygdrive/c/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Util/RemoteFilesystem.php on line 403
{ ~ }  »
```

So what and where do I need to change to get this to work?

**Comment by grasmash** [comment]
Two notes.

One snippet from [System requirements](http://blt.readthedocs.io/en/latest/INSTALL/):

> The local PHP environment should also have a memory limit of at least 2G for BLT to initialize. You can modify your PHP CLI's memory limit by editing php.ini. You can use the following command to open the correct php.ini in TextEdit. Set memory_limit = 2G.

Also, it looks like you might be on Windows? Windows isn't fully supported and requires a lot of extra work. Using it is highly discouraged. Not because we hate Windows or don't understand that sometimes it's necessary. We just know that using it with a Drupal dev stack is very painful.

See http://blt.readthedocs.io/en/latest/readme/windows-install/

**Comment by grasmash** [comment]
Did that address your issue?

**Comment by judy-akers** [comment]
Our office is mostly Windows pcs and we don't have the funds to replace with Macs. So my boss is looking into other tools. Thank you

**Comment by bobbygryzynger** [comment]
I'm also running into this while trying to create a new project, increasing my memory limit to `4G` addressed it.
