### ISSUE TITLE
Accessing commit message from overridden deploy:update command

### ISSUE THREAD

**Issue by Loguercio** [acquia/blt#2689]
Hi,

Not an issue, but I was wondering if anyone knew how to access the most recent commit message from within an overridden `deploy:update` command?

I'd like to be able to conditional run various deployment scenarios based on flags in the most recent commit message, but I'm having a hard time accessing it, even though it's displayed on the Acquia Task Log. 

Thanks,

Luca

**Comment by danepowell** [comment]
I'm assuming you are on Acquia Cloud. There might not be a way to get the latest commit message on Cloud, since it's a read-only static filesystem, not a full Git checkout.

Your best bet would be to do this at the level of the cloud hook. You can read about how Cloud Hooks work here, and see what info is available:
https://github.com/acquia/cloud-hooks

For instance, you could modify this file:
`hooks/common/post-code-deploy/post-code-deploy.sh`

... and insert some logic to read a flag and conditionally skip running `deploy_updates`, or maybe pass it an argument or set an environment variable that can be read later by that command.

But again... I'm not sure you can easily get the commit message. You might want to look at some other means of setting a flag, such as a configuration file in the codebase. Or you might need to do something more exotic like directly polling the git repo. Posting an issue in the Cloud Hooks repo might get you more info.

**Comment by grasmash** [comment]
Presuming you're actually in an environment with a git repo available:

In bash:
```
git log --oneline -1 | cut -f2- -d' '
```

In PHP:
```
$log = explode(' ', shell_exec("git log --oneline -1"), 2);
$git_last_commit_message = trim($log[1]);
```

**Comment by Loguercio** [comment]
@danepowell thanks. You are correct, we're on AC. I ended up using travis to read the commit message and create a flag file outside of the doc root, and then having the cloud hook check that file to determine what scenario should be executed

@grasmash turns out I didn't have access to the git repo from the AC env. Thanks though
