### ISSUE TITLE
Error on deploy builds: unterminated quoted string

### ISSUE THREAD

**Issue by danepowell** [acquia/blt#2720]
My system information:
* BLT version: 9.0.5

It looks like the deployment identifier can have quotes in it that aren't escaped properly before writing to disk. I got this error recently on a Pipelines build:

```
[ExecStack] Running echo 'MMv[Nwm'' > deployment_identifier in /tmp/artifact
sh: 1: Syntax error: Unterminated quoted string```

**Comment by malikkotob** [comment]
My first thought was that we could surround the string with double quotes instead of single, e.g. `"MMv[Nwm'"`. That's obviously not going to work because double quotes could be returned, lol. So our options are:
a) Find double, single quotes, and backslashes and escape them (would need to be careful not to escape backslashes being used as escape characters)
b) Prevent double and single quotes from being part of the `deployment_identifier`.
c) Some combination

For option b, one thing to be aware of is that the tag name is used as the deployment identifier if what is being deployed is a tag. Since BLT probably shouldn't limit tag name selection, we would still need to escape double and single quotes, as well as backslashes. So it seems like I just talked myself into option a.

@danepowell, @grasmash, @mikemadison13  what're your thoughts here?My first thought was that we could surround the string with double quotes instead of single, e.g. `"MMv[Nwm'"`. That's obviously not going to work because double quotes could be returned, lol. So our options are:
a) Find double, single quotes, and backslashes and escape them (would need to be careful not to escape backslashes being used as escape characters)
b) Prevent double and single quotes from being part of the `deployment_identifier`.
c) Some combination

For option b, one thing to be aware of is that the tag name is used as the deployment identifier if what is being deployed is a tag. Since BLT probably shouldn't limit tag name selection, we would still need to escape double and single quotes, as well as backslashes. So it seems like I just talked myself into option a.

@danepowell, @grasmash, @mikemadison13  what're your thoughts here?
