### ISSUE TITLE
Behavior of composer.suggested.json

### ISSUE THREAD

**Issue by danepowell** [acquia/blt#2758]
My system information:
* BLT version: 9.0.5

BLT provides suggested dependencies such as Lightning via composer.suggested.json, which is included by a project's main composer.json file via the composer-merge plugin.

In BLT 8.9, composer.suggested.json lived in the BLT package (in the vendor directory), and was thus "owned" by BLT. You could only modify it via an "excludes" file, IIRC--you couldn't modify it in place, because it was obviously owned by BLT. That all made sense.

In BLT 9, composer.suggested.json lives in the project at `blt/composer.suggested.json`, suggesting that it should be "owned" by the project. Further, this suggests that composer.suggested.json can be edited in  place in order to change or remove suggested dependencies.

On the other hand, composer.suggested.json is ignored by Git, and it also gets overwritten with the default BLT version any time composer update is run. This implies that it should _not_ be owned by the project, or edited in place.

Needless to say, this is very confusing. Can anyone clarify the intended behavior here?

**Comment by mikemadison13** [comment]
@danepowell i think these need to be removed from the .gitignore. I think I inadvertently broke a CI process with https://github.com/acquia/blt/pull/2745 related to these files, since they were just sitting there and not actually being included in the root composer.json file. Of course, as of 9.x-dev they are now in the composer.json file, but they aren't present in the repo (so that will cause problems for people).

i think your point about being able to modify them makes sense. regardless, we need to change something to fix the issue introduced the above.

@grasmash  any issues  with me removing these from the gitignore so they can be modified?

**Comment by dpagini** [comment]
I think they were moved into the project, b/c when they were living in `vendor/` it was possible to "hose" your composer, if for example, you removed your BLT vendor folder, but your composer.json file was pointing to a file that didn't exist. I don't know if that exact scenario makes sense, but I've ran into that issue plenty of times where composer won't run b/c it has a problem finding the required/suggested files. I would end up having to `$ rm -rf vendor` my vendor folder to fix the issue.

I'm not sure I agree with wanting to commit these files to the projects. Aren't there documented ways to modify these files, if that edge case issue comes up at all? These _should_ stay managed by the project, but due to the merge-plugin functionality, this was an alternate approach. I guess I would point to Drupal core files, contrib files, and local configuration files... all included in `.gitignore` files, and located in various locations throughout the project that have the same problems... if you edit them, the change will be ignored, and your changes will eventually be overwritten. So why are these two files different from that?

**Comment by grasmash** [comment]
The file logically belongs in vendor, but that causes problems as @dpagini pointed out. So, they’re effectively cached in the blt dir and they are not meant to be modified. This is why they are in .gitignore.

It’s not great. The best fix is to implement https://github.com/acquia/blt/issues/2744 and remove all this complexity.
