### ISSUE TITLE
Allow blt to be executed from the current folder

### ISSUE THREAD

**Issue by vstanchev** [acquia/blt#2759]
My system information:
* Operating system type: Linux
* BLT version: 9.0.5  

I have a case where my git repository has the following structure
```
 - .git
 - src
   -- docroot
   -- vendor
   -- *...*
 - *...*
```

Executing `blt` in the `src/` folder prints an error message "You must run this command from within a BLT-generated project repository."

Examining the `blt()` function in `~/.bashrc` reveals that `blt` is executed with `$GIT_ROOT/vendor/bin/blt`, where `$GIT_ROOT` is the git repo root folder. This is nice, because you can execute `blt` from any subfolder, but in my particular case it is set as `../` which is correct, but `vendor/bin/blt` is not there.

I managed to workaround by checking for `./vendor/bin/blt` like this:

```bash
function blt() {
  if [ "`git rev-parse --show-cdup 2> /dev/null`" != "" ]; then
    GIT_ROOT=$(git rev-parse --show-cdup)
  else
    GIT_ROOT="."
  fi

  if [ -f "$GIT_ROOT/vendor/bin/blt" ]; then
    $GIT_ROOT/vendor/bin/blt "$@"

  #### Check for local BLT
  elif [ -f "./vendor/bin/blt" ]; then
    ./vendor/bin/blt "$@"
  ####

  else
    echo "You must run this command from within a BLT-generated project repository."
    return 1
  fi
}
```

**Comment by grasmash** [comment]
This seems like an edge case, and creating a custom bash alias is the right solution.

Theoretically you could put `vendor` anywhere in your repo. The best that the BLT alias can do is check for the most likely location for `vendor`, which is the repo root. 

Drush does something very similar to find the Drupal docroot. That functionality actually end up being split into a separate package because it was such a common need. See https://github.com/webflo/drupal-finder
