### ISSUE TITLE
Install BLT alias automatically for developers

### ISSUE THREAD

**Issue by danepowell** [acquia/blt#284]
When a developer clones a project repo built on the new composer-based BLT, they have to do something like this:

1. `composer install`
2. `./vendor/bin/blt local:setup`

I think we could consolidate this to automatically run the local setup as part of the composer install. We should at least install the BLT alias so they don't have to poke around the vendor directory for the BLT binary.

**Comment by grasmash** [comment]
In order to do this, we'd need to either:
* Have the project's composer file contain a `post-update-cmd` script, or
* Define blt as a composer plugin in the way that cweagens/composer-patches does

**Comment by pixlkat** [comment]
I've been investigating how to accomplish this today. In its current form, the install-alias.sh script requires appropriate input from a prompt before it will actually install the alias. Scripts run as composer scripts do not support user input as a response to a prompt from a shell script. See https://github.com/composer/composer/pull/4036.

It is relatively straightforward to add a script definition to `template/composer.json` so that the script can be run, however if the alias does not already exist it is not created. If we want to go this route, we will need to modify the script so that it will check for a "-y" flag so it doesn't need to ask when running the command from composer.

I think running `blt local:setup` automatically is not really feasible since between setting up the project directories and installing everything, the local dev environment needs to be set up.  I think the best we can do here is to run `blt setup:drupal:settings`.

**Comment by grasmash** [comment]
Installing automatically causes issues in some environments, but I've made it much simpler: `composer blt-alias`.

I don't think we should run `local:setup` because some people may be adding blt to an existing codebase with an existing db, which would be dropped.

**Comment by kevinquillen** [comment]
One slight thing, the same function that works in fish, causes zsh to exit to iTerm/Term or the window itself will close (if zsh is set as default shell) if blt is ran in a directory fails the conditions in the function.
