### ISSUE TITLE
SimpleSAML PHP Config / mc_session_store

### ISSUE THREAD

**Issue by mikemadison13** [acquia/blt#2947]
My system information:
* BLT version: 9.1

Issue:
https://github.com/acquia/blt/pull/2547 introduced the $ah_options array into the mc_session_store function, but didn't pass it in from where it is used in the file. This should be remedied.

**Comment by brooke-heaton** [comment]
I'm confused. I'm just now implementing SimpleSAML with blt and read this in the docs:

```
$ah_options = array(
    // Use the database "role" without the "stage", e.g., "example", not
    // "exampletest" or "exampleprod".
    'database_name' => 'example',
    'session_store' => array(
      // Valid values are "memcache" and "database".
      'prod' => 'database',
      'test' => 'database',
      'dev'  => 'database',
    ),
  );
```

But that code is nowhere to be found in `acquia_config.php`

Do I need to add this manually?

**Comment by lcatlett** [comment]
@brooke-heaton - #2953 enhanced the acquia_config.php template to add support for multisite through dynamically generating the config previously in the `$ah_options` array. I'm closing this issue since it is specifically asking about missing `mc_session_store` config and memcache is no longer the recommended session storage for PHP7.
