### ISSUE TITLE
Deploy error on ACSF due to drush cache clear

### ISSUE THREAD

**Issue by mikemadison13** [acquia/blt#2951]
My system information:
* BLT version: 9.1

Original issue: https://github.com/acquia/blt/issues/2867

This is still happening to me during deploys to ACSF using BLT 9.1-alpha1. As far as I can tell, it's not blocking deployments, but it is causing errors during deployments.

```
The message from the server was: <project>.: Running BLT deploy tasks on testsite.newellsf.acsitefactory.com domain in 01live environemnt on the <project> subscription.
> drupal:config:import
 [37;46;1m[success][39;49;22m 'drush' cache was cleared.
 [37;46;1m[success][39;49;22m Cache rebuild complete.
 [37;41;1m[error][39;49;22m [37;41;1m Failed to remove directory "/home/<project>/.drush/cache/factory": rmdir(/home/<project>/.drush/cache/factory): Directory not empty. [39;49;22m
8.519s total time elapsed.
```

**Comment by mikemadison13** [comment]
this seems already fixed in the above issue, just update to 9.x-dev and patch drush as defined here: https://github.com/drush-ops/drush/pull/3597

**Comment by rjgwiz** [comment]
Sharing a similar experience: I ran into the same error in ACE cloud hooks on _one_ deploy, using BLT `9.0.5` and drush `9.2.3` during a `drush cr`:

` [error]  Failed to remove directory "/home/<ACQUIA_USER>/.drush/cache/factory": rmdir(/home/<ACQUIA_USER>/.drush/cache/factory): Directory not empty.`

I am not sure if the collision came from multisite, or drush commands running simultaneously in another non-prod environment.

https://github.com/drush-ops/drush/issues/3592 is still open, and as of right now it seems the best solution to pull in https://github.com/drush-ops/drush/pull/3597 as a patch (until it makes it into an official release) and add `cache-directory: /dev/null` to `/drush/drush.yml` under `drush.paths`

@danepowell you addressed this for ACSF (`db-update.sh`) in #2922, `export DRUSH_PATHS_CACHE_DIRECTORY=/tmp/.drush/${db_role}` looks like it prevents multisite collisions. Since environments can share servers too, would it help to add env? i.e. `export DRUSH_PATHS_CACHE_DIRECTORY=/tmp/.drush/${env}/${db_role}`

Depending on the direction of https://github.com/drush-ops/drush/issues/3592, ACE cloud hooks would benefit from `DRUSH_PATHS_CACHE_DIRECTORY` if ACSF continues down that path. I am curious how much of a performance boost using drush cache provides (vs. a null cache-dir)

**Comment by danepowell** [comment]
Good points, thanks. I created a follow-up issue: https://github.com/acquia/blt/issues/2957
