### ISSUE TITLE
artifact:ac-hooks:post-db-copy (postDbCopy) runs updates for all sites

### ISSUE THREAD

**Issue by rjgwiz** [acquia/blt#2952]
Following up on #2781, the post-db-copy hook is very useful but currently it is running updates for all sites. That doesn't seem desirable if only one site database is copied over, and it appears [cloud api](https://cloudapi.acquia.com/) only supports copying 1 db at a time. Ideally it updates only the site corresponding to the databases that was copied.

`@command artifact:ac-hooks:post-db-copy` currently calls `updateSites()`, which leads to an ACE or ACSF update function, both of which invoke `artifact:update:drupal:all-sites`. 

Currently `artifact:ac-hooks:post-code-update` calls the same `updateSites()` function. I'm not sure the best approach for supporting updating all sites or one site while minimizing code duplication. Also, any suggestions for the best way to use the `$db_name` param in `postDbCopy()` to find/match which site the db belongs to?

**Comment by ba66e77** [comment]
According to the [Cloud Hooks documentation](https://github.com/acquia/cloud-hooks#post-db-copy), post-db-copy gets passed in the site, target env, db name (which is the common name of the db), and the source environment. Rather than trying to reverse engineer the name from the db, you might be able to pass the site value straight into [updateSite()](https://github.com/acquia/blt/blob/9.x/src/Robo/Commands/Deploy/DeployCommand.php#L584)

**Comment by rjgwiz** [comment]
Thanks @ba66e77. The issue there is the `site` var in `post-db-copy` is the the Acquia Cloud username for the site, not the multisite ID. When [updateSite()](https://github.com/acquia/blt/blob/9.x/src/Robo/Commands/Deploy/DeployCommand.php#L584) gets called, BLT is looping through blt's `multisite` array. I haven't really dug in yet but I need to look for a simple & reliable way to match `db_name` from `post-db-copy`, which is being added to `AcHooksCommand` in #2782, to a multisite, and use that multisite id to call `updateSite()`

Closing this issue since #2782 isn't merged yet, I'll move discussion over to there.
