### ISSUE TITLE
Extend Drush cache-clear collision protection

### ISSUE THREAD

**Issue by danepowell** [acquia/blt#2957]
In #2922, we added cache-clear collision protection for ACSF sites, which solved this problem in the vast majority of cases.

However, there are still some edge cases where this problem can occur. For instance, if a deploy takes place in two _environments_ at the same time (as opposed to two sites on the same environment), or if this happens on ACE (which we haven't added protection for).

I propose the following changes:
1. Include the environment in the cache directory environment variable: `export DRUSH_PATHS_CACHE_DIRECTORY=/tmp/.drush/${env}/${db_role}`
2. Add this environment variable to Cloud Hooks as well, so ACE users can benefit

This is a follow up from https://github.com/acquia/blt/issues/2951#issuecomment-405700510

**Comment by lcatlett** [comment]
Setting `DRUSH_PATHS_CACHE_DIRECTORY` globally on an environment rather than just the current shell will impact any drush process that use the drush cache and may impact the ability to run concurrent tasks on ACE and ACSF since it can result in simultaneous writes to the same cache directory. I recommend the following approach to fully address the issue: 

 - Create unique drush temporary directory per environment / user / site process
 - prefix individual drush commands with `DRUSH_PATHS_CACHE_DIRECTORY` rather than setting a global value
 - delete drush temporary directory 
 - log / print resulting command output to to Acquia Cloud logs

**Comment by lcatlett** [comment]
@danepowell the [post-db-copy script](https://cgit.drupalcode.org/acsf/tree/acsf_init/lib/cloud_hooks/common/post-db-copy/000-acquia_required_scrub.php?h=8.x-2.x&id=50d0092)in the ACSF module is an example how similar issues have been resolved for internal Factory staging tasks. That hook would been to be refactored a bit for BLT deploy / update hooks so I can put in a PR when I get a moment if that would be helpful

**Comment by danepowell** [comment]
Are you proposing prepending the cache directory to every single Drush call? While that might work, it seems like a much larger (and unnecessary) lift than simply exporting the cache directory once as an environment variable in the factory hook. I'm not sure I see the advantage to the extra work (and departure from how BLT has already solved this in #2922).

**Comment by lcatlett** [comment]
I believe the part that is more important is creating and deleting the unique drush cache directory in each cloud hook call rather than whether or not it is prepended for every drush call vs. a subset of calls on deploy/update.  Simply exporting the cache directory once as an environment variable in the factory hook could result in drush using stale cached data and that another drush process is not executed during the deploy.

Prepending the resulting cache directory for each of the drush commands on deploy/update will guarantee that the commands are logically isolated and can support concurrency for multisite on both ACSF and ACE but may be overkill.

**Comment by lcatlett** [comment]
I just ran into this with a site install so the `post-install` hooks also need this environment variable set.

**Comment by bkosborne** [comment]
@lcatlett I believe we're experiencing this issue with a D8 multisite ACE:

```
[33mIn Filesystem.php line 180:[39m
[37;41m                                                                               [39;49m
[37;41m  [Symfony\Component\Filesystem\Exception\IOException]                         [39;49m
[37;41m  Failed to remove directory "/home/princetonsites/.drush/cache/factory": rmd  [39;49m
[37;41m  ir(/home/princetonsites/.drush/cache/factory): Directory not empty.          [39;49m
[37;41m                                                                               [39;49m
```

We're running BLT 9.2.3 with Drush 9.5.2. This happened in production  recently, but up until then had only been happening in our dev/qa environment. This deployment happened to coincide with a cron run, so I suspect that it may be that cron was being run (via drush) for this site at the exact time BLT was running drush commands for the site.

It looks like this has been fixed for ACSF, but not for ACE multisite (and that's what this issue is meant to track).

Any suggestions on how to mitigate this for now? Or anything I can do to help test?

**Comment by rjgwiz** [comment]
@bkosborne are you running a `drush cr` on every cron run?

@lcatlett what are your thoughts on this approach for a global solution that should work on ACE and anywhere?:

https://github.com/drush-ops/drush/blob/master/examples/Commands/SiteAliasAlterCommands.php is an example drush command using drush's `@hook pre-init *`. The example says it's for altering a site alias, but they are also altering drush config here: `$this->getConfig()->set('ssh.options', '-o ForwardAgent=yes');`

We should be able to programmatically/dynamically set drush config's `cache-directory` value based on current site and environment. Environment because it's common for non-prod environments to run on the same server. `AH_SITE_GROUP` could also be used since in a few cases one server hosts multiple docroots.

The command could look something like:
```
public function alter(InputInterface $input, AnnotationData $annotationData) {
  if (($ah_env = getenv('AH_SITE_ENVIRONMENT')) && ($ah_site = getenv('AH_SITE_GROUP'))) {
    $site = drush_get_context('DRUSH_DRUPAL_SITE', 'default');
    $this->config()->set('drush.paths.cache-directory', "/tmp/.drush/{$site}/{$ah_site}.{$ah_env}");
  }
}
```

...there may be a better way to get site name.

Adding a custom drush command is a little more upfront overhead/setup, but it should work across ACE, ACSF, and other platforms, and saves having to prefix drush or BLT command calls  in any scripts with setting the value for `DRUSH_PATHS_CACHE_DIRECTORY`. The drush command could be (optionally) copied to `drush/Commands/` during BLT setup, or hosted in a separate repo and added as a composer dependency for those who want to use it

**Comment by bkosborne** [comment]
@rjgwiz I'm not explicitly clearing caches on each cron run, no. Though some of my cron tasks could be selectively clearing Drupal caches. I'm just trying to figure out what causes this problem to *sometimes* surface for us. My understanding is that it happens when two drush processes are executed at the same time and both try to access or delete the drush cache dir.

**Comment by rjgwiz** [comment]
@bkosborne if the cron jobs aren't calling `drush cr`/`drush cc drush` (they shouldn't, there's not much good reason to script that), it's probably that cloud hooks are running a `drush cr` while a cron job is executing a drush command that is utilizing drush cache.

The alter command works, but there is an issue with `cache-directory`. No matter how it's set... alter command, drush config file such as `drush.yml`, manual cli argument... it breaks drush `sql-sync`. I figured out why and hope to open a PR on https://github.com/drush-ops/drush/ soon (`drush_get_global_options` needs `cache-directory` added to the options list). Though I am in-between home computers right now. `sql-sync` isn't typically run on remote servers, but still don't want to break any commands.

Any chance to use a drush command hook to perform an alter command to set cache dir will depend on a drush update or patch for the above. Also, `drush/Commands/` is gitignored by default. I think a standalone command is ideal. 

Where would custom standalone (non-module) drush commands live within a BLT project? A new `include` folder could be added to `drush.yml` for loading commands, but a different folder might interfere with namespacing the command files

**Comment by dpagini** [comment]
cc: @danepowell & @lcatlett 

I have an interesting find on this today I wanted to share. I read @danepowell's [comments](https://github.com/drush-ops/drush/issues/3592#issuecomment-401468284) over on drush-ops/drush#3592 about drush re-adding it's cache as part of its own bootstrap process, which seemed to make sense in the narrative I was observing. Then I started running the following command `$ rm -rf ~/.drush/cache/factory` which was failing for me quite a bit (see output below). 

```sh
update
```

Then I realized if I ran `$ rm -rf ~/.drush/cache/factory;ls ~/.drush/cache` I was seeing the factory folder be deleted some of the time, and the other instances it was _still there_ even though the command removed it.

This has only become an insurmountable problem for me the last few days, after seeing this issue pop up here and there previously. Re-running a command would not fail previously and we'd be good to go. Now I can't get anything to run correctly on my site due to `drush cc drush` failing in my cloud hooks.

I feel like maybe my Acquia account has maybe some kind of runaway drush process...? I will open a ticket with support to see if they can find anything... but in the meantime I thought it was interesting that just manually deleting the folder, I would see it re-added within a second, telling me something is calling drush somewhere else.

**Comment by lcatlett** [comment]
@dpagini - was this a production environment with multiple load balanced web servers by chance? If so this odd behavior is likely due to the home directory being stored in gluster on Acquia Cloud, so deleting a directory on one web does not actually 'remove' the directory atomically from the other webs and is instead dependent on gluster syncing the changes. 

One other possibility is that drush is running cron or other tasks in the background as intended, but again that depends on your environment setup on Acquia. If you send me the support ticket number or ping me in the Acquia insight ticket, I can take a look to see anything else comes to mind.

**Comment by dpagini** [comment]
I opened ticket 794513. This is actually non-prod I'm seeing the problem. Doing some more investigation, running `$ ps -ef | grep drush` to list running processes with drush in the name returns ~20 lines/processes. I'm sort of leaning to _that_ being my culprit right now. I feel like if I close all those processes, when I run `$ rm -rf ~/.drush/cache/factory` it wont be regenerated instantly.

**Comment by bkosborne** [comment]
For what it's worth, after paying closer attention to this throughout the weeks, I'm now positive that this only happens to us when cron is running (via drush). In the meantime, I have to time my deployments so that they don't occur while cron is running =/

**Comment by dpagini** [comment]
Yes, drush cron runs lines up with the behavior I've observed as well. Since drush is actively running the cron command, when the file gets deleted, the running cron command will recreate the cache _while_ the delete is running, and cause the error.

**Comment by danepowell** [comment]
BLT has already implemented some workaround for this that prevent the issue in most, but not all, cases. Ultimately, however, this is not a problem for BLT to solve. Anyone using Drush, especially in a multi-tenant environment or on a high-latency filesystem, is vulnerable to it. It needs to ultimately solved in Drush and/or Acquia Cloud.

**Comment by aweingarten** [comment]
Still observing this with 10.x branch on ACE.  It may make sense to port the code from the ACSF hooks over to the ACE hooks

**Comment by danepowell** [comment]
@aweingarten I don't see how this can be solved via Cloud Hooks on ACE. Whereas ACSF updates run on a per-site basis, and thus we can easily isolate cache directories per-site, the post-code-update and post-code-deploy hooks only run on a platform-wide basis. They don't get a `$uri` or `$db` or any equivalent parameter.

**Comment by josephdpurcell** [comment]
I can confirm we're experiencing this issue with Drupal 8, BLT 9.2.8, Drush 9.5.2. The failure happens on drush cache rebuild.

This is a key issue since the deployment script being used runs cache rebuild, fails, and therefore fails the deployment.

Does anyone have a workaround? Perhaps doing something like this would be ok:

```
drush cr || drush cr || false
```

The assumption being it attempts cache rebuild twice, if it fails both times, then fail the build. If it passes the first time it will only do cache clear once. Thoughts?

**Comment by josephdpurcell** [comment]
Acquia support has recommended adding this as a composer patch to your composer.json:

```
"drush/drush": {
      "Fixes #3592: Prevent race conditions in cache clears": "https://patch-diff.githubusercontent.com/raw/drush-ops/drush/pull/3594.patch"
}
```

This patch is from https://github.com/drush-ops/drush/pull/3594. See also https://github.com/drush-ops/drush/issues/3592.

**Comment by josephdpurcell** [comment]
The patch did not prevent the issue. The issue, specifically, is:

```
In Filesystem.php line 180:
    Failed to remove directory "/home/sitefactoryname/.drush/cache/factory": rmdir(/hom
e/sitefactoryname/.drush/cache/factory): Directory not empty.
```

Looking at the patch https://github.com/drush-ops/drush/pull/3594 I see it is closed in favor of https://github.com/drush-ops/drush/pull/3597 which uses `DRUSH_PATHS_CACHE_DIRECTORY` to allow each drush process to use its own cache directory. The workaround then would look like:

```
DRUSH_PATHS_CACHE_DIRECTORY='/tmp/a-randomly-named-dir drush cr
```

You can see that the factory-hooks generated by BLT use this approach:
* https://github.com/acquia/blt/blob/10.x/scripts/factory-hooks/db-update/db-update.sh#L51
* https://github.com/acquia/blt/blob/10.x/scripts/factory-hooks/post-install/post-install.php#L72

**Comment by josephdpurcell** [comment]
Using `DRUSH_PATHS_CACHE_DIRECTORY` for the scripts this issue no longer occurs.
