### ISSUE TITLE
shared settings files for multisite

### ISSUE THREAD

**Issue by shelane** [acquia/blt#2989]
According to the `/vendor/acquia/blt/settings/blt.settings.php`, any settings.php files in `/docroot/sites/settings` will be included. I created a base.settings.php and a shared.settings.php file in that location. When the command `blt blt:init:settings` is run, it does indeed included them, but it treats the `/docroot/sites/settings` as if it's a multisite and adds all the other settings files in that directory so it looks like:
```
+-_settings
|  +-- _settings
|   | +-- default.local.settings.php
|   | +-- local.settings.php
| +-- base.settings.php
| +-- default.local.drush.yml
| +-- default.settings.php
| +-- local.drush.yml
| +-- settings.php
| +-- shared.settings.php
```

How do I have a "shared settings" directory without getting it turned into a "site" directory?

**Comment by dpagini** [comment]
Hey @shelane. I think there's probably room for a code fix to ensure that a folder named `settings` is ignored in multisite, but for the time being, you can explicitly specify your multisite-sites in the `blt/blt.yml` file like below...
```yml
multisites:
  - default
  - site1
  - site2
  # - settings
```

Obviously you don't have to include `settings` here, and `site1` and `site2` are the names of your multisite directories.

**Comment by ba66e77** [comment]
I'm going to have to play with this to replicate and make sure I grok what is happening, but sure sounds like a bug.

**Comment by ba66e77** [comment]
I confirmed the reported behavior and put in a PR that fixes it. The problem is that when a `multisites` array is not defined in config BLT presumes all directories in docroot/sites (with the exception of the special `g` directory used by ACSF) are multisites. So the quick fix is to add `settings` to the list of directories it ignores.

I'm torn though as to if this is really the best approach. Maybe instead what we should do is explicitly populate the multisites config array with `default` when you create a BLT project and add to the array with each invocation of `blt recipes:multisite:init.` I like that there'd be less 'magic' happening in that approach and everything would be explicit rather than implicit, but I don't know what secondary effects that might have.

**Comment by ba66e77** [comment]
I've created #2995 as an enhancement to propose discussing/reworking the handling of multisites. That's a bigger chunk of work that I want to commit to in order to solve this immediate problem.
