### ISSUE TITLE
Manage local multisites through local.sites.php

### ISSUE THREAD

**Issue by lcatlett** [acquia/blt#3024]
When creating local multisites with the `blt multisite` command, sites.php is updated automatically to include the new site. The current approach generates a new sites.php and should be enhanced to instead use a local.sites.php or local.sites.inc which will improve the developer experience when working with ACSF and other modules that require modifications to sites.php.

**Comment by ba66e77** [comment]
The potential problem I see with this approach is that if you're not using ACSF and create a multisite locally (updating just local.sites.php) then push the code up to your cloud host, the cloud host won't see the multisite setting.  

Maybe instead we could set a config flag when `acsf:init` is run so that we can handle multisites differently for ACSF vs normal multisite codebases. 

Besides ACSF, what else are you aware of that would modify sites.php?

**Comment by lcatlett** [comment]
Sites.php should still be modified as needed for non-acsf projects. BLT doesn't configure any of the upstream sites.php config. On ACSF this is done in the sites.inc which is included in sites.php after running acsf-init.

**Comment by lcatlett** [comment]
Re: "Besides ACSF, what else are you aware of that would modify sites.php", all ACE projects also need to modify sites.php manually for each upstream environment.

**Comment by danepowell** [comment]
Let's consolidate discussion around the management of sites.php in #3477
