### ISSUE TITLE
Support the "install site from existing config" feature of 8.6

### ISSUE THREAD

**Issue by mikecrittenden** [acquia/blt#3086]
I don't see an issue for this but I could be missing it. There are a few other "install from existing config" issues but none of them are referring to the feature being built into 8.6 as far as I can tell.

See https://www.drupal.org/project/drupal/issues/1613424 and https://www.drupal.org/project/drupal/issues/2980670 - Drupal 8.6 now has built-in support for installing from configuration directly rather than doing what BLT is currently doing which is to install the site and then import from configuration directly afterwards. 

Does BLT have plans to support this? I'd love to be able to just run `blt setup` and have it just work, as opposed to splitting out the `drush site-install --existing-config` myself.

**Comment by ba66e77** [comment]
It's not something we've discussed yet but I could get behind this idea.

**Comment by mikecrittenden** [comment]
For anyone seeing this, I replaced `blt setup` with this in the meantime:

```
fin blt source:build --no-interaction
fin drush site-install MYPROFILENAME --account-pass="password" --existing-config --yes
```

That seems to work fine for now.

**Comment by danepowell** [comment]
Note that you don't have to use the `--existing-config` argument if you simply place your config in `docroot/profiles/custom/foo/config/sync` (or symlink it from there). Drupal will automatically install it.

AFAICT, you only have to use the `--existing-config` argument if your config only lives at /config/default.

It's probably still desirable to support that.

**Comment by mikecrittenden** [comment]
@danepowell Interesting - so does that mean that `blt setup` will install from existing config if you have a recent version of Drush and you have your config symlinked to `config/sync`? Because I believe it uses Drush behind the scenes, yeah?

**Comment by danepowell** [comment]
Correct, if you are using Drupal core 8.6 (or 8.5 + a certain core patch), have your config symlinked from a custom profile's `config/sync` directory, and you run `blt setup`, the site should get installed directly from existing config, which is considerably faster than doing a standard install and then running a config import.

**Comment by bobbygryzynger** [comment]
@danepowell It seems here that, in order to support the `--existing-config` flag, BLT's install strategy should no longer attempt to import configuration after the site installation. Would this somehow break some existing features to no longer do a post-installation import?

**Comment by danepowell** [comment]
What's wrong with running a config import after installation? If you are installing the site directly from config, then the subsequent config import should just exit cleanly. Worst case, it adds a second or two to the overall install process.

I don't think it would hurt anything to remove it if we know that the site was installed from existing config, but it seems like unnecessary complexity. Also, there is one advantage for folks who want to have strictly clean configuration--running the config import also triggers BLT's test for overridden configuration, which can be an early indicator of corrupt configuration sets.

**Comment by bobbygryzynger** [comment]
I see. I think the ultimate problem I was having was in the need not to use the `standard` profile because of its `hook_install` implementation. 

In trying to switch to the `minimal` profile in `core.extension.yml` I updated the `profile` key to `minimal` but I also needed to make the following update `standard: 1000` to `minimal: 1000`. This resolved the failing post-install config import.

**Comment by bobbygryzynger** [comment]
@danepowell  I agree with this though:
> I don't think it would hurt anything to remove it if we know that the site was installed from existing config, **but it seems like unnecessary complexity.**

Does BLT's configuration integrity check not work if the site is installed from existing configuration? Because if that doesn't break it or override it somehow, it could still be run post-installation.

**Comment by brooke-heaton** [comment]
I second this very sane observation: 

`installing, then importing seems unnecessarily complex when the --existing-config flag would alone accomplish the task.`

Repeating config importations is an abundant waste of time and unnecessary.

**Comment by brooke-heaton** [comment]
@danepowell  

`if you simply place your config in docroot/profiles/custom/foo/config/sync (or symlink it from there). Drupal will automatically install it.`

Isn't this missing a step though? Wouldn't one then need to change the profile in core.extension.yml and/or settings.php? Maybe I'm not understanding how Drupal would 'automatically install it'. I have a multisite for instance and one site was installed from the `minimal` profile a couple years ago and the other was installed from the `standard` install profile. I don't really see how that solution would work.

**Comment by brooke-heaton** [comment]
> What's wrong with running a config import after installation? 

Well... ok, so let's say you have a CD/CI process that runs. The entire process of installing then importing config just takes longer than it should. It can be done better and smarter.

**Comment by danepowell** [comment]
The symlink approach may not work well with multiple profiles. 

To be clear, I'm not saying this is a preferred approach, it's obviously just a short term workaround, and using the new Drush flag is much preferred. I'm just trying to help folks who need a short term workaround.

**Comment by lpeabody** [comment]
If you are using Configuration Split and have a local split setup, I'm pretty sure that's not taken into account during an install from config. If you import afterwards you'll see that the local config split was not applied during install, so it is necessary to run an import (if you're using the config split configuration management strategy).

**Comment by brooke-heaton** [comment]
hm, yea, that's a curveball. may require a workaround. I'm still eager to see install from config in BLT nonetheless.

**Comment by lpeabody** [comment]
This is just my 2¢ here but I don't think this is something BLT really needs to be concerned with, and if using a config split strategy then importing config after install is absolutely necessary.

My points are as follows:

1) BLT's existing install strategy works perfectly fine with install from config because using that install system lies within the responsibility of the profile, not BLT. Assuming you have profile_test setup to install from existing config, all you need to do is tell BLT which profile to install and Drupal's install from config process will take care of the rest. There is nothing more for BLT to do.

2) If using a config-split strategy, then BLT MUST import configuration after an install, in order to effectively import configuration that is local-specific. So, what BLT is currently doing should be satisfactory.

I think BLT being asked to support this is frankly unnecessary, and time is better spent improving BLT in other ways rather than worrying about 1 extra config import cycle running in non-config-split instances. Just an opinion from a heavy BLT user.

**Comment by brooke-heaton** [comment]
@lpeabody just to flesh out the issue more - it sounds like config_split would make this request a moot point, however I should note that config_split does offer `config-split:import` in which case it would NOT be necessary to completely re-import all config (unless I am mistaken). But that does mean this request becomes more cumbersome and painful for config_split sites.

**Comment by lpeabody** [comment]
>Solid points @lpeabody I'm a bit unclear on how to implement this for a multisite - is your profile set both in settings.php and on core.extension.yml? I've tried implementing the install from profile approach but have honestly found very little clear documentation despite the lengthy issue queue on the drupal.org core project.

We essentially have one configuration folder per site profile. Our setup looks something like:

```
/config/site_profile_1/default
/config/site_profile_1/prod
/config/site_profile_1/test
/config/site_profile_1/dev
/config/site_profile_1/local
/config/site_profile_2/default
/config/site_profile_2/prod
/config/site_profile_2/test
/config/site_profile_2/dev
/config/site_profile_2/local
```

And each profile's config/sync directory symlinks to the appropriate config directory above (i.e. /config/site_profile_1/default, /config/site_profile_2/default, etc.). The various local/prod/test/dev directories store split configuration.

I think there is a core issue which removed $settings['install_profile'] from settings.php, though I don't think there's an issue with you setting it there. I don't think it's required but I would need to test this for myself to deliver a reliable answer.

The only requirement I know of in settings.php is you need to set `$config_directories['sync'] = DRUPAL_ROOT . '/../config/site_profile_1/default';`. For now you MUST use the `'sync'` key otherwise Config Filter plugins will not apply to the configuration, [see here for an explanation](https://www.drupal.org/project/config_ignore/issues/2916654#comment-12635861).

Thinking about this more, I believe BLT does make an attempt to assign the appropriate sync directory automatically via blt.settings.php -> config.settings.php. You can set `$blt_override_config_directories` to FALSE before including blt.settings.php, and it will not override your `$config_directories['sync']` value. In fact, you have to do this in order to have a config-directory-per-profile strategy. @danepowell I think there is an opportunity for a documentation improvement here as it pertains to install-from-config workflows.

>@lpeabody just to flesh out the issue more - it sounds like config_split would make this request a moot point, however I should note that config_split does offer config-split:import in which case it would NOT be necessary to completely re-import all config (unless I am mistaken). But that does mean this request becomes more cumbersome and painful for config_split sites.

I have found the use for config-split:import to be mostly useless. Configuration Split integrates seamlessly into config:import, so you should always be running that anyway. I can't really think of a use case where I would ever want to run config-split:import in favor of config:import.

Anyway, that was a lot, hope it was helpful.

**Comment by brooke-heaton** [comment]
@lpeabody thanks for outlining your approach. I will see if I can get this working on my end. I hadn't realized the nuance with BLT and `blt.settings.php -> config.settings.php`

> I have found the use for config-split:import to be mostly useless. Configuration Split integrates seamlessly into config:import, so you should always be running that anyway. I can't really think of a use case where I would ever want to run config-split:import in favor of config:import.

Hm, yea I haven't used this myself, but my assumption was that if you install from config and that does not account for config_split that that would be the use case for running config-split:import since that should only account for split config. Maybe I don't understand the distinction. The difference I was assuming would be one that would provide faster BLT installs since it would not need to run a full config:import twice. I find that process is lengthy.

**Comment by lpeabody** [comment]
I think the key to understanding any configuration split setup is to study the heck out of how the Config Filter module works. A "configuration split" is an instance of a config filter plugin. You can have many splits and a lot of different logic that enables/disables however many splits you have setup for your project.

For example, you may have a series of language splits and an environment-specific split setup that enables local development modules like stage_file_proxy, dblog, and devel; when you do an import all of those splits should be taken into account. Running a `config-split:import` for each of them is completely unnecessary when you could just run `config:import`. You may also forget to run a singular split import and now you have an incomplete representation of your configuration as it should be in the database.

You can think of it this way: `config-split:import` applies a _singular_ config filter plugin. `config:import` applies _*ALL*_ config filter plugins. You should ALWAYS run `config:import` because that is a COMPLETE representation of what your import looks like. If you run just a singular split import, you potentially have an INCOMPLETE representation of your configuration set. If the importance of what I'm saying here isn't clear, please tell me so I can clear up any confusion. Not having a complete import of your configuration can lead to some very confusing circumstances.

**Comment by danepowell** [comment]
See #3241 for a pretty simple implementation of this. I think we should defer the discussion of whether to keep running post-install imports or not till a later date when the whole feature set has stabilized more.

**Comment by loopy3025** [comment]
I am extremely confused by the resolution to this problem. When I run 
```
fin drush site-install webny --existing-config --yes -vvv
```
My site does install without a problem. However, when I try using BLT to install my site, it complains that the configurations are not identical and that I should try exporting the config before installing. It then errors out on the first UnmetDependenciesException it finds.

I am trying to deploy this site on Acquia using pipelines. There's really no way I can pick and choose how to install this... it has to use BLT. Is there a way I can tell BLT to use the existing configuration when running through it's tests?
