### ISSUE TITLE
Test and validate configuration without having a site installed

### ISSUE THREAD

**Issue by mikecrittenden** [acquia/blt#3101]
I'm not sure how possible this is, but it would be really great if there was a `blt tests:config` that would look at your exported config and validate it for things like depending on modules which are set to disabled. 

That way, CI environments could fail builds if config doesn't validate (for example, on an open PR), without needing to actually try to install it on a real site (which usually happens after you merge the PR and deploy).

**Comment by mikecrittenden** [comment]
I do see https://www.millwoodonline.co.uk/index.php/blog/validating-drupal-8-config but I'm not sure if most/all of that needs a pre-installed site.

**Comment by mikecrittenden** [comment]
https://hechoendrupal.gitbooks.io/drupal-console/content/en/commands/config-validate.html is also related.

**Comment by ba66e77** [comment]
Yeah, I can see that being a nice enhancement.

As part of the CI process you're using, is it not trying to build and install the site to an environment within the CI tool?

**Comment by mikecrittenden** [comment]
In this specific case, I am just building the code base and running linting and validation against it. This job runs for any push to any branch so I'm trying to keep it lean and quick, and adding a site install would make it take three or four times longer than it currently takes.

**Comment by ba66e77** [comment]
Yeah, fair point. 

I generally have a full CI build done when a PR is opened. It does take awhile but catches conflicts like you're talking about here.

**Comment by mikecrittenden** [comment]
Yeah, I'm using bitbucket pipelines which doesn't have a good method for only running CI on PRs rather than any branches. And even then, if you open a PR and then push to it 10 times, it would still run each time. Bitbucket Pipelines charges per minute so faster is definitely better for me at the moment.

**Comment by danepowell** [comment]
I agree this would be nice to have, but I don't see any reasonable way to do it. The configuration management subsystem of Drupal is so complex and has so many plug-in components (such as Config Split), you'd have to use it directly for testing, at which point you might as well just install the site.

You might consider doing a minimal site install to save time, or maybe store a static db dump of a basic install that you can import rather than doing a full install each time. Then you can import config against that site.
