### ISSUE TITLE
Default setup.strategy in CI to sync

### ISSUE THREAD

**Issue by fiasco** [acquia/blt#3109]
The `install` setup.strategy is based on the premise that your site is essentially a shippable distribution and that all testing should be conducted in a controlled environment agnostic of production content.

However, this is rarely the application BLT finds itself in. In other words, its not a sane default (IMO).

For single-site apps:

- syncing the db is usually the de facto direction a dev team will take for establishing a working dev environment
-  I've seen many cases where the dev team isn't too familiar with BLT and don't even realise that syncing is one of its capabilities. 
- Because BLT will instead "install" your site, they tend to not use it and opt for their own manual approaches.
- CI testing is about validating the build's readiness for production. But behat testing an install process is probably just running the lightning tests which may not correlate to validation. 
- If site specific behat tests were written, they'd want a database to test from, not a fresh install.
- When config-in-code reaches the CI, it can break the install process forcing the team to halt delivery to fix the CI. If the install process is not actually delivering any value for the project, then fixing it for the sake of having CI work again is stupid. But happens rather often.

When BLT breaks the delivery pipeline like this, it creates a bad perception of BLT because its seized velocity for no valuable reason.

Syncing is a much more valuable default.
- It makes BLT a more enticing tool to bootstrap your local dev with
- It makes the CI pipeline emulate a deployment rather than setup for tests that don't exist

Its more valuable to fail on a deployment simulation in CI than to fail a Drupal installation process which can't be attributed to project value.

**Comment by lpeabody** [comment]
I'm not a maintainer of BLT, but I'm an ardent user of it and I just want to chime in with my 2 cents here.

It doesn't make sense to ship BLT with a default to sync quite simply because there is no database. Telling your CI environment to use a sync strategy is as simple as creating a ci.blt.yml file placed in your blt directory and adding:

```
setup:
  strategy: sync

drush:
  aliases:
    remote: sitegroup.site
```

Have you reviewed the documentation [around overriding BLT](https://blt.readthedocs.io/en/latest/extending-blt/#modifying-blt-configuration)? You can then run `blt --env=ci` and it will use overridden configuration provided by any ci.blt.yml file.

I've found similar frustrations with teams adopting BLT, and I've found that the single biggest key to understanding and groking BLT is a firm grasp on how it's configuration override system works. Educate your team around that and you'll be fine.

**Comment by fiasco** [comment]
> It doesn't make sense to ship BLT with a default to sync quite simply because there is no database. 

Hi @lpeabody - I don't quite understand what you mean by this? BLT will install Drupal so there must be a database present? Or are you saying that in the beginning, there is nothing in the Stage environment to restore from? So a sync strategy would fail?

I've not found BLT documentation that easy to follow. Evidently, thats been the case with the dev teams I've supported too. Most do not configure BLT which is why the install strategy is what most use. Perhaps this configuration option needs to be more pronounced in the documentation - I mean, "overriding BLT" isn't exactly an intuitive place to look when you're even aware that BLT install's Drupal in the first place (only find that out when it breaks).

**Comment by danepowell** [comment]
I agree that sync isn't a sensible default out of the box only because there is no remote site when you first set up a BLT project. So there'd be nothing to sync from and test.

Long-term, however, I agree that most projects _should_ be using sync as the strategy in order to test update hooks. This could be instead of or in addition to testing fresh installs.

See my overall recommendation here: #3116

**Comment by mikemadison13** [comment]
closing. projects can certainly change their projects to "sync" if they so desire, but there has to be an end environment to sync "from" and it's not a safe assumption that all projects will have that.

**Comment by fiasco** [comment]
Ok, I get that sync isn't a good idea at the beginning. Perhaps I should be asking if installing Drupal in the CI process is a sensible default? out of the box, BLT/Lightning should be validating that process anyway and customers will only ever want to proceed to that step IF they intent to contribute tests?

**Comment by fiasco** [comment]
@lpeabody My last comment is questioning setting Drupal up in CI. In other words, neither sync nor install would be a default. Instead, CI would only build by default making the validation step (which is what requires the install or sync) an opt-in feature.
