### ISSUE TITLE
Establish best practice and support for testing and setup strategies

### ISSUE THREAD

**Issue by danepowell** [acquia/blt#3116]
Based on issues like #3109, it's clear that people are looking for guidance and additional functionality around how to run automated tests specifically in regards to setup strategy.

My opinion is that BLT should default to using the `install` strategy out of the box in CI environments, but that long term all sites should use one of two approaches:
- Single site installs should use the `sync` strategy, which ensures that database updates get tested against live content
- Multisite / ACSF installs should use a duel strategy: `sync` or `import` first in order to test database updates against sites with live content, then `install` to ensure that _new_ sites can be installed in the future.

I think we should try to align on a recommended approach, document it, and then implement any necessary changes to support it. Note that the second approach is currently unintuitive to configure (you basically have to hack the `sync.commands` variable), I think this could be supported more cleanly.

**Comment by lpeabody** [comment]
> (you basically have to hack the sync.commands variable)
Can you elaborate on this statement? In what circumstances would altering sync.commands be needed?

**Comment by lpeabody** [comment]
I think what would be helpful to a lot of folks is, in addition to getting these two items well documented, that the configuration structure in its entirety be documented. For every configuration item, document what commands use it and why they use it.

I find myself digging through the source code and finding configuration in build.yml that is referenced in the source, experimenting with overriding it in various levels of blt.yml files, and see if I'm happy with the resulting execution. I shouldn't be having to dig through the source as much as I am, I should be referencing a set of documentation with cleanly defined use cases and explanations of every BLT command and configuration item.

So my asks are:

1. Document every single command. Explain what they do and which additional commands are invoked by issuing that command.
2. Document all of the configuration items (and possible values) BLT consumes. Explain the purpose of the `setup` configuration and why it exists, and explain what each nested configuration item does (e.g. `setup.strategy` defines which supported setup strategy should be executed in the context of a given site).
3. Keep the configuration overrides documentation front-and-center.

Every complaint or gripe I've heard about adopting BLT has come from people not knowing how to intuitively get started with it or adapt it to suit their current project needs.
They don't know when they should be deferring to BLT to do something or when to simply use Drush, or they don't understand the configuration override system or the notion of site contexts, etc... People just have a lot of questions and they're having a hard time getting answers.

Sorry to pile on, but, I think my asks here warrant consideration at the very least. BLT does A LOT. I don't even know what genre of application BLT falls under, I personally view it as a sort of compiler. There's nothing else quite like it. It has amazing potential (I will use it for as long as it is supported, I find it to be an indispensable tool), but lacks in a superb quality set of documentation to help it become more fully adopted.

If you feel this issue can be re-forged into a greater documentation overhaul, or if I should open up another issue to address this, or if you think I'm off base, please let me know. I just want to see people enjoy using BLT and appreciate the problems it is solving for them, rather than fight it and want to quit using it altogether.

Thanks for reading.

**Comment by danepowell** [comment]
> (you basically have to hack the sync.commands variable)

What I mean is that currently if you want to run multiple kinds of setup as part of a single _setup_ command, you need some way to hook into the process. The easiest is probably by overriding the `sync.commands` config (see the default value in build.yml). So you'd set the `setup.strategy` to `sync`, then add something like `setup:drupal:install` to the `sync.commands` array. Maybe you could use an actual pre-setup/post-setup hook too, I don't know, I haven't tried it. Regardless, it seems pretty kludgy.

**Comment by lcatlett** [comment]
I'm cautious to recommend this new proposed type of setup strategy in BLT as an Acquia best practice since running `import` or a `sync` command followed by a site install is not the same install / update process that occurs on the upstream production environment, especially on ACSF. 

While I am very much in favor of running tests against live content in addition to a new install as part of every CI build,  I'm not sure I follow the logic behind adding an additional setup strategy to BLT rather than setting up two test scenarios in the CI config which mirror the end-to-end build / deploy/ install / update tasks of the production environment. 

It seems like users of BLT would benefit more from improved docs and maybe sample CI scripts about how to use existing BLT config to accomplish common scenarios such as running tests against a demo site, syncing and sanitizing production data, running core or contrib module tests, parallelizing builds, or integrating 3rd additional tools or production-like components like memcache or Varnish within CI builds
