### ISSUE TITLE
Memcache settings doesn't work with memcache 8.x-2.0

### ISSUE THREAD

**Issue by haggmand** [acquia/blt#3220]
System information:
* BLT version: 9.2.1
* Requiring `/../vendor/acquia/blt/settings/blt.settings.php` in `settings.php`

In memcache.settings.php the bootstrap_container_definition is out of date and does not work with the stable release version of the Memcache module (8.x-2.0).

Correct bootstrap_container_denfinition is discussed here:
[https://www.drupal.org/project/memcache/issues/3002858](url)

In the memcache modules README.txt this is also stated.

**Comment by lcatlett** [comment]
@haggmand BLT currently [locks to the 2.0-alpha7 ](https://github.com/acquia/blt/blob/9.2.x/composer.suggested.json#L16)version of the memcache module because Acquia does not yet recommend that customers update to 2.0. We align our settings and package versions with the [Acquia documentation on docs.acquia.com](https://docs.acquia.com/acquia-cloud/performance/memcached/enable/#configuration-for-drupal-8) as much as possible to make sure we don't have contrasting recommendations from different Acquia products to avoid confusion in the Support ticket queue and to ensure that BLT remains an Acquia supported project. 

Internal testing is still ongoing for the memcache module 2.0 stable release, particularly the new support for cache tags, and as you pointed out there are also settings.php changes that will be required which are not backwards compatible. This also means that the settings recommended for releases prior to beta1 (and currently in BLT 9 and 10) will not work with the stable release. BLT will update the settings in lockstep with the Acquia docs team, as we work very closely with the docs team to make sure our messaging is consistent.

**Comment by lcatlett** [comment]
closing due to response above
