### ISSUE TITLE
Protocol error when running any blt command inside VM

### ISSUE THREAD

**Issue by juanjosedeleon** [acquia/blt#3329]
My system information:
* Operating system type: Windows 10 Pro
* BLT version: 9.1.8

Output of `blt doctor`:
I can't run any blt command. The output I get is:
```
-bash: ./vendor/bin/blt: Protocol error
```

When I run any blt command such as `blt setup` I get the same Protocol error message. This also happens with other command, for example if I try to run `composer install`:
```
  [Symfony\Component\Process\Exception\ProcessFailedException]
  The command "'/var/www/myproject/vendor/bin/phpcs' '--config-show' 'installed_paths'" failed.

  Exit Code: 2(Misuse of shell builtins)

  Working directory: /var/www/myproject

  Output:
  ================


  Error Output:
  ================
  sh: 1: /var/www/myproject/vendor/bin/phpcs: Protocol error
```

I'm running Vagrant inside an Ubuntu for Windows (WSL) shell. I can go into the shell with `vagrant ssh` and attempting to run BLT commands from there.
As additional info, I have deactivated Hyper-V and I'm running VirtualBox as VM provider. This is a repo I forked from an existing project.

Any advice? Thank you.

**Comment by lcatlett** [comment]
@juanjosedeleon - "Exit Code: 2" errors are commonly caused by anti-virus software and / or VPN services running on Windows 10. Do you happen to be using either when you are running the failing blt commands? If so, you might want to temporarily disable the package on your host to see if it is the root cause.

**Comment by juanjosedeleon** [comment]
Thanks for your reply @lcatlett and sorry for my late one. I tried it again by disabling the Windows Virus protection but had no success.

I have been running my project within Docker containers in the meantime, however there are some performance issues and hopefully I'll find a solution to get the Vagrant alternative running in the future.

**Comment by danepowell** [comment]
This is not something I've seen before. Since it happens with commands other than BLT, I would suggest opening an issue in the DrupalVM issue queue: https://github.com/geerlingguy/drupal-vm/issues

It sounds like something about your system is corrupt, possibly due to antivirus or some other corporate security restriction.

Unfortunately, it's not something that I can troubleshoot unless you can provide more specific steps to reproduce. Windows is really hard to support because of edge cases like this.
