### ISSUE TITLE
"BLT installation failed! Please execute C:/Users/

### ISSUE THREAD

**Issue by Momodoujobe** [acquia/blt#3359]
My system information:
* Operating system type: [Windows] 
* Operating system version: [Windows 10]
* BLT version: [9.2]

Output of `blt doctor`:
```
[

![52077064-0f93aa80-255e-11e9-91f6-1e8e5ccc4d31](https://user-images.githubusercontent.com/46496452/52139005-d8d09980-261c-11e9-87cd-a05200b01110.png)


]
```

When I run this command:
``` 
[composer create-project --no-interaction acquia/blt-project blt-project]
```

I get the following output:
```
"BLT installation failed! Please execute C:/Users/Mjobe/projects/BLT-Project/vendor/acquia/blt/bin/blt internal:create-project --ansi --verbose to debug the issue.
"
[replace with ENTIRE command output. DO NOT enter partial output.
![image](https://user-images.githubusercontent.com/46496452/52139053-061d4780-261d-11e9-9538-aab917206f15.png)

![image](https://user-images.githubusercontent.com/46496452/52138852-61026f00-261c-11e9-90dd-5a84a20cd274.png)


 ran
C:/Users/Mjobe/projects/BLT-Project/vendor/acquia/blt/bin/blt internal:create-project --ansi --verbose

![image](https://user-images.githubusercontent.com/46496452/52138873-74add580-261c-11e9-82f2-be0a94f5f756.png)
]
```

And I expected this to happen:

**Comment by mikemadison13** [comment]
Can you try updating to 9.2.x and see if things are better?

Also does this issue now supersede the one you opened yesterday?

**Comment by Momodoujobe** [comment]
Is the same issue I am still stuck on the same spot.

**Comment by alexxed** [comment]
Hi @Momodoujobe ,

We have a guide to install BLT on Windows here https://blt.readthedocs.io/en/latest/windows-install/ using Ubuntu on Windows.

Can you use that, or are you set on using babun for any reasons ? We haven't tested yet BLT on cygwin.

**Comment by justinlevi** [comment]
@alexxed From my minimal experience working with Ubuntu on Windows, it's more trouble than it's worth. 

- You can't easily use explorer to get to the WSL filesystem
- Launching a gui code editor like VSCode from the command line was a pain the last I checked.

The Babun cygwin environment works well with Docker based LAMP stacks like Docksal and DDEV. Ultimately, I personally think doing web development on a Windows platform is bananas but there are lots of people who don't have a choice.

**Comment by mikemadison13** [comment]
@justinlevi agree with most of what you've said, I'm just not sure (to echo @alexxed) if any BLT testing has been done with Babun, so it's not terribly surprising that there are issues. Can it work? I'm sure it can, I just don't know that it's a use case we have explored or developed for.

**Comment by alexxed** [comment]
I tested with latest babun on Windows 10 and found the problem is a path one. BLT has in its code hardcoded forward slash, but babun uses php compiled for windows, so system calls like __DIR__ will return paths with backslash. So blt ends up trying to execute commands with a combination of both which fails. In this case, it fails to rsync the template.

**Comment by alexxed** [comment]
Further investigation shows the fault is in [symfony/process](https://github.com/symfony/process/blob/master/Process.php#L311) that uses proc_open and on Windows sets bypass_shell to false, so composer will try to execute vendor/bin/blt as a windows binary; which does not work, that's why the message reported.

**Comment by alexxed** [comment]
@justinlevi [you are not supposed to change the internal files](https://blogs.msdn.microsoft.com/commandline/2016/11/17/do-not-change-linux-files-using-windows-apps-and-tools/), that's why the Linux files are not in an obvious location. But you don't need to, you'll create your projects in your Windows home directory and access them from /mnt/c/Users/Alex/ for example.

To use VSCode from wsl, just type code . in a directory for example and it will open the folder in vscode.

For docker, you can either use docker.exe from wsl, or [setup the linux docker to connect remotely to the windows one](https://nickjanetakis.com/blog/setting-up-docker-for-windows-and-wsl-to-work-flawlessly).

**Comment by alexxed** [comment]
After fixing the first problem, the next one is a misunderstanding between what php provides as current directory and the rsync command available from babun (cygwin).

PHP provides paths like C:/Users/ but rsync wants /cygdrive/c/Users.
```
{ ~ }  » cygpath C:/Users                                                                   ~ 127
/cygdrive/c/Users
```

Some software under cygwin copes with both paths, rsync does not.

**Comment by alexxed** [comment]
After fixing the rsync problem, there are some posix calls in the way:
```
 PHP Fatal error:  Uncaught Error: Call to undefined function Acquia\Blt\Robo\Inspector\posix_getpwuid() in C:\Users\alexa\blt\src\Robo\Inspector\Inspector.php:487
```

I think we can definitely conclude here that blt needs more work to work in Windows, work that I don't think is worth doing because in the end you'll have to run blt in the VM/Docker container anyway which is Linux.

So what I suggest here is clone the template project: https://github.com/acquia/blt-project in a directory, use that directory to set up a docker environment (docksal, ddev, lando). Then use those tools to run composer install inside the docker container instead of the windows machine. After that, blt will be available in the container.

**Comment by alexxed** [comment]
@mikemadison13 considering the above, I think we should show an error message that Windows is not supported on BLT install. But make sure it's not displayed when in WSL.

**Comment by mikemadison13** [comment]
agreed @alexxed, i think having a blanket "Windows is not supported unless using the WSL" message makes sense. We should update the documentation to be a little more explicit here. I would love if there was a way to expand this in the future, but that's the state of the world for now.

**Comment by alexxed** [comment]
I'll put up PRs for the message and to update documentation on what to do if WSL is not an option on Windows.

**Comment by alexxed** [comment]
@Momodoujobe although the resolution for now is that we don't support babun, since I saw you wanted to use docksal, you can use it's cli container like it's described here: https://blog.docksal.io/docksal-and-acquia-blt-1552540a3b9f .

So you'll run blt in the container, not on Windows, by prefixing `blt` with `fin` commands.

**Comment by Momodoujobe** [comment]
Thank you @alexxed & @mikemadison13 after running into so many issues with windows, I decided to invest in a mac and I haven't faced an issue ever since.
