### ISSUE TITLE
DT-594: Add Variable Analysis

### ISSUE THREAD

**Issue by mikemadison13** [acquia/blt#3385]
Enhancement from the second half of https://github.com/acquia/blt/issues/2289

Once coder supports phpcs 3, use that in BLT, and add the variable analysis plugin to our composer.json and phpcs.xml.dist

Or better: is this something that Drupal Core could incorporate into its own ruleset?

Tangentially: for anyone setting up inspections for BLT (and any other project) in PHPStorm, it's best to disable all built-in inspections and instead rely on the PHPCS bin and ruleset provided by individual projects (including BLT).

The only exception for the timebeing is obviously undefined variable analysis, leave that enabled.

**Comment by danepowell** [comment]
It turns out this already working in BLT without the need to specifically include another sniff.

BLT already uses the DrupalPractice standard, which includes a variable analysis sniff copied verbatim from the suggested VariableAnalysis package: https://github.com/pfrenssen/coder/blob/8.x-3.x/coder_sniffer/DrupalPractice/Sniffs/CodeAnalysis/VariableAnalysisSniff.php
