### ISSUE TITLE
BLT config should check and warn for aliases that would overwrite remote

### ISSUE THREAD

**Issue by ghazlewood** [acquia/blt#3454]
My system information:
* Operating system type: any
* Operating system version: any
* BLT version: any

When I run this command locally:
```
blt sync
```
aka [ds|drupal:sync|drupal:sync:default|sync|sync:refresh]

with the following local.blt.yml configuration:

```
drush:
  aliases:
    local: my.production.drush.alias
```

I may end up dropping all tables in the remote database and overwriting my remote/production database with my local database.

And I expected this to happen:

```
To get a warning that I am about to overwrite the remote database, which may be production!
```

This could also happen if the default blt.yml file was changed.

To avoid this in future a warning should be displayed if `local:` isn't set to `self`.

**Comment by ghazlewood** [comment]
I'm not totally aware of how BLT does things, but it looks like the right place to have a warning or something would be [/src/Robo/Commands/Sync/SyncCommand.php 's syncDb](https://github.com/acquia/blt/blob/061a0f5c7fa191020a89d0362b8fc3cf0d1b329f/src/Robo/Commands/Sync/SyncCommand.php#L124)

**Comment by danepowell** [comment]
Thanks for the suggestion. We definitely don't want people clobbering production dbs. However, I can't think of a reasonable way to implement this. Furthermore, it's a pretty outlandish misconfiguration to make.

Your test case is missing something, it would require that you also set the remote alias to be a local alias in order to overwrite production with a local db as you describe:
```yaml
// DANGEROUS CONFIGURATION, DO NOT USE
drush:
  aliases:
    local: foo.prod
    remote: self
```

At some point, we have to rely on users configuring things in a sane way. If you've already configured your aliases that way, I'm not sure that an additional warning would really help.

Keep in mind that BLT has no way to know that the local alias that you've defined is actually a "remote" / production database. It's perfectly valid to have a local alias that's not self, for instance if you are using a VM. I can't think of any other criteria on which to base such a warning.

If you wanted to submit a PR for this, I might consider it as long as it's not too obtrusive for normal users (we don't want needless warnings/confirmations). But otherwise it's not on the roadmap.
