### ISSUE TITLE
Updating to Drupal 8.6.13

### ISSUE THREAD

**Issue by mikemadison13** [acquia/blt#3480]
Given https://www.drupal.org/sa-core-2019-004

For acquia/blt versions 9.2.x and 10.x
```
composer update webflo/drupal-core-require-dev --with-all-dependencies 
```

For acquia/blt version 9.0.x and 9.1.x
```
composer update drupal/core --with-all-dependencies 
```

**Comment by mikemadison13** [comment]
Note that this update should not require any change in Lightning, BLT, or any other packages.

**Comment by nirojghale-iheartmedia** [comment]
I ran this command `composer update webflo/drupal-core-require-dev --with-all-dependencies 
` nothing changed.

I still see this hard-coded Drupal Core version in vendor/acquia/blt/composer.required.json file
` "require": {
    "drupal/core": "^8.6.0",
    "drupal/config_split": "^1.0.0"
  },`

**Comment by dpagini** [comment]
Try `composer update webflo/drupal-core-require-dev drupal/core --with-all-dependencies` maybe?

**Comment by danepowell** [comment]
For major upgrades, I think it's better to just do `composer update` without package whitelists or `--with-all-dependencies`. Otherwise you can run into problems like this, or the opposite problem (some packages get updated but not their siblings or nested dependencies.) I think this has gotten better in recent versions of Composer, but I still wouldn't completely trust it.

**Comment by anavarre** [comment]
Note also the Drupal community recommends the use of the `--with-dependencies` parameter (see [doc page](https://www.drupal.org/docs/8/update/update-core-via-composer)) when updating Drupal core, which is perhaps why it's preferred (or the `--with-all-dependencies` alternative) over `composer update` for many users, because you can then isolate core updates from any random contrib / library module update.

**Comment by danepowell** [comment]
Yep, neither method is ideal. I think `composer update` is less error-prone in the long term as long as you are generally responsible about keeping packages up to date, and make sure that you are aware of what packages are getting updated.

**Comment by nirojghale-iheartmedia** [comment]
None of those above command is working. Can we not lock the drupal core version in the blt composer.required.json ? or how can we override any of the modules defined in the blt composer.required.json ?

**Comment by danepowell** [comment]
@nirojghale-iheartmedia can you be more specific? How is it "not working"? What's the output of `composer why-not drupal/core:8.6.13`?

**Comment by mikemadison13** [comment]
The biggest concern I have with a more generic composer update, is that if you are just doing a drupal/core or webflo update for a security patch, the broader composer update will update a LOT of other stuff (that may make the deployment more trouble than a simple security update). I highly advise against ever running `composer update` without specific flags unless you know precisely what is going to change.

**Comment by lcatlett** [comment]
I think also adding `symfony/*` to the update is often recommended when using `drupal/core` to prevent dependency conflicts when attempting to update core (see drupal.org/docs/8/update/update-core-via-composer#known-issues). The full command would then be `composer update drupal/core webflo/drupal-core-require-dev symfony/* --with-dependencies`, which helps avoid the headache of having to manually resolve individual dependencies while also limiting the scope of the update. should we perhaps add a composer script to the the root blt composer.json?
