### ISSUE TITLE
Upgrade Drupal VM version constraint to ^5.0

### ISSUE THREAD

**Issue by geerlingguy** [acquia/blt#3536]
**Is your feature request related to a problem? Please describe.**

Drupal VM 5.0.0 was just released: https://github.com/geerlingguy/drupal-vm/releases/tag/5.0.0

BLT currently uses the version constraint `^4.8` (see https://github.com/acquia/blt/blob/10.x/src/Robo/Commands/Vm/VmCommand.php#L37).

The main change in Drupal VM 5 is the new default versions for underlying software:

  - Ubuntu 18.04 (was 16.04) — _note_: this differs from Acquia Cloud now, which I believe is still on 16.04
  - PHP 7.2 (I believe this is the current default on Acquia Cloud)
  - Node.js 10.x (I believe this is the current recommended version for our frontend tools)

If someone really needs to keep running on Ubuntu 16.04, they can either make sure they install the `geerlingguy/drupal-vm` base box version < 2.0.0, or they can switch the `vagrant_box` to `geerlingguy/ubuntu1604`.

**Describe the solution you'd like**

I'd like us to update the version constraint to `^5.0`.

**Describe alternatives you've considered**

We could not update the version constraint to `^5.0`.

**Additional context**

N/A

**Comment by danepowell** [comment]
I'd like input from the community on this, if anyone else has an opinion.

My only concerns are that (1) the Ubuntu version on ACE would be different, and (2) there are mixed reports as to whether ACSF supports PHP 7.2 (compare [public docs](https://docs.acquia.com/site-factory/known-issues/#acsf-php72) and comments in https://github.com/acquia/blt/pull/3512.

I'm not so concerned about (1), OS version mismatch has rarely been an issue for me. (2) isn't so good, since we'd want to align the default PHP version across Pipelines, DrupalVM, BLT, etc

This change would only apply to projects creating a _new_ VM, which is good (existing users wouldn't be forced to upgrade). So this doesn't seem BC-breaking for BLT users.

@geerlingguy I'm assuming there's nothing BC-breaking in DrupalVM 5 that BLT would need to change to match?

**Comment by geerlingguy** [comment]
@danepowell - Nope! And in fact, if you want to keep the PHP default at `7.1` for the time being, we can just explicitly set that as `php_version: '7.1'` in the BLT `config.yml`.

**Comment by dpagini** [comment]
I can give two quick thoughts...
* I sort of share the sentiment that it's ideal to keep Drupal-VM, CI environments and Acquia all on the same operation system. It's one more thing you can rule out as differences between environments, although I would agree I can't think of anything where OS version has caused me a problem in the past. If it's a concern, just like PHP couldn't the default `box/config.yml` use the old box? Probably not worth thinking _too much_ about though.
* I've actually _also_ had problems upgrading our PHP to 7.2 on Acquia. We use SSO and there was an underlying system PHP library that needed to be upgraded, and Acquia acknowledged it was on the roadmap, but there was no ETA for that upgrade. I'm not sure of the current status of that, but it left us unable to upgrade to PHP 7.2 until that was addressed.

**Comment by danepowell** [comment]
Opened a PR for folks to provide any additional feedback: #3539 

Seems like the best option is to upgrade DrupalVM and PHP versions, and just add a warning for ACSF users. I don't want to hold back the whole project because of just ACSF. And regardless of ACSF / ACE / etc..., people could use different PHP versions in any environment and need to be aware of that, these are just defaults.
