### ISSUE TITLE
Drush 9.6 issue with Acquia Cloud PaaS

### ISSUE THREAD

**Issue by christopher-hopper** [acquia/blt#3555]
**Is your feature request related to a problem? Please describe.**

Recently we were running minor version updates for a client and ran into a problem with Drush 9.6.x on Acquia Cloud. This is a known issue but is fairly new, having only recently been documented in the Acquia Cloud Knowledge Base.

https://support.acquia.com/hc/en-us/articles/360020691873-Drush-9-6-issue-with-Acquia-Cloud 

**Describe the solution you'd like**

It may help others if Acquia BLT can prevent projects from updating to Drush versions that are known to not work on the Acquia Cloud PaaS. Suggest adding the following version constraint to Acquia BLT:

    composer require drush/drush:~9.5.2

This would allow updates to: `>=9.5.2  <9.6.0`

The restriction could be lifted once Acquia has completed work to rewrite its custom coded Drush commands.

**Describe alternatives you've considered**
> A clear and concise description of any alternative solutions or features you've considered.

**Additional context**
> Add any other context or screenshots about the feature request here.

This is not the same as #3513

**Comment by danepowell** [comment]
@christopher-hopper the link that you posted to Acquia documentation does not work for me, do you have a different one? I'm aware of incompatibility with Pipelines (#3513) but not with Cloud more generally.

I don't think limiting the Drush version for all BLT users makes sense, since many non-Acquia customers also use BLT and may wish to use Drush 9.6. I'm open to other suggestions about how to handle this though. Documentation (via release notes) is the approach I've been using.

**Comment by greylabel** [comment]
The [link](https://support.acquia.com/hc/en-us/articles/360020691873-Drush-9-6-issue-with-Acquia-Cloud) was working as of last week, IIRC. Any chance it now being a 404 means the issue has been fixed?

**Comment by christopher-hopper** [comment]
I have no idea if the issue is fixes or not. I also have no other links.
We've addressed the problem by using the Acquia recommended solution, which
was to downgrade our drush installed version.

Hopefully this helps others using the platform with BLT. You can assess if
anyone else hits issues with drush I guess.

--
Christopher Hopper

**Comment by lcatlett** [comment]
@christopher-hopper - the [updated known issues notice ](https://support.acquia.com/hc/en-us/articles/360022116553-Acquia-Cloud-experiencing-temporary-issues-involving-drush-dependencies-for-all-users-of-drush-9)was just posted, which unfortunately expands upon the information in the original (now unpublished) notice to all customer codebases using Drush 9, both vendored and Acquia global:

> Acquia Cloud is experiencing a temporary issue involving drush aliases for all users of drush 9.3 or higher.  A custom drush command (written for Acquia Hosting) utilizes code that became obsolete when drush factored SiteAlias classes out into the consolidation/site-alias project in drush 9.4.  Drush extensions such as the ah-* drush commands that directly reference site alias classes must update namespaces in order for drush 9 to work as expected on Drupal 8. 
> 
> This change currently prevents Drupal from being bootstrapped for all users of Drush 9 installed via composer with updated dependencies.

This is the same issue that was reported to BLT in https://github.com/acquia/blt/issues/3204 which will need to be resolved in BLT or upstream packages once Acquia Cloud engineering has resolved the underlying bug. 

Acquia Support and engineering teams are aware of the impact of this issue currently and are treating it with high urgency, however if you are experiencing issues impacting busines-critical tasks and/or your production environment, please file a support ticket through your subscription in the Acquia Cloud UI since issues filed directly to the BLT github project [are not currently subject to the Acquia SLA](https://github.com/acquia/blt/blob/10.x/docs/CONTRIBUTING.md#submitting-issues).

**Comment by danepowell** [comment]
I will continue to link to the known issues in release notes, but other than that I do not see what action BLT can take to assist with this, nor have I seen any proposals for how projects such as BLT should work around it. Judging by the known issues page, it sounds like the only workaround is for individual projects to use different Drush versions.

If anyone has a specific recommendation for how BLT can assist with this issue or a specific test case for something that BLT is currently doing wrong, please let me know and I'm happy to reopen.

**Comment by danepowell** [comment]
@alexxed if there's a known issue with Drush 9.6 on Acquia Cloud, it might make more sense to incorporate a check for this into ADS, which is Acquia-specific.
