### ISSUE TITLE
Pre-commit composer.lock validation passes when file is unstaged

### ISSUE THREAD

**Issue by gardon** [acquia/blt#3557]
**Describe the bug**
When you attempt to commit changes to composer.json file and it's not consistent with composer.lock the validator fails, but after updating the lock file without staging it, the validator passes, commiting potential inconsistent composer files.

**To Reproduce**
1. Make some changes to composer.json without updating the lock file. Stage the file for commit.
2. Try to commit. The message suggests a simple regeneration of lock file.
3. Run `composer update --lock`
4. Do not stage composer.lock. Try to commit again. Commit should succeed, while the actual changes to composer.lock are left unstaged.

**Expected behavior**
Composer should test for a staged composer.lock when composer.json is staged.

**System information**
* Operating system type: OS X
* Operating system version: 10.12.6
* BLT version: 9.2.4

**Comment by danepowell** [comment]
It seems like this problem wouldn't be specific to composer validation, but could occur for any other pre-commit check (such as code linting and sniffing). The problem is that PHPCS, composer validate, etc... can only read files as they exist on disk, not as they exist in Git staging.

The only solution I see would be to add a pre-validation function to ensure that every file being scanned doesn't have an unstaged version. That could be ugly, since the checks use disparate filesets and we may not know what they are _a priori_.

**Comment by gardon** [comment]
I resumed work on a project and realized the last changes I did to pass PHPCS (Adding function comments) never really went through because I had forgotten to stage before commit, so same issue as above. Maybe we can just display some warning at the end of pre-commit when some of the files checked have unstaged changes to remind developers to verify?
