### ISSUE TITLE
Use composer-scaffold to build new BLT projects

### ISSUE THREAD

**Issue by lcatlett** [acquia/blt#3563]
**Is your feature request related to a problem? Please describe.**
Given the recent progress in adding a composer scaffolding plugin to core to resolve https://www.drupal.org/project/drupal/issues/2982684, BLT should update the current method of assembling files when a new project is created or updated to use @grasmash's new [composer-scaffold plugin](https://github.com/grasmash/composer-scaffold) since it is now the basis for the in-progress core-patch which does the same: https://www.drupal.org/project/drupal/issues/2982684#comment-13067069)

**Additional context**
The readme in `grasmash/composer-scaffold` has significant updates in the not-yet-merged https://github.com/grasmash/composer-scaffold/blob/824b0eb12600ffb9edeca46cd68e3a27efe417de/README.md which outline how vendors and projects like BLT are expected to manage vendor overrides to config and the location of other files provided by core.

**Comment by danepowell** [comment]
This is the first I've heard of composer-scaffold. If I understand correctly, the goal here would essentially be to replace drupal-scaffold (which BLT currently uses to download non-composer Drupal files) with composer-scaffold? composer-scaffold's readme also mentions being an alternative to composer/installers, but I don't see how composer-scaffold supports placing modules and other packages into arbitrary directories, it only has examples for core.

Drupal Scaffold is pretty well established and broadly used, such as by drupal-project and lightning-project. I'm hesitant to hitch our cart to a new horse, as neat as it sounds, unless that's where the whole community is going. Have the maintainers of drupal-scaffold talk about officially deprecating that project? Has lightning-project talked about switching? These are the kinds of questions we'd need to answer before making such a big shift.

Maybe @grasmash can provide some context?

**Comment by grasmash** [comment]
The idea is to actually merge Composer Scaffold into Drupal Core and then deprecate Drupal Scaffold. Once it's committed to core in a dev branch, it would be worthwhile for BLT to begin looking at deprecating Drupal Scaffold in preparation for Drupal 8.8.0, which is the target release for core scaffolding functionality.

**Comment by danepowell** [comment]
Thanks, that context is a lot more helpful. I'll add this to the 11.0 milestone, since BLT 11.0 will be released coincidentally with Drupal 8.8.

**Comment by danepowell** [comment]
This has been merged in core: https://www.drupal.org/docs/develop/using-composer/using-drupals-composer-scaffold

Additionally, Matt points out that it has some other features that could be useful, such as the ability to delegate the creation of Acquia-specific files to a sub-package that also uses Composer Scaffold, i.e. `acquia/drupal-scaffold-files`. Sounds useful although I haven't exactly figured out how yet.

**Comment by grasmash** [comment]
Yes. Acquia should create a new package like `acquia/scaffold` and BLT should require it.  

It would look something like this. 

*acquia/scaffold*

```
  "name": "acquia/scaffold",
  "require": {
    "drupal/core-composer-scaffold ": "*@stable"
  },
  "extra": {
    "composer-scaffold": {
      "locations": {
         "web-root": "./docroot"
      },
      "symlink": false,
      "overwrite": true
    }
  }
}
```

*acquia/blt-project*

```
{
  "name": "acquia/blt-project",
  "require": {
    "acquia/blt": "^10.2.0",
    "acquia/scaffold": "^1.0.0"
    "drupal/core": "^8.8.x-dev",
  },
  "extra": {
    "composer-scaffold": {
      "allowed-packages": {
        "drupal/core": "*",
        "acquia/scaffold": "*"
      }
    }
  }

```

**Comment by danepowell** [comment]
As much as I'd love to get on board with Composer Scaffold, I don't see how we can do this any time in the foreseeable future. There are at least two major blockers, both of which tied to the fact that Composer Scaffold declares a strict composer conflict with Drupal Scaffold, so they can't both be installed on the same project at the same time.

1. Lightning still depends on Drupal Scaffold, and supporting Lightning for BLT users is a much higher priority than supporting Composer Scaffold. So until Lightning switches to Composer Scaffold, it's unlikely that BLT can. I've already mentioned this to the Lightning team.
2. Composer Scaffold is new to Drupal 8.8, so in order to switch to Composer Scaffold we'd need to drop support for Drupal 8.7, which won't happen until at least May 2020. We might be able to work around this by moving scaffold configuration from BLT's composer.json into BLT Project, but this presents its own challenges (dealing with updates, BLT doctor, etc...)
