### ISSUE TITLE
Optimize autoloader for deploys, but don't optimize locally

### ISSUE THREAD

**Issue by danepowell** [acquia/blt#3591]
**Is your feature request related to a problem? Please describe.**
Matt added Composer config and CLI arguments in #3312 to optimize the autoloader in an attempt to fix #3148. We now know that the root cause of #3148 was unrelated, and this change had no effect at best, and may be disrupting local development at worst.

**Describe the solution you'd like**
According to the [official Composer docs](https://getcomposer.org/doc/articles/autoloader-optimization.md#autoloader-optimization), you should never optimize the autoloader in development environments. We should revert this change.

**Describe alternatives you've considered**
Not do this? I don't know that I've seen any clear problems either way, but I'd prefer to stay on the reservation and do what Composer officially recommends unless there's a clear reason not to. It seems like we got into this situation by essentially spitballing solutions, which I'd like to undo.

Even though this has nothing to do with #3148, since it does touch the autoloader we should make sure that once removed the class errors don't come pack when using the upstream composer patch: https://github.com/composer/composer/pull/8108

**Comment by lcatlett** [comment]
I think most projects just use `[autoload-dev](https://getcomposer.org/doc/04-schema.md#autoload-dev)`for autoloader conffig specific to the local development tools/environment as opposed to disabling optimization by default since the CI environment is presumably set up with php.ini, opcache, and APCu settings that match the prod environment as closely as possible, if not identical. It is usually this config that is under or mis-configured if composer seems to be slow, consuming abnormally high memory due to disk I/O, or dumping autoload and clearing caches isnt working as expected. See https://github.com/aws-samples/aws-refarch-drupal#opcache for opcache recs in particular

**Comment by nateacquia** [comment]
https://backlog.acquia.com/browse/DT-485

**Comment by danepowell** [comment]
The composer docs I linked to above say repeatedly and explicitly to _never_ use optimizations locally. They don't make any allowances or exceptions for using `autoload-dev`. I'm inclined to followed those recommendations.

Obviously it would be better if we could perfectly replicate production configuration in CI, but that's just not likely to happen given how much other stuff we need to keep around for testing purposes. Maybe someday we'll have a hybrid testing system with an isolated production like SUT, but that's well beyond the scope of this ticket.

**Comment by theMubashir919** [comment]
This might be a rookie question but how can I revert the optimize autoload if done?
