### ISSUE TITLE
New 9.2.x Project Fails on Drupal Packagist Composer Requests

### ISSUE THREAD

**Issue by mikemadison13** [acquia/blt#3592]
**Describe the bug**
I created a new project and tried to add a drupal/ package to composer. It failed. When I added the d.o packagist to the composer.json, it was fine.

**To Reproduce**
Steps to reproduce the behavior, _ideally_ starting from a fresh install of BLT:
1. Run `composer create-project acquia/blt-project --no-interaction`
2. once completed, run `composer require acquia/lightning 4.0.0-beta1`
3. the composer request will fail with `acquia/lightning 4.0.0-beta1 requires drupal/lightning_api ^4.0-beta1 -> no matching package found.`
4. manually add the drupal packagist to the repo:
```
"repositories": {
        "drupal": {
            "type": "composer",
            "url": "https://packages.drupal.org/8"
        }
}
```
5. re-run the same command, confirm that it works

**Expected behavior**
Clean project checkout should just work

**Additional context**
I think the BLT 9.2 project template should move the Drupal packagist from the required.composer.json into the root file.

**Comment by mikemadison13** [comment]
I can update this with a PR @danepowell but i'm not sure if it should be in blt-project or in https://github.com/acquia/blt/blob/9.2.x/template/composer.json

**Comment by danepowell** [comment]
I can't reproduce this, and it doesn't really make sense to me that this would just now be a problem unless something radical changed due to an update with composer or the merge plugin.

I think there must be something wrong with your project or development environment, have you tried creating the project again to see if this is a fluke? Can you run blt doctor and/or report your composer version?

**Comment by danepowell** [comment]
I pinged Mike directly, agreed this was a fluke but we'll keep an eye out if it happens again. Add it to the pile of reasons we are dumping composer merge plugin in 10.x.
