### ISSUE TITLE
Check Dirty During Deployments Fails on Permission Variation

### ISSUE THREAD

**Issue by mikemadison13** [acquia/blt#3633]
**Is your feature request related to a problem? Please describe.**
This request is related to the ongoing discussion surrounding https://github.com/acquia/blt/issues/3526. 

I discovered today that even if your files are "identical" the check dirty during deployment will flag an M for any files that have permissions variance.

This is, theoretically, desirable. **However** it's also totally non-obvious and a blocker to deployments.

**Describe the solution you'd like**
Best case scenario, we figure out a way to identify permission based variations vs. actual file modifications. I am not convinced this is possible with git.

Otherwise, we should have a disclaimer in the output of that failure that warns users that if a diff comes back without finding changes that there is a likely a permissions mismatch between pipelines and the repository. Even more ideally we (outside of the warning) should try to identify "what" the permissions should be and advise the change in the text.

**Describe alternatives you've considered**
Add a `git config core.fileMode false` to the the command to ignore file permissions.

**Comment by danepowell** [comment]
I just tested this and Git reports a changed file permission (specifically +x, since that's the only one it tracks) the same as any other change. Specifically, it looks like:
>  M salt.txt
[error]  There are uncommitted changes, commit or stash these changes before deploying.

How is this more or less informative than any other type of dirty file?

Is the real issue here not specific to permissions, but more generally that there's not enough information to debug how files have changed? Do you want a `git diff` in these instances or something?
