### ISSUE TITLE
What happened to the docs on readthedocs?

### ISSUE THREAD

**Issue by shelane** [acquia/blt#3636]
So, I see that yesterday the index page was updated to redirect people to the Acquia docs site. However, the documentation there is lacking considerably compared to the docs that are in the code base. Also, users cannot contribute to docs on Acquia's site.

What was the reason for deprecating the readthedocs site?

**Comment by jigarius** [comment]
It might be a good idea to have moved the docs to docs.acquia.com/blt, however, I believe, one of the following action should be taken to address the old doc pages:

* Add a `410 Gone` HTTP header to the old pages so that Google will eventually unindex the pages
* Add `301 Moved Permanently` header to redirect users to the new docs
  * Redirect all requests to the home page of the new docs if not to the exact page

Currently it seems like the pages are returning `200 OK` and they have no content. So one has to search twice to get to the right doc.

**Comment by danepowell** [comment]
Sorry for the confusion. Yes, official documentation was moved to docs.acquia.com, this was done to harmonize it with the rest of Acquia product documentation. As you observed it is a little out of date, we'll get it synced up very shortly.

The old documentation was on Read The Docs, and unfortunately that's a hosted service that we don't control so I don't think we have any way to set up HTTP redirects. This is part of the reason we would rather use docs.acquia.com, which we have more control over.

If you have any other suggestions about how we might ease the transition, please let us know.

**Comment by danepowell** [comment]
Upstream issue (unlikely to be resolved soon): https://github.com/rtfd/readthedocs.org/issues/2267

**Comment by danepowell** [comment]
RTD just added the ability to have custom 404 pages, so I used that to put up a more prominent redirect notice. Let me know if there's anything else we can do to improve the experience.

https://blt.readthedocs.io/en/latest/
