### ISSUE TITLE
Custom filesets on BLT 10.x

### ISSUE THREAD

**Issue by dpagini** [acquia/blt#3642]
**Describe the bug**
I was previously using custom filesets in BLT. The upgrade to 10.0 appears to have broken this functionality. The example filesets uses a namespace of `Acquia/Blt/Custom` but I believe that is broken with the new "BLT Plugin" functionality.

**To Reproduce**
Steps to reproduce the behavior, _ideally_ starting from a fresh install of BLT:
_Follow the instructions on the [Acquia documentation page](https://docs.acquia.com/blt/extending-blt/#adding-or-overriding-filesets)._

**Expected behavior**
My custom fileset is available to linting functions.

**Detailed error output**
![image](https://user-images.githubusercontent.com/1724163/57640922-a3273f00-7581-11e9-911d-74a157aeff44.png)

**Comment by wu-edward** [comment]
If you look at the project root composer.json for a BLT 10 project, BLT's' PSR-4 autoloader was changed, and the namespace for `blt/src` directory is now `Example` instead of `Acquia\Blt\Custom`, so you might try changing the namespace in your Filesets class accordingly. 

If that's the issue, it looks like the Filesets class template: `scripts/blt/examples/Filesets.php` needs to a PR so it can be updated as well.

**Comment by dpagini** [comment]
Thanks @wu-edward - I have been trying things along that line with no luck. I'm also trying to get the custom commands to work, but I'm not convinced that one isn't "user error" just yet... but so far, no luck with either custom filesets or custom commands.

I also think this `Example\` namespace is a little odd... can we not come up with some better namespace here?

**Comment by dpagini** [comment]
Dug into this a little more... BLT is requiring that a custom fileset is namespaced/named `Acquia\Blt\Custom\Filesets` exactly. The file is getting dropped at `blt/src` but that's also the same location the new `Example` namespace is pointing to as well, so I'm guessing we can't have both things there...? 

For now I got around this by moving my custom commands, and `Example\` namespace, to point to another folder entirely.

**Comment by danepowell** [comment]
Yeah, seems like a bug. As you observed, BLT is hardcoded to look for filesets in the `Acquia\Blt\Custom` namespace, which made sense in 9.2.x when you could only expose filesets via a single directory in the project. But that paradigm breaks in BLT 10.x since we should now be accepting plugins and filesets from _any_ namespace as long as it's exposed correctly via PSR4.

I understand why the Example namespace is confusing, but it makes sense when you think about it along those lines, doesn't it? Any package can declare any number of namespaces that expose BLT commands and plugins. So the namespace should reflect the nature of the plugins. In this case, they really are just examples. I'm not sure what else we'd want to call it.

BTW the docs you linked to about extending BLT are a little out of date, although not in a way that impacts filesets. Just an FYI. I'll make sure they get updated.

**Comment by longmtran** [comment]
+1

I'm having the same issue. I've tried to use `Example` as namespace on the custom `Filesets.php` but still hit the same error.

**Comment by dpagini** [comment]
> I understand why the Example namespace is confusing, but it makes sense when you think about it along those lines, doesn't it?

Yeah, I guess that makes sense...  I guess I would expect more of a suggested default. I personally know enough to change it, I dunno...  If I were to make a suggestion, something like... \Blt\Project\Example` maybe? Honestly, I'm not too worried about it, but it was a little confusing to me when I first started using it.

Thanks for looking at this issue!

**Comment by longmtran** [comment]
@dpagini I take that you have a workaround for it. Would you mind elaborate a bit more on the approach? At the moment, my custom command works when I updated the namespace to `Example\Blt\Plugin\Commands` but the fileset is still hitting the same error as you did.

**Comment by dpagini** [comment]
@longmtran Yep, I alluded to it above... I moved my custom commands to a different folder altogether... As long as they have `Blt/Plugin` in the namespace, and they are correct PS4 (as in the composer.json specifies where they live), they should work. Then I left my custom filesets in the `blt/src` directory with the same namespace I previously used. That's my work-around for now.

**Comment by longmtran** [comment]
@dpagini thanks, will have a try at some point.

**Comment by D41078817** [comment]
I ran across this looking for *how* to create a custom fileset. It was unclear to me, even with the example `blt/src/Filesets.php` file. So, I found this and wanted to link to an example I created: https://github.com/acquia/blt/issues/1812#issuecomment-523897836
