### ISSUE TITLE
How to add --ignore-platform-reqs in Acquia BLT project to ignore soap extensions in CI environment Pipelines Deployment

### ISSUE THREAD

**Issue by arjunpws** [acquia/blt#3686]
I have Drupal 8 project built using Acquia BLT and I am trying to setup the project with acquia pipelines. but when I am using salesforce module in my project it is dependent on soap extension it is working in my local as I have enabled and also it is active in my acquia environments(dev, stage, prod) but the problem is when I have pushed the codes to acquia git and runs the pipelines start command (CI/CD setup) and after some time the build failed and the log is saying
Problem 1 - Installation request for messageagency/force.com-toolkit-for-php v1.0.0 -> satisfiable by messageagency/force.com-toolkit-for-php[v1.0.0]. - messageagency/force.com-toolkit-for-php v1.0.0 requires ext-soap ^7.1 -> the requested PHP extension soap is missing from your system. Problem 2 - messageagency/force.com-toolkit-for-php v1.0.0 requires ext-soap ^7.1 -> the requested PHP extension soap is missing from your system. - drupal/salesforce 3.3.0 requires messageagency/force.com-toolkit-for-php ^1.0.0 -> satisfiable by messageagency/force.com-toolkit-for-php[v1.0.0]. - Installation request for drupal/salesforce 3.3.0 -> satisfiable by drupal/salesforce[3.3.0].

**System information**
* Operating system type: Linux
* Operating system version: Centos7
* BLT version: 10.0.1

**Comment by danepowell** [comment]
This isn't supported out of the box I'm afraid. The best workaround I can think of would be to fork the projects requiring soap, and remove the soap dependency from their composer.json so composer stops complaining.

I'm surprised that your Cloud environment has the soap extension but Pipelines does not. If that's true, I think it would be worth requesting that the soap extension be enabled in Pipelines. It seems to me that Pipelines should mirror production Cloud environments in terms of available extensions. You can submit that request via a support ticket.

Finally, a better long-term fix on the BLT side would be to support ignoring extension requirements when run via Pipelines. The reason this isn't possible right now is because BLT only accepts `--ignore-platform-reqs` via the `deploy` command, which doesn't actually get run on Pipelines since it has its own deployment process. I'll convert this into an enhancement request to account for that.

**Comment by danepowell** [comment]
This is no longer in the BLT roadmap. The best solution would be to get Soap in Pipelines, assuming that's not already the case.
