### ISSUE TITLE
EnvironmentDetector feedback.

### ISSUE THREAD

**Issue by dpagini** [acquia/blt#3804]
Hey @danepowell - just wanted to provide some feedback on the new environment detector stuff.

* I thought the `classmap` addition to the composer file was a little strange. Is there any reason loading the plugin the same way you do for Filesets and Commands does not work? Just include it as a PSR class for your project and then look for a file named "*Detector.php" in the "Blt/Plugin/EnvironmentDetector" namespace? Anyways, having to add that explicitly I thought was confusing.
* The way it's built, while I'm sure there are technical reasons/limitations, is a tad bit confusing. The only way I can overwrite the base function is by returning TRUE from my subclass. If I return FALSE, the original code still gets executed. It's not causing me any problems, but was just confusing to realize that's what was happening and that I don't have a great way to stop the original class running, if I needed to.
* Obviously you can only override the methods _you_ build into BLT. Not a big deal to me, just a limitation.
* Maybe declare your class "abstract" since its not meant to be an object? Not sure if that's a valid use of abstract classes.
* Not sure if this would be a good practice... I know everything is a static method, so maybe using static variables would work... anyways, just a suggestion to "cache" the results of a command so when this gets called multiple times from the settings includes files, if we already know this is DEV, just return the result... So like...

```php
static protected $ahStage;

public static function isAhStageEnv() {
  if (is_null($ahStage)) {
    $ah_env = self::getAhEnv();
    // ACE staging is 'test' or 'stg'; ACSF is '01test', '02test', ...
    $ahStage = preg_match('/^\d*test$/', $ah_env) || $ah_env == 'stg';
  }
  return $ahStage; 
}
```
Truth be told, I'm not even sure if the above works with global/static variables, I don't use them a lot... but just thought it would make sense not to evaluate some of these methods over and over again on a single request.

--- 

That's all to say, I think this was such a great addition to BLT and thank you for finding a very clever solution here! Please feel free to close this unless you think anything is actionable here.

Thank you as always!  🎉

**Comment by danepowell** [comment]
Thanks for the feedback. I definitely appreciate that the method for overriding the detector feels a bit kludgy, but I couldn't think of any better solutions. Definitely open to suggestions. I'll try to respond to each of your points individually when I have a little more free time. #3814 might also help a little by better documenting this functionality.

**Comment by danepowell** [comment]
* The reason you have to define the classmap is primarily for performance. Unlike most other BLT plugins that only run when you run `blt` via the CLI, the environment detector gets called multiple times on every Drupal web request. This means that the application container (and Robo plugin discovery methods) is not available to is. Furthermore, the way that Robo does plugin discovery is by literally searching every file in the PSR4 space to find matching file/class names. I don't know exactly how performant that is, but the idea of doing that multiple times on every single page load scares me. Forcing plugin developers to add a single line to their composer.json (though not ideal) seems like a good trade-off.
* The use case we imagined for overriding the environment detector is to support alternative hosting environments. In these environments, the built-in detector methods (isProd, isDev, etc...) should all return false normally. So you'd only ever want to override them to be true. Do you have some other use case?
* The base environment detector is static but it's not abstract, it is called directly and doesn't have any abstract methods. I'm not sure why we'd want to declare it abstract?
* XHProf reveals that all of the environment detector methods add a total of ~30ms to a page load. That's not nothing, but not terrible either. Might be worth looking into reducing.

Overall, I understand that implementing your own detector is not the most intuitive pattern. It would be _so_ much better if there was a way to handle this using native inheritance, but since BLT is instantiating the base detector in its own settings I just can't think of any way to instantiate an end-user version of the class instead. Plus this wouldn't support having detectors provided by multiple plugins.

If you have specific suggestions for how to improve the DX, ideas or pull requests are certainly welcome.

**Comment by danepowell** [comment]
Actually in profiling page loads for this, I found that some other BLT functions contribute an order of magnitude more time to page loads, although only on local installs I think. But it's all worth following up on: https://github.com/acquia/blt/issues/3823

**Comment by dpagini** [comment]
> The reason you have to define the classmap is primarily for performance.

Makes a lot of sense... 👍 

> Do you have some other use case?

I don't... it was more just an observation.

> The base environment detector is static but it's not abstract

👍 

> If you have specific suggestions for how to improve the DX, ideas or pull requests are certainly welcome.

Nope, nothing specific... like I stated in the first post, just wanted to give some feedback from actually using it. It wasn't even that well thought out feedback. This was a really great addition to the project, so thank you for all your work on this!

**Comment by danepowell** [comment]
No problem. I've said it before and I'll say it again, this is one of the uglier implementations I've had to work on, but it's also just an ugly problem, so I understand your concerns. If there's anything else we can do to make it better feel free to open a new ticket.
