### ISSUE TITLE
Retry composer install upon failure for Travis CI

### ISSUE THREAD

**Issue by trwill** [acquia/blt#3832]
**Is your feature request related to a problem? Please describe.**
Recent (possibly infrastructure related?) bug causes composer patch download to fail causing sporadic build failures for TravisCI. One suggestion in the [d.o issue](https://www.drupal.org/project/infrastructure/issues/3076207) was to prefix the special helper `travis_retry` to `composer install` - we are considering adding this to our project but are curious if maintainers here see a different path forward or would consider adding as default. 

Related;
https://www.drupal.org/project/infrastructure/issues/3076207

**Describe the solution you'd like**
Prefix `travis_retry` to `composer install` line in travis.yml

**Describe alternatives you've considered**
Waiting for fix to infrastructure (?) or [composer-patches ](https://github.com/cweagans/composer-patches/issues/279)

**Additional context**

**Comment by danepowell** [comment]
The fix to composer-patches was committed and released, I think that's a much preferable alternative to fixing this individually for every CI platform. Otherwise, users with legitimate problems with their composer files (other than just transient network errors) will need to wait 3-10x as long (depending on how many retries you want to allow) to get the failed test. Would you agree?

**Comment by trwill** [comment]
Thanks @danepowell that makes sense
