### ISSUE TITLE
Please advise on the correct deploy steps

### ISSUE THREAD

**Issue by dimdiden** [acquia/blt#3843]
Hello Team,
Please help me to understand the most preferable way to use BLT for ci/cd processes

**I want to...**
We are using BLT tool as part of the deployment process. The branching model is GitFlow.
When the master branch gets a new commit, we are deploying the master branch as follows:
`BLT deploy --no-interaction --branch master`
The Acquia master branch is pointed to Stage env.

When we decide the release is ready to be deployed to prod env, we make a tag on our repository and then the tag is deployed as follows:
`blt deploy --no-interaction --tag <tag_name>`

However, both commands have an identical set of time-consuming tasks: git, rsync commands, etc..

I thought, there could be an option to use blt as follows
1.  blt build (main set of tasks) -> save as artifact on CI system
2. blt deploy --no-build --branch master (just push to Acquia)
3. blt deploy --no-build --tag <tag_name> (just push to Acquia)
But as far as I understand the command "deploy" always presuppose artifact building.

What is the preferable way to use BLT tool for the described workflow without double-rebuilding the artifact?

Sorry, if that has been already discussed somewhere, I couldn't find it.
Thank you!

**Comment by danepowell** [comment]
When BLT deploys, it builds the deploy artifact in the directory `<repo-root>/deploy`. That persists after the deploy finishes, so your CI/CD process could just cd into that directory, add a tag, and push.

BLT also has an `artifact:build` command that will build the artifact without doing anything Git-related. However, I wouldn't recommend using this in isolation because there's a lot of fairly subtle Git-fu that needs to happen for deploys to go smoothly, and BLT handles this for you as part of `blt deploy`.

I'm open to the idea of a `--no-rebuild`-type flag for `blt deploy`, but it would be a little complex to implement. I think we'd need to run `blt artifact:build` in a separate directory like `<repo-root>/artifact` and then rsync it into `<repo-root>/deploy`. Conceptually, I do like the idea of further decoupling artifact builds from deploys.

**Comment by dimdiden** [comment]
@danepowell Thanks, really appreciate your response.
`but you'd still need to wait for all of the git checkouts and such to happen twice`
I think that would be perfectly fine.

Just one more thought. At current state, in order to save a deployable artifact somewhere, I need to make sure there is no `deploy` folder (to save some space, since it will be recreated by the next blt deploy run), compress and save whole source project. After that, if I need to deploy it, I'd need to decompress it and run `blt deploy` which does all the mentioned commands.
Ideally, it would be great if I could run `blt build`, save only `deploy` folder as an artifact and have the possibility of running kind of `blt deploy --git-only` just to execute the needed git tasks.

Please share your thoughts on that matter.

**Comment by dimdiden** [comment]
Thanks. So just to conclude:
If I need to save self-deployable artifact, I need to checkout the commit from source repo and compress it. The artifact should contain all folders, including `.git`.
If I need to deploy it, either by tag or by branch, I'll just need to decompress it and run `blt deploy --tag` or  `blt deploy --branch`.

Please let me know whether it is the correct approach from your perspective.

**Comment by danepowell** [comment]
I don't understand what you are asking.

> If I need to save self-deployable artifact, I need to checkout the commit from source repo and compress it. The artifact should contain all folders, including .git.

In the first sentence you talk about the source repo, in the second you talk about the artifact. I don't see how those are connected.

Like I said in my first reply, the `deploy` directory is just a checkout from your artifact repository, presumably on Acquia Cloud. Once you've built a commit for it using BLT, you can just use `git tag` if you want to create a tag, or `git checkout -b` if you want to create a branch. No reason to re-involve BLT if you don't want to.
