### ISSUE TITLE
blt:sync should enable/disable modules and then import configuration.

### ISSUE THREAD

**Issue by carlos-garcia** [acquia/blt#3855]
Hi All, this is my use case scenario, we are using acquia BLT in our project that is hosted with acquia cloud site factory, obviously, the ACSF module is enabled on servers, i'm trying to use blt:sync to sync the database and files from one instance there. the problem is that configuration import if failing because on local, the settings of acsf will not be allowing the configuration import.

So after looking the Robo task, i just flip the tasks for blt:sync. Making drupal:toggle:module be first and then drupal:config:import.

With that, i was able to disable acsf module on local and then the config import was done successfully.

I have a patch here, but i think i made myself clear and this should be the rigth way to do blt:sync

Thanks,
Carlos

[config_sync.txt](https://github.com/acquia/blt/files/3632228/config_sync.txt)

**Comment by mikemadison13** [comment]
Just food for thought, I usually work around this process by writing a database update hook in one of my modules to enable a module. I believe the reason that the toggle modules logic is _after_ the config import, is that if you turn on a module (e.g. seckit) with BLT, then the config import runs, and seckit isn't enabled in the config dump, it will just get disabled again. The BLT process runs after config import so that the config itself won't "undo" what BLT does. I think changing the order of those tasks will cause more trouble for other projects (unfortunately).

Something like the following would work in a module's .install file (assuming that module exists and is already enabled).

```
/**
 * Adding a new module.
 */
function hook_update_8001() {
  \Drupal::service('module_installer')->install(['seckit']);
}
```

**Comment by carlos-garcia** [comment]
Thanks for the answer... however if in this flow im getting errors and the blt sync will not finish because of the errors containing configuration with modules that are not installed. And the script breaks.  If i am doing in the uninstalling first, the  configuration modules are uninstalled along with the configuration and the blt sync script finish ok (with the files synced). Looks like this is a situation of the configuration that you have on the database and depend on which you have on it.. At least i thing is more safe to disable and then importing configuration than the other way...

Thanks for reading!

**Comment by danepowell** [comment]
If you are using core configuration management or config split, I would recommend not using the toggle-modules functionality at all, since it's likely to conflict in one way or another. If you run toggle-modules before config imports, then the config import will just revert any changes made by toggle-modules.

I think you'd be better off managing the ACSF module via config split (specifically "environment splits"), so it only gets enabled in the relevant environments but doesn't get enabled locally. Information on setting up config splits is available here: https://docs.acquia.com/blt/developer/config-split/

If you're determined to proceed with your current approach, your best option would be to override the `sync.commands` variable and insert a call to `drupal:toggle:modules` prior to `drupal:update`.
