### ISSUE TITLE
BLT's default post-install.php ACSF causes error on site installs - is it even needed?

### ISSUE THREAD

**Issue by bkosborne** [acquia/blt#3939]
**Describe the bug**
BLT has a default [post-install ACSF hook](https://github.com/acquia/blt/blob/10.6.0/scripts/factory-hooks/post-install/post-install.php) which causes an error during site installs.

The log output from the task log in ACSF is a bit hard to read, but I pasted relevant parts below with some details obfuscated.

The error is not clear, but the BLT command fails to run and there's a small exception stack trace that seems incomplete.

What I'm confused about is why this post install task if even needed? The file comments indicate it's mean to make sure that the site install process happens in the same way that it does in a local environment. Not sure that is necessary? The script is pretty complicated because it does a lot of "bootstrapping" to determine to correct data to pass to BLT.

**To Reproduce**
Not entirely sure. This was on our recently provisioned ACSF from 2 months ago or so. This is also a codebase that had already been using BLT 10.5.0 with traditional multisite which I'm migrating into ACSF.

**Expected behavior**
The post install hook should work as expected, meaning the BLT task should run successfully.

**Detailed error output**
**One task entry has this:**
> Execute post install hook post-install.php. - The following command is executed synchronously on web-4134.enterprise-g1.hosting.acquia.com: CACHE_PREFIX='/mnt/tmp/obfuscated.01live' \drush8 --root='/mnt/www/html/obfuscated.01live/docroot' -l 'https://briantest.obfuscated.acsitefactory.com' scr --script-path='/mnt/www/html/.01live/factory-hooks/post-install' 'post-install.php'

**And the one following it, which errors out, has this:**

> The post-install hook post-install.php has encountered an error: Completed in 3 seconds. Exit code: 1. Standard out: [33mIn BootstrapHook.php line 32:[39m
> [37;41m                                                                      [39;49m
> [37;41m  [Exception]                                                         [39;49m
> [37;41m  Bootstrap failed. Run your command with -vvv for more information.  [39;49m
> [37;41m                                                                      [39;49m
> 
> [33mException trace:[39m
>   at [32m/mnt/www/html/obfuscated01live/vendor/drush/drush/src/Boot/BootstrapHook.php:32[39m
>  Drush\Boot\BootstrapHook->initialize() at [32m/mnt/www/html/obfuscated01live/vendor/consolidation/annotated-command/src/Hooks/Dispatchers/InitializeHookDispatcher.php:34[39m
>  Consolidation\AnnotatedCommand\Hooks\Dispatchers\InitializeHookDispatcher->callInitializeHook() at [32m/mnt/www/html/obfuscated01live/vendor/consolidation/annotated-command/src/Hooks/Dispatchers/InitializeHookDispatcher.php:27[39m
>  Consolidation\AnnotatedCommand\Hooks\Dispatchers\InitializeHookDispatcher->initialize() at [32m/mnt/www/html/obfuscated01live/vendor/consolidation/annotated-command/src/CommandProcessor.php:145[3...notify] [--xh-link XH-LINK] [--] [39m[32m<command>[39m
> 
> 0.25s total time elapsed.; Standard error: Running updates on: site: obfuscated; env: 01live; db_role: abcd123; name: briantest3;
> Site domain: briantest3.obfuscated.acsitefactory.com;
> Executing: DRUSH_PATHS_CACHE_DIRECTORY='/mnt/tmp/obfuscated.01live/drush_tmp_cache/b37cad7ff608d3ec1cccaa4289b6aa09' '/var/www/html/obfuscated.01live/vendor/bin/blt' drupal:update --environment='01live' --site='briantest3' --define drush.uri='briantest3.obfuscated.acsitefactory.com' --verbose --no-interaction with cache dir /mnt/tmp/obfuscated.01live/drush_tmp_cache/b37cad7ff608d3ec1cccaa4289b6aa09;
> [Acquia\Blt\Robo\Tasks\DrushTask] Running /mnt/www/html/obfuscated01live/vendor/bin/drush @obfuscated.local updb --uri=briantest3.obfuscated.acsitefactory.com --no-interaction -v --ansi in /mnt/www/html/obfuscated01live/docroot
> [Acquia\Blt\Robo\Tasks\DrushTask]  Exit code 1  Time 0.165s
> [error]  Failed to execute database updates!
> For troubleshooting guidance and support, see https://docs.acquia.com/blt/faq/ 
> Command execution returned status code: 1!
>  [error]  Drush command terminated abnormally due to an unrecoverable error.

**BLT doctor output**
Post the full output of `blt doctor` in the failing environment here.

**System information**
* Operating system type: OSX
* Operating system version: 10.14.6
* BLT version: 10.5

**Comment by lcatlett** [comment]
@bkosborne I can't speak to the errors you are having, but to answer your questions about why the the post-install script is necessary: it is primarily needed to support running `blt drupal:update` with a dynamic preferred domain/`--uri` on ACSF, as all drush commands must use a `--uri` when you are working with multisite (and blt commands should use `--site` if using site splits). When a user creates a site on ACSF, you don't necessarily know the site name or preferred domain in advance, or the database name (which ACSF uses as a uuid of sorts that is keyed to the site name and respective domain for each site). The post-install hook also allows you to automate using blt to install the site, including importing config and site splits on site install on ACSF since the db-update factory hook only runs when doing a code release. On ACE you typically have to have a developer install drupal with drush on the cli prior to running blt commands which is not scalable for most ACSF projects. This is the key line: https://github.com/acquia/blt/blob/10.6.0/scripts/factory-hooks/post-install/post-install.php#L74

**Comment by lcatlett** [comment]
@bkosborne - actually in looking at your error message, i think you issue is that you are using the `@obfuscated.local ` drush alias in blt.yml or other blt config file - this should be `self`

**Comment by bkosborne** [comment]
Thanks @lcatlett that's helpful information

**Comment by bkosborne** [comment]
@lcatlett 

> as all drush commands must use a --uri when you are working with multisite

This is true, but the "wrapper" command that executes the post-install.php script is this:

```
CACHE_PREFIX='/mnt/tmp/obfuscated.01live' \drush8 --root='/mnt/www/html/obfuscated.01live/docroot' -l 'https://briantest.obfuscated.acsitefactory.com' scr --script-path='/mnt/www/html/.01live/factory-hooks/post-install' 'post-install.php'
```

The URI is already passed there. Unless you're saying that it's not the primary domain that's passed and that's what you want BLT to use.

Also I guess you may be saying that in order to execute the BLT command within the script, and the BLT command needs the URI, then you need to re-evaluate what the URI should be. Seems like you'd be able to pull it out of the bootstrapped Drupal site though.

**Comment by danepowell** [comment]
I don't see a clear error in that log. You may need to contact the ACSF team via Support to get an untruncated log, so you can see what the error is. The alias might be part of the root cause here.

As to why this script exists, it's because by default ACSF essentially just runs `drush si`, which won't do a lot of things (such as importing default configuration) that BLT would otherwise do for you if you were invoking, say, `blt setup`. Without this, many sites would be in a totally broken state after installs, and would require manual intervention to e.g. sync configuration.
