### ISSUE TITLE
DT-1171: Cannot run Drupal functional tests in Pipelines

### ISSUE THREAD

**Issue by dpagini** [acquia/blt#3993]
**I want to...**
Run Drupal's PHPUnit tests (Kernel, Functional and JavascriptFunctional) on Acquia Pipelines.

**It's not working because...**
I was expecting that #3931 in BLT 11 was going to allow for running PHPUnit tests on Acquia Pipelines. Maybe this is just a bug, but I don't see how this can work...?

Given this code:
https://github.com/acquia/blt/blob/f54c245bc6e360e22568b04111cdbe144f15cdbc/src/Robo/Commands/Tests/DrupalTestCommand.php#L109-L117

When the `drupalTestRunner` is "phpunit" as it is in #3931, the very first thing it does is check for java and exit early if java is not available. 

From #3921: 
>I've tested this on an actual BLT project to ensure that these tests can be run in an OOTB Travis or Pipelines environment (previously they would fail because of the Selenium / Chromedriver dependency).

Maybe this is just referencing the tests at the `tests.phpunit` config key? If that's the case, it's just a little confusing b/c there's sort of 2 ways to run basic PHPUnit tests then, right?

**Comment by danepowell** [comment]
You're right, that's confusing. I looked up the internal test results for #3931, it looks like maybe I only ran root phpunit tests, not Drupal phpunit tests, which would explain the discrepancy.

As long as you are using chromedriver with headless chrome directly (no Selenium), you don't need Java at all any more, do you? In which case the solution would just be to remove the check for Java?

Regarding the two ways to run PHPUnit (for custom tests vs Drupal tests)... yeah, I see why that's confusing. I think they were created separately because Drupal core supports/requires a bunch of environment variables, plus you might want to run core tests independently of other stuff. But if you think there's a case for combining them, can you open a new ticket to start a discussion?

**Comment by dpagini** [comment]
> As long as you are using chromedriver with headless chrome directly (no Selenium), you don't need Java at all any more, do you? In which case the solution would just be to remove the check for Java?

I think this is right? I mean, the code I highlighted should maybe only do that check if selenium is used (_is there a way to determine that?_). 
I'd be happy to help test out a patch for this to confirm if you'd like?

> Regarding the two ways to run PHPUnit (for custom tests vs Drupal tests)... yeah, I see why that's confusing. I think they were created separately because Drupal core supports/requires a bunch of environment variables, plus you might want to run core tests independently of other stuff. But if you think there's a case for combining them, can you open a new ticket to start a discussion?

Yeah, I totally understand the history there, especially around using that test-runner script provided by core. If they're abandoning it, it's probably worth the effort to make BLT's PHPUnit be able to handle all those drupal variables as well. I'll open..

Thanks @danepowell

**Comment by dpagini** [comment]
Thank you @danepowell! 🎉
