### ISSUE TITLE
DT-1166: Drupal Check Incompatibility w/ CI (TTY error on Pipelines)

### ISSUE THREAD

**Issue by mikemadison13** [acquia/blt#3996]
The newest version of drupal-check introduces a new slew of build failures related to TTY output. I have bugged this on the drupal-check side (and it's related to upstream changes in phpstan). 

The output caused by this failure is:
```
In Process.php line 1037:
                                                   
  TTY mode requires /dev/tty to be read/writable. 
```

For the interim, I recommend pinning:
```
"mglaman/drupal-check": "1.0.14"
```

See https://github.com/mglaman/drupal-check/issues/131

**Comment by danepowell** [comment]
I think BLT should just exclude the broken drupal-check version from the version constraint in composer.json as part of the next release (Wednesday).

Something like (I haven't tested this yet):
`"mglaman/drupal-check": ">=1.0.10 <=1.0.14 | ^1.0.15",

**Comment by danepowell** [comment]
Actually didn't mglaman cause us grief due to an unexpected breaking change a few months back as well? Maybe we should just cap the version constraint and not allow updates until we've tested new releases internally. I'm not sure how the burden of bug reports for future breaking changes weighs against support requests from people who want the latest version now.

**Comment by mikemadison13** [comment]
yeah, we've had issues in the past. i like the idea of somehow blocking updates until we know things are stable.

**Comment by hugovk** [comment]
Drupal Check 1.1.1 has now been released with a fix for the Pipelines TTY error:

* https://github.com/mglaman/drupal-check/releases/tag/1.1.1
* https://github.com/mglaman/drupal-check/pull/135
* https://github.com/mglaman/drupal-check/issues/131

Can we revert https://github.com/acquia/blt/pull/4001? The pinning is blocking us from using https://drupal.org/project/upgrade_status. Thanks!

**Comment by danepowell** [comment]
Have you tried using [Composer version aliases](https://getcomposer.org/doc/articles/aliases.md#require-inline-alias)? That's the normal workaround when you want to use a different version of a dependency pinned by an upstream package.

I'd rather not revert #4001 because of all the previous breaking changes in minor and patch releases. I want to keep it pinned for now. But we can investigate bumping to the newer version if it passes testing: https://github.com/acquia/blt/issues/4072
