### ISSUE TITLE
DT-1183: config.platform.php in blt-project prevents installation of packages requiring PHP >7.2

### ISSUE THREAD

**Issue by TravisCarden** [acquia/blt#4003]
https://github.com/acquia/blt/pull/3769 changed `blt-project`'s configuration to make Composer negotiate requirements as if the installed version of PHP were 7.2, regardless of the version actually installed. I understand the motivation, but it's probably a bad practice because it may mask errors off-prod by allowing developers to develop and test locally with a different version of PHP than prod has. But at least as important, it prevents the installation of Composer libraries requiring later versions of PHP... like Drupal 9. Thus this is a D9 readiness blocker and I request that we remove it.

Now it might be argued that this isn't urgent or even necessary since developers can just remove the config from their own implementations. But I would observe that besides the fact that the setting is not well-known and can thus cause difficult to diagnose errors, it will prevent ORCA from installing Drupal 9 and already prevents ORCA users from requiring PHP >7.2 in their own packages.

As to the motivation behind the original change, I have argued that it's a bad idea. But users can always add the configuration themselves. And as it's probably a minority use case, that seems like the more appropriate approach to take. For users who really like bad ideas and want to make their futures selves sorry, I've confirmed that you can set the config globally: `composer config --global platform.php 7.2`. (But seriously, don't do that. Just install the correct version of PHP locally. If you need to switch between versions for different projects and you're using Homebrew on Mac, use [Brew PHP Switcher](https://github.com/philcook/brew-php-switcher).)

**Comment by danepowell** [comment]
While I accept that this config might seem like a hack, and we certainly need to unblock D9, I think you underestimate the scale of the problem (and associated support requests) caused by mismatched PHP versions. We were absolutely swamped with people who had e.g. installed PHP 7 packages locally only to see deployments to their PHP 5 environments crash unexpectedly. Adding this config virtually eliminated those issues, and yours is the first case I've seen of anyone having a problem with enforcing the PHP version.

From the BLT perspective, the preferred solution to D9 compatibility would be to bump all dependencies (including the PHP version constraint and `drupal/core-recommended`) in June to coincide with the stable release of Drupal 9. This would allow new BLT Projects to be created with Drupal 9. I'm reluctant to bump the version any sooner, since that would block people from creating Drupal 8 projects with PHP 7.2 (which should be a supported combination). Note that the PHP version constraint isn't even the biggest blocker here, since the BLT template project explicitly requires Drupal 8.

In the interim, the advice I'd give to customers wanting to try Drupal 9 would be to manually bump the PHP constraint (as well as the core version itself) in the template composer.json to support Drupal 9. In which case, ORCA should do the same.

Note that all of this discussion only affects _new_ projects created using the BLT Project template. It doesn't affect BLT being added (or upgraded) with existing projects. Also, for what it's worth, the intended workflow is for projects to continually update this config to match their production environment.

**Comment by danepowell** [comment]
Another option (albeit not a quick fix) is to ditch BLT Project entirely. As a short-term step towards that, maybe this composer option could be added dynamically when BLT is installed in a way that ORCA can disable (or not added at all, and only suggested).

**Comment by wimleers** [comment]
FYI: in the case of https://github.com/acquia/acquia_migrate/pull/22, this is wholly unrelated to Drupal 9. (That's also where this problem was originally discovered — thanks to @TravisCarden for tracing the root cause to here.)

**Comment by TravisCarden** [comment]
@danepowell #4010 would solve this problem for ORCA, though I don't see how it solves the #3769 use case. Not that I'll argue if it unblocks me. ¯\_(ツ)_/¯

**Comment by danepowell** [comment]
If I understand correctly, you are saying that enforcing the project PHP version based on wherever BLT was initially installed is slightly less safe than setting it to some safe PHP version for _all_ BLT projects, because in general people run newer versions of PHP locally than they might in production.

I agree that's a risk, but as I mentioned above, the only alternative to unblock ORCA is to keep the php constraint in the project template and ORCA should manually change it if necessary (as that is what we would instruct customers to do). Let me know if you prefer this.

**Comment by TravisCarden** [comment]
As long as the potential risk is on your radar and you consciously accept it, @danepowell, I have no issue with it (indeed, essentially no stake in it). I appreciate your readiness to unblock ORCA. Please proceed.

**Comment by danepowell** [comment]
I maintain that using this config is best practice. But we can't set it dynamically, and we can't set it statically in way that's cross-compatible with Drupal 8 (with PHP 7.2) and Drupal 9.

The best solution I see is to start the BLT and BLT Project 12.x branches, and make them just support Drupal 9. See #4023
