### ISSUE TITLE
DT-1196: Permission denied error on Drush cache directory during cloud hook.

### ISSUE THREAD

**Issue by richardbporter** [acquia/blt#4009]
**Describe the bug**
We're getting the following error during a post-code-update cloud hook:
```
> drupal:update
[Acquia\Blt\Robo\Tasks\DrushTask] Running /var/www/html/foo02.dev/vendor/bin/drush @self updb --uri=mysite.com --no-interaction -v in /var/www/html/foo02.dev/docroot
 [preflight] Failed to create "/tmp/.drush/dev/factory": mkdir(): Permission denied.
 [warning] Drush command terminated abnormally. Check for an exit() in your Drupal site.
[Acquia\Blt\Robo\Tasks\DrushTask]  Exit code 1  Time 0.311s
```

**To Reproduce**
Run `blt recipes:cloud-hooks:init` in a BLT 11.x project. Push code to the dev environments for two applications on the same hardware. Since the Drush cache is not scoped by user first, only one user has write permissions to `/tmp/.drush`.

**Expected behavior**
I would expect Drush to be able to read/write from the DRUSH_PATHS_CACHE_DIRECTORY environment variable regardless of user executing the BLT/Drush commands.

**System information**
* Operating system type: Acquia Cloud
* BLT version: 11.1.0    

**Additional context**
Acquia Support ticket 901585.

**Comment by richardbporter** [comment]
It doesn't look like `export DRUSH_PATHS_CACHE_DIRECTORY=/tmp/.drush/${target_env}` is in the post-code-update/deploy hooks anymore: https://github.com/acquia/blt/blob/11.x/scripts/cloud-hooks/hooks/common/post-code-update/post-code-update.sh 

Is this supposed to be removed?

**Comment by richardbporter** [comment]
Removing that export statement in existing cloud hooks seems to resolve the issue.

**Comment by richardbporter** [comment]
Actually, that only solves it one application but now the other has the same error. I'll try adding that export statement back scoped by site, e.g. `export DRUSH_PATHS_CACHE_DIRECTORY=/tmp/.drush/${site}/${target_env}`.

**Comment by danepowell** [comment]
Thanks for the report. This hasn't anything to do with write permissions, it's actually a race condition due to bugs with the Symfony filesystem handler. See this issue for context: https://github.com/acquia/blt/pull/2922

Ideally we could modify the Drush handler to isolate tasks per site, irrespective of the context (i.e. Cloud Hooks or not). Otherwise just implement your suggestion, which will fix the use case of multiple applications on the same hardware, but not multiple sites in the same environment.

**Comment by richardbporter** [comment]
>Ideally we could modify the Drush handler to isolate tasks per site

Do you know of a way to do that on Acquia Cloud? Or if its possible to disable this cache entirely? We're running into other edge cases when `drush cron` or some other scheduled Drush task is running.

**Comment by danepowell** [comment]
The problem with solving this in a generic way is that you (a) have to know which context (site) a given Drush request is operating under, and (b) set an environment variable according to that context. BLT can do (b) pretty easily because we have a custom Drush task, but we'd still need to ensure that we understand the site context even when it's not explicitly set.

It would be harder to do generically on Acquia Cloud because anyone can run Drush from the CLI, and there's no way to vary the cache directory per-request.

You could disable it by setting the cache dir to `/dev/null`. Obviously that might have performance implications. See https://github.com/drush-ops/drush/issues/3592

**Comment by danepowell** [comment]
Hmm, alternatively, since this is 90% a problem during Cloud Hook and ACSF hook execution, we could just set DRUSH_PATHS_CACHE_DIRECTORY to something unique in the Cloud Hook like we do for ACSF hooks. That's something Cloud / ACSF could do independently of BLT, which I'll pass along.

**Comment by richardbporter** [comment]
I was going to try adding a `drush.yml` file to each multisite directory with the following contents:
```
drush:
  paths:
    cache-directory: /tmp/.drush/${env.AH_SITE_GROUP}/${env.AH_SITE_ENVIRONMENT}/mysite.com
```

However, that config file doesn't seem to be loading. Probably related to https://github.com/drush-ops/drush/issues/4324.

**Comment by richardbporter** [comment]
Another potential workaround I tried was using `putenv("DRUSH_PATHS_CACHE_DIRECTORY=...` before each multisite runs the `drupal:update` process. Unfortunately, that doesn't seem to carry down to the Drush child process.

**Comment by richardbporter** [comment]
>Ideally we could modify the Drush handler to isolate tasks per site, irrespective of the context 

If I understand correctly, https://github.com/drush-ops/drush/pull/4345 in some form, would do that. But will that mitigate multiple Drush processes for the same site running simultaneously? Ex. cron and a cloud hook. I'm thinking no.

If not, would you be open to adding opt-in config, `drush.cache-isolate` or something, that adds a `drush.paths.cache-directory=$tmpRandom` option to `TaskDrush`?

**Comment by rmuit** [comment]
Ex ACSF person here. I was just digesting this Drush cache thing around April 1 when my contract ended so I can't comment internally here anymore. Will use this issue to refine my thoughts a bit...

> It doesn't look like export DRUSH_PATHS_CACHE_DIRECTORY=/tmp/.drush/${target_env} is in the post-code-update/deploy hooks anymore

Was it ever there? Sorry I don't know BLT on Cloud/ACE. But I can't see it in git history.

I'm curious where this /tmp/.drush/${target_env} was set, so I don't make any further wrong statements. (I think I already did, in an Acquia-internal PF ticket.) I don't see this showing up anywhere in the 'sandboxy' ACE environment I'm checking.

If this was a modification (to get the Drush cache out of ~/.drush) made by your own organization then I agree that the solution is to add $site (sitegroup, application, whatever the name is) to the path.
 
And if DRUSH_PATHS_CACHE_DIRECTORY is set somewhere in BLT or by Acquia Cloud before they execute post-code-* hooks... then I agree they should be ading the AH_SITE_GROUP environment variable as a path component. From your issue report, it sounds like your diagnosis is correct: _your_ reported issue is not a race condition, but the fact that two different unix users are trying to write to the same cache. You might have an unconventional hardware setup for this aplication? (It may not happen often that multiple applications share the same setup - so most customers will never have any clashes if they forget to differentiate the cache path per application == unix user.)

...but actually...

I suspect that path can still give issues because only one unix user is allowed to create 
/tmp/.drush and write to it. scripts/blt/drush/cache.php takes /mnt/tmp/{$site}.{$target_env}/drush_tmp_cache, which should be problem free.

Further:

* I agree that the 'right' solution is for Cloud/ACSF to set this environment variable so that applications like BLT don't need to think of implementing drush workarounds. (Sorry Dane, it took me quite a while to get to that understanding :) An ACSF ticket is open now as a starting point to get this done.)

* ...but if BLT wants to fix this for customers and accepts that it is somehow in a position to move much faster than Acquia Cloud engineering is, to fix this... it may still be a good idea to set DRUSH_PATHS_CACHE_DIRECTORY in these default cloud hooks just like it's done in factory hooks currently. (Although I'm not completely sure what the actual issue is we'd be solving, because I don't know what the current default value is.)


>>  ... isolate tasks per site, irrespective of the context (i.e. Cloud Hooks or not). 

> ...will that mitigate multiple Drush processes for the same site running simultaneously? Ex. cron and a cloud hook. I'm thinking no.

I'm also thinking no.

Just sharing what I currently understand the issue to be:

* Disclaimer: I don't understand how the drush.yml discussion is connected to this cache discussion.

* I do not know if the Drush cache has any issues getting polluted by multisite setups, like e.g. if info from modules in one sites/.../modules directory gets cached, it influences execution for other sites in the same docroot. I _am assuming_ there are no cache pollution issues because Drush' multisite support is mature enough / am not aware of bug reports stating otherwise.

* If the above assumption is true, then there is no intrinsic reason for having a per-site 'context'. AFAICT the _only_ reason for having multiple contexts is preventing concurrent execution of drush commands using the same cache directory. On ACSF, we have per-site factory hooks which can be executed concurrently, so as a result, a separate directory per site _happens to be_ the easiest solution for avoiding concurrency issues re. the drush cache. I'm not sure that this is the case on ACE (by default), so we wouldn't need to look at creating a per-site context on 'regular' cloud hooks.

* The one thing we are trying to prevent is having a 'drush cc drush' or 'drush cr' run at the same time with the same directory as _any other_ drush command. (Because cr/cc drush are the only commands that remove (files from) the cache directory, and can exit non-zero if that fails. Any drush command writes files to the cache if they don't exist yet, and can therefore mess with those cache clears.)

* Creating many more different 'contexts / cache directories' than we need, is not very practical because 1) it defeats the purpose of having a cache 2) we would need to make sure that all these cache directories are emptied, each time new code is deployed. (Changing code in the docroot can make the cache go stale which can cause errors when running drush.)

So, what should we (we == a collection of cloud hook scripts, possibly managed by BLT) do to prevent concurrent execution? I'm thinking:

* Anything running on cron, or scripts run by the user, we cannot influence or make assumptions about. (But let's assume that whatever it does, it will have to figure out the concurrency issue by itself. We cannot help it. In practice the most likely situation is that all of those commands use ~/.drush/cache if Cloud doesn't set it to anything else. Which (I hope?) somehow gets refreshed on a new code deploy, independently of us.)

* The only thing we need to do to prevent 'cache clashes' is... use a different cache from the default, so that all those commands cannot break our cache clears, and we cannot break 'their' cache clears by running random drush commands at the same time.

* If we can assume that no cloud hook scripts run concurrently (can we?), and if we ourselves don't do anything advanced that executes concurrent drush processes... then we only need one cache directory / 'context'. Whatever it is. (To be precise: one for a given application+environment.)

/mnt/tmp/{$site}.{$target_env}/drush_tmp_cache could be good, but if you want to be clearer about "other scripts please do not use this", you could use /mnt/tmp/{$site}.{$target_env}/blt_drush_cache or /mnt/tmp/{$site}.{$target_env}/cloudhooks_drush_cache to specify the 'owner'.

Since it is "our" context, we need to make sure that 
* the directory exists (mkdir -p) before using it, 
* it's emptied when new code gets deployed
* (...and if we have very many contexts like ACSF does which creates a directory per site, we should likely clean it up after using it, because it could waste disk space. But if we have just one or a couple of cache directories, we likely don't need to do that / it might be useful to keep using the same already-populated cache directory.)

That's all.

So, circling back / condensed conclusion:

A 'context' is a 'space where we can be sure that no Drush cache clear is running at the same time as another command'.

> Ideally we could modify the Drush handler to isolate tasks per site, irrespective of the context (i.e. Cloud Hooks or not). Otherwise just implement your suggestion, which will fix the use case of multiple applications on the same hardware, but not multiple sites in the same environment.

I'm no ACE expert but I'm assuming Cloud Hooks don't run concurrently / don't run concurrent drush commands by default. If that's the case, and assuming the Drush cache itself can work fine with multisite setups... the suggestion provided by @richardbporter is exactly what we need by default. It adds _one_ extra context "only for Cloud Hooks", which is a good solution (until custom Cloud Hooks start doing freaky stuff, at which time they will need to do their own separate-contexts thing). Whereas a per-site context _irrespective of_ "Cloud Hooks or not", is not water tight.

**Comment by rmuit** [comment]
Also, silly 'newbie' question: do post-code-* hooks run on _every_ web? Otherwise the "is emptied when new code gets deployed" part is... harder.

**Comment by danepowell** [comment]
I appreciate everyone's input on this discussion. I do not believe this feature is a good fit for BLT. This needs to be solved in Acquia Cloud so that all customers can take advantage of it, not just BLT users.

If any individuals want to work around this issue in the meantime, I'd suggest copying the approach used in the ACSF factory hooks of setting `DRUSH_PATHS_CACHE_DIRECTORY`. Cloud Hooks can be freely modified, nothing in BLT will block you.

If you are an Acquia customer and this issue affects you, please submit a support ticket or contact your TAM and tell them you have product feedback for Acquia Cloud, and optionally post the ZD ticket here (@richardbporter I've already captured your information, thanks). This will ensure that the most attention gets paid to this issue.
