### ISSUE TITLE
entity_reference_revisions field type issue while Drupal BLT setup

### ISSUE THREAD

**Issue by sourabh-cohaesus** [acquia/blt#4014]
**Describe the bug**
We are getting some error related to 'entity_reference_revisions' field type while setting a Drupal using BLT.

**To Reproduce**
Steps to reproduce the behaviour
1. We have set up the Drupal using BLT. [Ref Article](https://docs.acquia.com/blt/install/creating-new-project/) 
2. Install the [paragraphs](https://www.drupal.org/project/paragraphs) module.
3. Create paragraphs in the CMS and attach paragraphs on content type using entity reference revisions type field.
4. Export the DB configurations using `drush cex` command.
5. Push all the changes in the git repository including composer.json
5. After this, set up the project on some other system.
6. while executing the command 'blt setup' on the Linux system, we are getting below error

```
In FieldConfigStorageBase.php line 31:`
  Unable to determine class for field type 'entity_reference_revisions' found  
   in the 'field.field.node.landing_page.field_content_blocks' configuration   

In DiscoveryTrait.php line 53:
  The "entity_reference_revisions" plugin does not exist. Valid plugin IDs fo  
  r Drupal\Core\Field\FieldTypePluginManager are: contact_storage_options_ema  
  il, datetime, file_uri, file, image, layout_section, link, metatag, list_fl  
  oat, list_integer, list_string, path, redirect_source, text_long, text, tex  
  t_with_summary, video_embed_field, uuid, password, map, integer, string_lon  
  g, email, float, uri, entity_reference, decimal, language, boolean, created  
  , string, timestamp, changed
```

7. The same error will occur when running `blt drupal:install -n -vvvblt drupal:install -n -vvv` command so it may be Drupal install error.

**Additional context**
Below are the steps which will resolve it.
1. Run `blt doctor`
2. Clear cache using `drush cr`

After running above commands the site will be running fine but we are not sure what is the issue and why it is occurring.

**BLT doctor output**
vagrant@local:/var/www/drupal-blt$ blt doctor
Below is the output of blt doctor
```
+--------------------------------------+--------------------------------------------------------------+
| Check                                | Problem                                                      |
+--------------------------------------+--------------------------------------------------------------+
| ConfigCheck:checkGitConfig           | Git repositories are not defined in blt.yml.                 |
|                                      |   Add values for git.remotes to blt.yml to enabled automated |
|                                      | deployment.                                                  |
| NodeCheck:checkNodeVersionFileExists | Neither .nvmrc nor .node-version file found in repo root.    |
+--------------------------------------+--------------------------------------------------------------+
```

**System information**
* Operating system type: Linux (Ubuntu)
* Operating system version: Ubuntu 16.04.6 LTS
* BLT version: 11.1.0

**Comment by alanoakden** [comment]
Seeing this too BLT version 11.2.0, Drupal 8.8.2 , Ubuntu 18.04  (drupal-vm box) using a 'standard' BLT install profile

**Comment by danepowell** [comment]
This seems like a problem with your configuration export, and not anything specific to BLT. Running the `drush` commands completely absent of BLT will result in the same error.

It's hard to say why your configuration export would be corrupt. It could be due to a bug with Paragraphs, or a problem with how you exported config. Have you confirmed that entity reference revisions (the module) exists in your codebase when you are attempting to reinstall, and that it gets installed prior to the import happening?

**Comment by sourabh-cohaesus** [comment]
Hi Dane

We have already checked that the entity reference module is exists in the codebase and the `drush` command is also working of the BLT setup.

When we install the paragraph module with the non-BLT environment then the import-export is working fine. Also when we remove the paragraph module from the BLT environment then there is no issue in the import-export so maybe there is some issue in the BLT setup with paragraph module.

**Comment by lpeabody** [comment]
What happens if you clear the discovery cache bin?

**Comment by sourabh-cohaesus** [comment]
We have truncated the 'cache_discovery' table and then exported the configuration. After that, we have again run the 'blt setup' command but still, we are getting same error.

**Comment by danepowell** [comment]
> maybe there is some issue in the BLT setup with paragraph module

BLT doesn't do any sort of setup related to individual modules. It only runs other commands (primarily Drush commands) to assist in installing your site and importing configuration.

In this case, it sounds like if you were to run the same Drush commands that BLT does (as shown by `blt drupal:install -n -vvv`), completely outside of BLT, you would get the exact same errors, because there's something wrong with how Paragraphs is exporting its configuration.

Unfortunately I can't reproduce this given the available information, which makes it impossible to troubleshoot. I'd encourage you to open an Acquia Support ticket (support.acquia.com) if you need additional help debugging the Paragraphs module.
