### ISSUE TITLE
Unexclude the NamespacedDependency sniff.

### ISSUE THREAD

**Issue by dpagini** [acquia/blt#4024]
Thought it might be appropriate to revisit #2295.

It's a bit odd to ignore this one single code sniff. Obviously BLT projects have the ability to add this if they desire, or any other code sniff, so maybe we should not exclude it by default.

Several of the reasons given 2 years ago have been addressed in Core.

This isn't really blocking anything for me, b/c I can just exclude the BLT default. Just thought I would raise it.

**Comment by danepowell** [comment]
Can you elaborate on what specifically has changed in the last couple years? I haven't followed the changes related to this particular sniff in core, but all of the justifications provided in #2295 still sound valid to me.

Tangentially, I wonder if we should switch to using https://github.com/acquia/coding-standards-php rather than using the Drupal/DrupalPractice rulesets as a base and making our own judgement calls about which sniffs to include.

**Comment by danepowell** [comment]
Will be fixed if we switch to using Acquia Coding Standards in 12.x: https://github.com/acquia/blt/pull/4045

**Comment by dpagini** [comment]
Just to respond back, going back to the original issue, a few comments below. It just seems odd that it's the 1 sniff that BLT decides to ignore. 

> Core does not do namespacing, currently. e.g. [...]

All of core does namespacing now, as far as I can tell.

> The practice is recommended, rather than required, and only for contrib modules. 

Agreed, but it's not only for contrib, see previous answer.
