### ISSUE TITLE
BLT (DrupalVM) solr config should match Acquia search solr instances when developing locally.

### ISSUE THREAD

**Issue by bhasselbeck** [acquia/blt#412]
Acquia Search solr instances have extra libraries that aren't included with "vanilla" Solr included in DrupalVM.  We should identify those libraries and ensure that Solr is set up to match Acquia Cloud's Solr instances as best as possible for local development.

I believe that an extra script should be included in BLT instead of DrupalVM (though it could be optional in DrupalVM) to configure Solr to match Acquia's instances.

**Comment by damontgomery** [comment]
See reference from @geerlingguy, https://github.com/geerlingguy/ansible-role-solr and Drupal VM example, https://github.com/geerlingguy/drupal-vm/blob/master/examples/scripts/configure-solr.sh

To add this to Drupal VM, you can include this in `config.yml` for Drupal VM,

```
 post_provision_scripts:
  - "../examples/scripts/configure-solr.sh"
```

**Comment by lcatlett** [comment]
that script downloads search_api_solr-8.x-1.x-dev.tar.gz which will break testing search locally. It should use search_api_solr-8.x-1.0-alpha3.tar.gz to work with the recommended Acquia Search modules.

**Comment by geerlingguy** [comment]
@lcatlett - Note that the script linked in the comment above is intended for a general audience (most of whom would be using a later version of the Search API Solr module, since they will likely run Solr 5, Solr 6, and wouldn't be on Acquia Cloud).

For BLT's purposes, if targeting Acquia Cloud / Acquia Search specifically, BLT would need to provide it's own script to target the specific version of the Search API Solr module it would like to use.

For Drupal VM, I would rather stick with the -dev release as the script provided is just an example that end users are supposed to customize and make work for their particular use case.

**Comment by geerlingguy** [comment]
Also note that the default Drupal VM config has `solr_version: "5.5.2"` (see: https://github.com/geerlingguy/drupal-vm/blob/master/default.config.yml#L289). This is because that's the latest version that's currently supported by all the Solr modules for Drupal 7 and 8 (though Solr 6 support should be coming to the Drupal 7 modules soon).

So BLT needs to make sure to specify a 4.x version, e.g. by setting this in config.yml:

```yaml
solr_version: "4.5.1"
```

See recommended Acquia Cloud overrides here: https://github.com/geerlingguy/drupal-vm/blob/master/examples/acquia/acquia.config.yml

(Note also that there's no way I'd recommend Solr 3.5—the current default for new Acquia subs—for any Drupal 8 sites... or really any sites. Please make sure to file a support ticket to update to 4.5.x, and also cross your fingers for newer supported versions soon—4.x has not seen any updates in a couple years now, and even 5.x is no longer supported much).

**Comment by damontgomery** [comment]
@lcatlett,

The internal Search page has the script Jeff put together for one of our projects. That can be used as an example as well.

**Comment by bhasselbeck** [comment]
@janusman can you please follow this thread to ensure that we are marking new libraries correctly?
