### ISSUE TITLE
11.x Drupal 9 Support

### ISSUE THREAD

**Issue by aweingarten** [acquia/blt#4139]
**Is your feature request related to a problem? Please describe.**
I am trying to install Drupal 9 using BLT 11 and I cannot due to the composer dependency of BLT on Symfony 3.x..  Requesting a new release of BLT with updated composer dependencies to allow us to prepare for D9.

```
  Problem 1
    - The requested package acquia/blt (locked at 11.4.1, required as 11.x-dev) is satisfiable by acquia/blt[11.4.1] but these conflict with your requirements or minimum-stability.
  Problem 2
    - drupal/core-recommended 9.0.0-beta2 requires symfony/yaml v4.4.7 -> satisfiable by symfony/yaml[v4.4.7].
    - drupal/core-recommended 9.0.x-dev requires symfony/yaml v4.4.7 -> satisfiable by symfony/yaml[v4.4.7].
    - drupal/core-recommended 9.1.x-dev requires symfony/yaml v4.4.7 -> satisfiable by symfony/yaml[v4.4.7].
    - Conclusion: don't install symfony/yaml v4.4.7
    - Installation request for acquia/blt 11.x-dev -> satisfiable by acquia/blt[11.x-dev].
    - drupal/core-recommended 9.0.0-beta1 requires symfony/yaml v4.4.5 -> satisfiable by symfony/yaml[v4.4.5].
    - Conclusion: don't install symfony/yaml v4.4.5
    - drupal/core-recommended 9.0.0-alpha2 requires symfony/yaml v4.4.4 -> satisfiable by symfony/yaml[v4.4.4].
    - Conclusion: don't install symfony/yaml v4.4.4
    - acquia/blt 11.x-dev requires symfony/yaml ^3.2.8 -> satisfiable by symfony/yaml[v3.4.35, 3.4.x-dev, v3.4.1, v3.4.10, v3.4.11, v3.4.12, v3.4.13, v3.4.14, v3.4.15, v3.4.16, v3.4.17, v3.4.18, v3.4.19, v3.4.2, v3.4.20, v3.4.21, v3.4.22, v3.4.23, v3.4.24, v3.4.25, v3.4.26, v3.4.27, v3.4.28, v3.4.29, v3.4.3, v3.4.30, v3.4.31, v3.4.32, v3.4.33, v3.4.34, v3.4.36, v3.4.37, v3.4.38, v3.4.39, v3.4.4, v3.4.5, v3.4.6, v3.4.7, v3.4.8, v3.4.9].
```

**Describe the solution you'd like**
A new version of BLT 11 that supports Drupal 9.  

**Describe alternatives you've considered**
Looked into trying BLT 12 but its in a HIGHLY experimental state at the moment.

**Comment by danepowell** [comment]
Sorry, it is not feasible to add Drupal 9 support to BLT 11.x. There are too many dependency conflicts that are mutually exclusive between Drupal 8 and Drupal 9. We have solved this in part in BLT 12 by removing some of the conflicting functionality (i.e. Behat), but since that's a breaking change for many users we cannot do the same for BLT 11.

BLT 12 is indeed unstable but we are pushing for an alpha release in the next few days, and a beta shortly thereafter. We plan to have a stable release to coincide with Drupal 9.
