### ISSUE TITLE
Acquia BLT setup on windows machine

### ISSUE THREAD

**Issue by manerkargaurav** [acquia/blt#4208]
Hello,

I need documentation on how to setup acquia blt on windows machine.

**Comment by danepowell** [comment]
Hi Gaurav, did you follow the documentation link from the homepage? The Windows install instructions are on the same page as the instructions for other OSes: https://docs.acquia.com/blt/install/

Note that because Windows is somewhat problematic as a Drupal development environment, it also has a dedicated page: https://docs.acquia.com/blt/install/windows-install/
