### ISSUE TITLE
BLT alias doesn't correctly detect the IDE

### ISSUE THREAD

**Issue by anavarre** [acquia/blt#4211]
In Cloud IDE, when you install the BLT alias, the env var isn't correct.

```
ide:~$ echo $PROJECT_ROOT
/var/www/html/sitegroup.IDE
```

The project root is always `/home/ide/project`

**Comment by danepowell** [comment]
@anavarre we should solve this and https://github.com/acquia/drupal-environment-detector/issues/5 together, let's discuss on grooming tomorrow

These problems both exist because IDEs "claim" to be an Acquia hosting environment, but don't follow many of the Acquia hosting standards when it comes to file locations. If we fix this in BLT and the Environment Detector, customers may end up playing wack-a-mole when it arises elsewhere in their application. It might be better to instead fix it in IDEs (by moving files or adding symlinks to match Acquia Cloud).

**Comment by danepowell** [comment]
I think the outcome of this discussion, per scrum, was to make Cloud IDEs behave more like Cloud hosting, rather than adapt BLT and Environment Detector to treat IDEs as a special case.

**Comment by danepowell** [comment]
This is pending release on the IDE side

**Comment by anavarre** [comment]
This was released.
