### ISSUE TITLE
Enhance BLT sync to take latest db backup rather than creating a new db export

### ISSUE THREAD

**Issue by gareth-cohaesus** [acquia/blt#4241]
When I run BLT Sync, a new database export is triggered on Acquia Cloud. Often I don't need the most up to date version, but a recent backup version will suffice.

I would like to be able to add a variable to grab the latest backup file rather than creating a new db export.

Currently I have a bash script that grabs the news file in the database backup location and will then scp the file locally, but it would be better if I could factor that in with the sanitisation and other features that blt:sync offers.

**Comment by danepowell** [comment]
I doubt this is possible within BLT because BLT relies on Drush to handle these commands, and Drush won't have any awareness of Cloud-specific features like DB backups. The best alternative is to download the file yourself and import it using the static import option in BLT, or use a hook to automatically retrieve said dump prior to import.

**Comment by lpeabody** [comment]
Drush does actually support referencing a hosted dump file on the sync source. I had previously written an alternative BLT command that does basically everything the current BLT sync command does, only it adds an option to the Drush task specifying the dump file. Using this, ~once a week I would dump all the test databases to the Acquia server pointed to by the pertinent source Drush alias, and every database sync operation in CI would just grab that file instead of dumping each individual database every time.

I suppose this is why you invented BLT plugin :) I have a backlog of contributions... Anyway, just wanted to shine a light on that and point out it is possible to do something like this.

**Comment by gareth-cohaesus** [comment]
Thanks for responding. I'll look into a custom Plugin to complete the task.
