### ISSUE TITLE
Problem creating settings on existing D9 installation

### ISSUE THREAD

**Issue by iainp999** [acquia/blt#4266]
**Describe the bug**
I installed BLT to an existing D9 codebase using the instructions provided for adding to an existing install.

When I tried to generate my settings file using BLT, I received the error below.

For info, I'm using Lando.

**To Reproduce**
- Install BLT to an existing D9 site using instructions for composer.
- Run `blt setup:settings`
- Error that `example.local.blt.yml` is missing.

**Expected behavior**

**Detailed error output**
```
[debug] Drupal VM is not initialized.
Could not find blt/example.local.blt.yml/. Create and commit this file if you'd like to automatically generate blt/local.blt.yml/ based on this template.
Hash salt already exists.
[debug] Multisites found: default
[debug] Initial site: default
[Filesystem\FilesystemStack] _chmod ["<path>/docroot/sites/default",511]
[Filesystem\FilesystemStack] _chmod ["<path>/docroot/sites/default/settings.php",511]
[File\Write] Writing to <path>/docroot/sites/default/settings.php.
[Filesystem\FilesystemStack] _chmod ["<path>/docroot/sites/default/settings.php",420]
0.238s total time elapsed.
```

`<path>` is valid, I removed the actual path from the output above.

**System information**
* Operating system type: MacOS
* Operating system version: Darwin
* BLT version: 12.3.0

**Comment by mikemadison13** [comment]
FYI i dug around and I don't actually see the example.local.blt.yml file in the codebase anymore, I'm wondering if that's related?

**Comment by mikemadison13** [comment]
this could be related to https://github.com/acquia/blt/issues/4231 btw

**Comment by danepowell** [comment]
This is not an error or bug, it's just a friendly notice and by design: https://github.com/acquia/blt/pull/4239

Not everyone needs a local config file so we don't provide one any more. This notice just brings visibility for users who might not be aware of this functionality, or might not be aware that it's changed from BLT 11.

The template we used to provide in BLT 11.x was empty anyway, so it's not like restoring it would add any functionality: https://github.com/acquia/blt-project/blob/11.x/blt/example.local.blt.yml

This only change I can think of would be to link to that example file, would that be helpful?
