### ISSUE TITLE
issues in Git

### ISSUE THREAD

**Issue by MoHalawa819** [acquia/blt#4289]
hello there 
iam new in **Git** and have problem when iam trying to add files to stage area by command 
**git add index.html**
the error is
**fatal: pathspec 'index.html' did not match any files**
plz help me

**Comment by danepowell** [comment]
I would suggest searching for your issue, this post seems relevant: https://stackoverflow.com/questions/20188229/fatal-pathspec-file-txt-did-not-match-any-files-git

If you are an Acquia customer, please open a support ticket, as the support team will be better equipped to help with general Git usage.

I'm going to close this ticket since it doesn't seem to be specific to BLT or Drupal (neither of which would use index.html).
