### ISSUE TITLE
Build artifact with APCU autoloader.

### ISSUE THREAD

**Issue by dpagini** [acquia/blt#4290]
**Is your feature request related to a problem? Please describe.**
Given [this CR](https://www.drupal.org/node/3020296) in Drupal core, I am wondering if BLT should ship a deployment artifact with the APCU autoloader flag, which Drupal will then take advantage of by default...?
Honestly, this is all a bit over my head, but it seems like given the change above, if that APCU autoloader data is present, Drupal will use it and gain a performance benefit from it.

**Describe the solution you'd like**
I'm thinking DeployCommand needs to call composer with `$ composer install --apcu-autoloader`.

**Describe alternatives you've considered**
None?

**Comment by danepowell** [comment]
My reading of the [change record](https://www.drupal.org/node/3116384) is that BLT 12 is already doing this correctly for Drupal 9, and no action is required:

> Previously, to use composer's APCu optimised classloader you would run composer install with the --apcu-autoloader and add the $settings['class_loader_auto_detect'] = FALSE; to your settings.php. **This is no longer necessary and can be removed**.

Maybe for Drupal 8 there's an optimization here, but if so it must be a small one as I've never seen issues related to the autoloader. Am I missing something?

**Comment by dpagini** [comment]
So I guess I was reading it differently, but I definitely see what you're saying...

Seems like D9 is now going to use the composer class loader, instead of building their own (?), and then storing that class loader in APCu cache?

>  The default behaviour is still to use APCu to cache class locations.

So that led me to the question... would the `--apcu-autoloader` flag offer any additional benefit?

This is all for sure a bit over my head though, so feel free to close if you think this isn't needed/relevant.

**Comment by danepowell** [comment]
Hmm you might be right, on second reading that change record is a bit ambiguous. You might still need to pass the apcu-autoloader flag to take advantage of it.

- https://www.drupal.org/project/drupal/issues/3020296#comment-13935826
- https://getcomposer.org/doc/articles/autoloader-optimization.md

I think the potential benefit here is small, since the "level 1" autoloader optimizations will be opcached and I don't think apcu would be any faster, but I'd be interested to see if anyone has benchmarks on a real site. I'd also be concerned about consuming too much APCu memory, which is already constrained in some circumstances (multisite/acsf).

**Comment by danepowell** [comment]
Closing since we don't have enough information to demonstrate a significant improvement here. Feel free to reopen if any has additional information or benchmarks.
