### ISSUE TITLE
BLT 12 assumes Config Split but does not ship Config Split

### ISSUE THREAD

**Issue by mikemadison13** [acquia/blt#4300]
**Describe the bug**
BLT 12's default CM strategy is using the config split module. However, the new drupal-recommended-project repo doesn't have a dependency in composer for config split. The result is this bug.

**To Reproduce**
Steps to reproduce the behavior, ideally starting from a fresh install of BLT:
1. Run blt setup
2. Run drush cex 
3. Re-run blt setup (config will run this time)

**Expected behavior**
Config split should work out of the box.

**Detailed error output**
```
In PmCommands.php line 253:
                                                                               
  Unable to install modules config_split due to missing modules config_split.  
                                                                               
```

**System information**
* Operating system type: Mac OS
* Operating system version: 10.15.7
* BLT version: 12.4.0

**Additional context**
This used to be in blt-project so it wasn't an issue in BLT 11.

**Comment by lpeabody** [comment]
In addition to my feedback on the PR earlier, I just want to throw out a few suggestions that keeps BLT as flexible as possible without adding more dependencies that you have to maintain the permissible versions for over time:

1. If the `config-split` strategy is in use, do a check using composer to see if the library is included, and if it is not included then require it into the project.
2. Create a validation hook that checks if the `config_split` module is available. If you try to use the `config-split` import strategy without the module, then it fails and provides instructions for requiring the module into the project. In addition, add `drupal/config_split` as a suggested package.
3. Make `core-only` the default update strategy (I don't necessarily prefer this, just pointing it out as an option and devil's advocate).
4. Update `ConfigCommand::importConfigSplit` to first check if the module is available; if it is available then conditionally enable the module, and if it is not then output a warning and defer to `ConfigCommand::importCoreOnly` (this way you're effectively implementing 3 above without changing the BLT default setup strategy).
5. If you must require `drupal/config_split` with the project, require it as `drupal/config_split:*` so projects are not locked into particular versions because they also happen to use BLT.

If this were a vote, and I were to rank those in order of preference, I would vote for 4, 2, 5, and no preference on the others. Again, my reasoning for providing alternatives is to just take the burden off of BLT in maintaining version constraints for packages that are technically optional within the project. Like if I want to use the `core-only` strategy, I shouldn't be required to include `drupal/config_split` in my project.
