### ISSUE TITLE
toggle:modules is reading environment incorrectly

### ISSUE THREAD

**Issue by shelane** [acquia/blt#4313]
**Describe the bug**
When running `blt artifact:update:drupal` in the context of a multisite, it will eventually invoke `drupal:toggle:modules`. When it does, it is now reading the environment "from config." Because of this, it reads that it is "local." How does one set the "config" per environment to work as it did in BLT 11? How will it not read the environment that was passed as part of the parent command with the --environment flag?

**To Reproduce**
This error is occurring on the test environment on Acquia Cloud Enterprise.
In an update or deploy hook, call `blt artifact:update:drupal --environment=$target_env`
To cause an "error" have a module in the modules.local.enable set that cannot be enabled (doesn't exist in code)
It would read local and output something like:
```
> drupal:toggle:modules
Executing drush pm-enable for modules defined in modules.local.enable...
[Acquia\Blt\Robo\Tasks\DrushTask] Running /var/www/html/****.test/vendor/bin/drush @self pm-enable asset_injector views_ui stage_file_proxy view_modes_display --uri=www --no-interaction --ansi in /var/www/html/****.test/docroot

[33mIn PmCommands.php line 253:[39m
[37;41m                                                                               [39;49m
[37;41m  Unable to install modules asset_injector, views_ui, stage_file_proxy, view_  [39;49m
[37;41m  modes_display due to missing modules view_modes_display.                     [39;49m
[37;41m                                                                               [39;49m
```

**Expected behavior**
I expect the correct environment to be read to enable/disable modules.

**System information**
* ACE
* BLT version: 12.5.1

**Additional context**
I see a change to this command was made here: https://github.com/acquia/blt/pull/4295
To test, I created a patch to restore the previous setting, but it still failed. I have no idea what "upstream" change could be the factor.

**Comment by danepowell** [comment]
Can you provide steps to reproduce this from a fresh install of BLT and a project template? I cannot reproduce it. The only way this should happen is if you've configured something (via blt.yml or a similar config file) or set an environment variable to detect the environment as local.

To debug, you could invoke the environment detector yourself in the toggle-modules command to see what it thinks the environment is, apart from BLT.

**Comment by shelane** [comment]
> To debug, you could invoke the environment detector yourself in the toggle-modules command to see what it thinks the environment is, apart from BLT.

please tell me how to invoke this. When outputting the value from the —environment flag in the parent command, it showed “test” as the value, which was the correct environment.

No environment variable is set to say local. I went from it working in my last 8.9.11 build with BLT 11.6.0 to this issue after updating all the required packages for Drupal 9 which involved the documented process to update. 

I will work on trying to do a fresh project for comparison.

**Comment by shelane** [comment]
So, I did a patch that looks like this:
```
     if ($this->getConfig()->has('environment')) {
       $environment = $this->getConfigValue('environment');
     }
+    if (EnvironmentDetector::isAhEnv()) {
+      $app = EnvironmentDetector::getAhGroup() ?? 'local';
+      $path_env = "/var/www/site-php/{$app}";
+      $env = EnvironmentDetector::getAhEnv();
+      $this->say("Deploy environment Ah detector: $env");
+    }
+    else {
+      $this->say("$environment didn't come from detector");
+    }
```

So that I can see what is going on. This is the output:
```
> drupal:toggle:modules
Deploy environment Ah detector: test
Executing drush pm-enable for modules defined in modules.local.enable...
[Acquia\Blt\Robo\Tasks\DrushTask] Running /var/www/html/llnl8.test/vendor/bin/drush @self pm-enable asset_injector views_ui stage_file_proxy view_modes_display --uri=www --no-interaction --ansi in /var/www/html/llnl8.test/docroot
```

So, despite the environment detector seeing the correct environment of "test" the "config" somehow still has "local".

**Comment by danepowell** [comment]
If the problem only occurs in a Cloud hook, can you replace the invocation with `blt artifact:update:drupal --environment=test -vvv` and post the output from the toggle-modules portion of the command?

Since I can't reproduce this locally, I'm wondering if the Cloud hook is actually not determining the environment correctly, and overriding BLT and the environment detector.

The 'environment' config is set here: https://github.com/acquia/blt/blob/0f6bb8728cdf07c8ea7d77e40b473cad01b2ba07/src/Robo/Config/ConfigInitializer.php#L180

The very first item in that conditional reads from the command line, so it seems like the only possible explanation is that the `--environment` parameter is being passed incorrectly.

**Comment by shelane** [comment]
Running that directly, it works fine.

```
> drupal:toggle:modules
[Robo\Common\ProcessExecutor] Running /var/www/html/****.test/vendor/bin/drush @self site:alias @self --format=json in /var/www/html/****.test/docroot
{
    "@self": {
        "root": "/mnt/www/html/****stg/docroot",
        "uri": "default"
    }
}
Environment by config: test
Executing drush pm-enable for modules defined in modules.test.enable...
[Acquia\Blt\Robo\Tasks\DrushTask] Running /var/www/html/****.test/vendor/bin/drush @self pm-enable asset_injector shield simplesamlphp_auth stage_file_proxy externalauth --no-interaction -vvv --ansi in /var/www/html/****.test/docroot
```

However, we have a custom command that we run so that we can go through the multi sites, test if Drupal is installed, update if it is or install if not. The `artifact:update:drupal` gets invoked in this command.

So, I call: `blt customcommand:site:deploy --environment=$target_env`

(which does show `test` as the environment)

And then I do `$this->invokeCommand('artifact:update:drupal');` within my command. Under BLT 11, this worked where the environment parameter was "passed along," but now this doesn't seem to be the case. How should it be passed along?

**Comment by danepowell** [comment]
Okay, that explains a lot. It would have helped to mention from the beginning that you are using a custom command instead of the stock cloud hooks, which explains why I couldn't reproduce it.

What's your full command file look like? Without seeing the full thing, it's hard to say for sure, but possibly the lost context is due to Robo command hooks. We previously fixed this for two other hooks:
- https://github.com/acquia/blt/pull/2176
- https://github.com/acquia/blt/pull/2052

It's also possible, though unlikely, that `switchSiteContext()` is interfering somehow. But we use both `invokeCommand()` and `switchSiteContext()` in other places that we've already established work fine. So I'm leaning toward the hook issue.

**Comment by shelane** [comment]
I can't post my full command publicly, so I sent it to you via Slack (Drupal). I will be looking at the ones you linked as well.

**Comment by danepowell** [comment]
I managed to reproduce this by modifying the example custom command and just adding `$this->invokeCommand('artifact:update:drupal');`:
https://github.com/acquia/blt/blob/12.6.0/scripts/blt/examples/Commands/ExampleCommands.php

Running `blt artifact:update:drupal --environment=test -vvv` produces `modules.test.enable is not set`, while `blt custom:hello --environment=test -vvv` produces `modules.local.enable is not set`. So it's obviously something to do with `invokeCommand()`. And in fact, adding a command to BLT's built-in command files also produces the bug. Which is weird, because we use `invokeCommand()` so many places, why hasn't this cropped up before?

@shelane as a temporary workaround, `invokeCommand()` takes a set of arguments, I'm not sure of the format off the top of my head but you can probably relay the environment parameter that way. It'll take some time to dig in on a root cause.

**Comment by shelane** [comment]
Sorry I didn’t mention the custom command sooner, but at least we ruled out that it wasn’t `artifact:update:drupal` directly.

I’m glad you were able to reproduce it. That does make me feel a bit better.

The format seems to be an array and I had already tried doing 
```
$args = [‘environment’ => $environment]
$this->invokeCommand('artifact:update:drupal', $args);
```
It said something about environment being an unknown argument or parameter. I can’t remember exactly what. So I thought it must be different to pass something in via that —parameter versus the second argument.

**Comment by camoa** [comment]
We are having this issue when deploying to the Stage/test environment. The module toggle is trying to use the local configuration.

We can see this message when deploying code with BLT 12.6.1 on staging:

> Executing drush pm-uninstall for modules defined in modules.local.uninstall...

**Comment by shelane** [comment]
Since this is also having an effect on `blt internal:drupal:install` I was looking at the command to see if I could apply the same workaround. However, I don't see a clear cut way to do it as I did with the module toggle. With the module toggle, I just set the php environment variable based on the system environment variable. In the install command, I don't see a php environment variable, so I'm not sure where to apply the override. Any pointers would help.

**Comment by shelane** [comment]
So I also tried a patch to change the determineEnvironment function that you listed above to this:
```
  public function determineEnvironment() {
    // Support --environment=ci.
    if ($this->input->hasParameterOption('--environment')) {
      $environment = $this->input->getParameterOption('--environment');
      $this->say("Has parameter --environment: $environment");
    }
    // Support --define environment=ci.
    elseif ($this->input->hasParameterOption('environment')) {
      $environment = ltrim($this->input->getParameterOption('environment'), '=');
      $this->say("Has parameter environment: $environment");
    }
    elseif (EnvironmentDetector::isAhEnv()) {
      $environment = EnvironmentDetector::getAhEnv();
      $this->say("Deploy environment Ah detector: $environment");
    }
    elseif (getenv('ONPREM_ENVIRONMENT')) {
      $environment = getenv('ONPREM_ENVIRONMENT');
      $this->say("Deploy environment On Prem env setting: $environment");
    }
    elseif (EnvironmentDetector::isCiEnv()) {
      $environment = 'ci';
    }
    else {
      $environment = 'local';
      $this->say("Deploy environment by default setting: $environment");
    }

    $this->environment = $environment;
    $this->config->set('environment', $environment);

    return $this;
  }
```
I'm probably using the wrong debugging output, because it didn't return anything.

**Comment by danepowell** [comment]
I think this is the best fix, which should work for all instances of invokeCommand() / invokeCommands(): https://github.com/acquia/blt/pull/4324
