### ISSUE TITLE
Make drupal:sync command configurability more general

### ISSUE THREAD

**Issue by greggmarshall** [acquia/blt#4317]
**Is your feature request related to a problem? Please describe.**
I really like that I can configure the commands to be executed during a drupal:sync command via our project blt.yml file.  I only wish it could do more.  The project I'm working on now is using Acquia Site Studio which adds the need for a couple of Drush commands beyond what we have via drupal:sync.  We've split the cohesion configuration files to let Site Studio handle the configuration via its package manager as recommended.  So after doing a drupal:sync we need to also do a drush sync:import, a drush cohesion:import, and a drush cohesion:rebuild.  It would be nice to have them included during a drupal:sync.

**Describe the solution you'd like**
If the commands in the sync section of the blt.yml were to include blt <command> and drush <command> then I could bundle everything into a single command.

**Describe alternatives you've considered**
My quick and dirty solution is a shell script that calls blt drupal:sync and the drush commands.  Longer term my tentative plan is to write a custom BLT command to implement the drush commands so I can include it in the drupal:sync.

**Comment by danepowell** [comment]
I don't think modifying drupal:sync to accept arbitrary commands is the best solution here, if only because it would break backwards compatibility. But more generally, it would duplicate the annotations system that we already have for running one command before, after, or instead of another.

There's a few ways you could solve this, ranging from a custom command that runs every other command you want, and set this command for `sync.commands`. Or write a custom command that replaces `drupal:sync:default:site`. Or if you want to run an arbitrary command before or after some set of other default BLT `sync.commands`, use a Robo command-event hook.

References:
- https://docs.acquia.com/blt/extending-blt/#adding-a-custom-robo-hook-or-command
- https://github.com/consolidation/annotated-command#hooks

**Comment by grasmash** [comment]
I would actually expect that we remove these commands given that they are now duplicative with the pull commands in Acquia CLI.

**Comment by shelane** [comment]
Not everyone who has BLT in their project has or wants Acquia CLI. The main purpose for the CLI tool is to interact with the Acquia cloud environment, is it not? Not everyone using BLT is even on Acquia cloud. BLT commands should remain platform agnostic.

**Comment by danepowell** [comment]
I don't think this is going to make it onto the roadmap as is, so I'm going to close it for now. If it gets a lot of upvotes or we can find a lighter-touch solution, I'd be willing to reconsider.
