### ISSUE TITLE
Issue with vanilla Drupal

### ISSUE THREAD

**Issue by sharique** [acquia/blt#4333]
When running blt setup in vanilla Drupal giving following error
```
ww-data@a5b40fb2aaa6:/app$ blt setup
[warning] The xDebug extension is loaded. This will significantly decrease performance.
Setting up local environment for site default.
Using drush alias @self
> source:build
PHP Fatal error:  Access level to Robo\Common\TaskIO::printTaskInfo() must be public (as in class Robo\Common\ExecTrait) in /app/vendor/consolidation/robo/src/Common/ProcessExecutor.php on line 63
Fatal error: Access level to Robo\Common\TaskIO::printTaskInfo() must be public (as in class Robo\Common\ExecTrait) in /app/vendor/consolidation/robo/src/Common/ProcessExecutor.php on line 63
```

blt.yml is as follows
```
project:
  machine_name: example
  profile:
    name: standard
  local:
    protocol: http
    hostname: ${project.machine_name}.lndo.site
docroot: ${repo.root}/web
```

I'm using lando for local environment, 

- Drupal version 9.1.2
- BLT version 12.6

**Comment by danepowell** [comment]
What version of Robo is installed? `composer show consolidation/robo`

> vendor/consolidation/robo/src/Common/ProcessExecutor.php on line 63

This error should not be possible, because ProcessExecutor isn't even 60 lines long in any major Robo branch: https://github.com/consolidation/Robo/blob/3.x/src/Common/ProcessExecutor.php

Can you compare the contents of ProcessExecutor.php to the upstream versions and figure out why it's reporting an error on line 63, when (AFAICT) line 63 does not exist?

**Comment by sharique** [comment]
It shows me version 1.4.13. I tried to update Robo package but it didn't help. 
After many trial and error, I finally able to get working using `composer update -W`.
