### ISSUE TITLE
DX-5142: Package minimum stability

### ISSUE THREAD

**Issue by sanfair** [acquia/blt#4568]
**Is your feature request related to a problem? Please describe.**
Installation acquia/blt package on version 13.5.1 with `"minimum-stability": "alpha"` failed with error:
```
  Problem 1
    - Root composer.json requires acquia/blt ^13.5.1 -> satisfiable by acquia/blt[13.5.1].
    - acquia/blt 13.5.1 requires grasmash/yaml-expander dev-master -> found grasmash/yaml-expander[dev-master, 3.x-dev (alias of dev-master)] but it does not match your minimum-stability.

```

**Describe the solution you'd like**
Change version constraint for `grasmash/yaml-expander` package from `dev-master` to `3.0.1` because they are the same at the moment, https://github.com/grasmash/yaml-expander/compare/master...3.0.1

**Comment by danepowell** [comment]
I can replicate this issue by installing acquia/drupal-recommended-project, changing the minimum stability to alpha, then attempting to add BLT.

The default branch for grasmash/yaml-expander appears to be `main` instead of `master`, but regardless you are right. I'll open a PR.

Thanks for the clear and concise report.
