### ISSUE TITLE
Issue on MAC with standard install process 

### ISSUE THREAD

**Issue by mghinea** [acquia/blt#526]
I followed [normal steps ](https://github.com/acquia/blt/blob/8.x/readme/creating-new-project.md)... and it is asking me the password ...  

blt > setup:drupal:install:
[echo] Printing drush status.
[drush] Changing working directory to: /Users/mghin/Desktop/blt_dev/MY_PROJECT_TEST/docroot
    [drush] Executing: /Users/mghin/Desktop/blt_dev/MY_PROJECT_TEST/vendor/bin/drush @blted8.local --uri=default --yes --verbose status
Loaded alias @blted8.local from file /Users/mghin/Desktop/blt_dev/MY_PROJECT_TEST/docroot/../drush/site-aliases/aliases.drushrc.php               [notice]
Begin redispatch via drush_invoke_process().                                                                                                            [notice]
Calling proc_open(ssh -o PasswordAuthentication=no -i /Users/mghin/.vagrant.d/insecure_private_key vagrant@blted8.localhost 'env COLUMNS=160 drush  --uri=default --yes --verbose --root=/var/www/blted8/docroot  core-status 2>&1' 2>&1);
Password:
Password:
Password:
Permission denied (publickey,keyboard-interactive).
End redispatch via drush_invoke_process().

**Comment by grasmash** [comment]
It seems that drush is unable to SSH into the Vagrant machine using the alias defined in `/Users/mghin/Desktop/blt_dev/MY_PROJECT_TEST/docroot/../drush/site-aliases/aliases.drushrc.php `.

So, I'd tackle the problem directly by getting `drush @blted8.local ssh` or `vagrant ssh` working. The issue is with Vagrant's ability to communicate with the VM. Have you previously used vagrant on your computer? You may have old configuration that's causing a problem.

**Comment by mghinea** [comment]
"vagrant ssh" works ... only the drush does not work

**Comment by grasmash** [comment]
> Have you previously used vagrant on your computer?

**Comment by mghinea** [comment]
yes

**Comment by grasmash** [comment]
In that case, I suspect configuration from your previously used vagrant machines is causing an issue.

Since `vagrant ssh` works, I'd take a look at the output of `vagrant ssh-config` to see what configuration is being used successfully. You may be able to copy to working insecure_private_key to `/Users/mghin/.vagrant.d/insecure_private_key`.

If that doesn't work, I'd also consider attempting to delete `/Users/mghin/.vagrant.d/insecure_private_key`, `vagrant destroy`, and `vagrant up` to (hopefully) regenerate a private key to be used.

See similar issues:
* https://github.com/puphpet/puphpet/issues/1253. That's where I'm getting a few ideas from.
* http://stackoverflow.com/questions/34598980/vagrant-ssh-promtps-for-password

**Comment by mghinea** [comment]
thank you for your help

seems I fixed it ... 

STEP 1
`vagrant box update `
 
STEP 2 .... do what the new error message says 
```
The ECDSA host key for blted8.localhost has changed,
and the key for the corresponding IP address 192.168.88.88
is unknown. This could either mean that
DNS SPOOFING is happening or the IP address for the host
and its host key have changed at the same time.
```

**Comment by grasmash** [comment]
Great!
