### ISSUE TITLE
Why does BLT assume the usage of a "vcs" config directory?

### ISSUE THREAD

**Issue by bkosborne** [acquia/blt#678]
BLT assumes the usage of a "vcs" config directory, I think because Acquia sets this in the ACE config file that's included on all ACE sites.

I don't really understand why we should have both the "vcs" config directory and the default "sync" directory that Drupal assumes. With the "vcs" approach, I have to specify that directory when running drush config-import and config-export, otherwise drush assumes the default of "sync".

Maybe at the very least this value can be changed to use a variable instead, so we can override it in our project.yml file? https://github.com/acquia/blt/blob/8.x/phing/tasks/deploy.xml#L167

**Comment by grasmash** [comment]
paging @danepowell. I think I had the same question.

**Comment by danepowell** [comment]
Hi @bkosborne , BLT generally assumes that you are storing config in Git, i.e. at `/config/default`. BLT defines that to be the `sync` directory in [local.settings.php](https://github.com/acquia/blt/blob/8.x/settings/default.local.settings.php#L30), while ACE calls that the `vcs` directory.

Honestly, I'm not sure why either ACE or BLT settled on the convention they did. I suspect BLT chose the `sync` key just for ease of use, because Drupal generally assumes you are working with the `sync` directory unless you specify something else. ACE probably chose `vcs` because Drupal by default puts the sync directory into the files directory (which conflicts with how we typically use it).

I could see arguments for any of the following:

1. Leave everything as it is :)
2. Use `vcs` across the board, even locally, which would be more consistent and less confusing, but would require anyone running drush config-import/export to manually pass `vcs` as an argument. We could write a wrapper command to make that easier.
3. Make the deploy/local default config directory key configurable, to support other conventions and other deployment environments besides ACE.

**Comment by bkosborne** [comment]
Thanks @danepowell 

Well I guess for now it makes sense to leave it as it is, I was mostly just confused

**Comment by grasmash** [comment]
@weitzman Could you shed some like on this? I'm frankly still not sure why Drush and Acquia Cloud use a `vcs` dir rather than a `sync` dir.

**Comment by geerlingguy** [comment]
I did a little more research, and it seems there's no particular reason why `vcs` was chosen... It just sort-of happened, and it's the default on Acquia Cloud. It seems to have been made the default around 8.0.0-rc2, and besides a few mentions in the documentation, there's no other public reasoning behind the ACE environments using `vcs` instead of the default `sync` directory used by Drupal core.

**Comment by weitzman** [comment]
There was a reason, but its not a great one. I suggest Cloud and BLT just consider the standard sync dir.
