### ISSUE TITLE
Multiple BLT projects in single machine needs more Hard disk space for VirtualBox

### ISSUE THREAD

**Issue by jayakrishnanj** [acquia/blt#706]
This is not any bug with any blt version.

When using multiple BLT projects in single machine with (256 GB hard disk and 8 GB RAM), System is slow due to its RAM allocation (2 GB each vagrant) and Vagrant box is consuming more than 10 GB per project.

is there any way we cannot use DRUPALVM inside BLT and use standalone Drupal VM with BLT setup in it.

**Comment by grasmash** [comment]
You're really free to customize your local machine in any way that you'd like. BLT won't care. I personally use MAMP for most projects since I have so many and resources are precious. But, you could easily spin up a single VM and clone many projects into it. The only tricky part will be the mount point. Assuming you want to mount project files from the host machine (which is faster), you'll need to either mount multiple directories or a higher level directory.

That's about the extent of my knowledge. I'd suggest asking a question in the [Drupal VM issue queue](https://github.com/geerlingguy/drupal-vm/issues) if you want more information on configuration.
