### ISSUE TITLE
Mailhog required for some commands

### ISSUE THREAD

**Issue by danepowell** [acquia/blt#809]
My system information:
* BLT version: 8.5.2
* LAMP stack is DrupalVM 3.5.2

When I run this command:
```
blt local:refresh
```

I get the following output:
```
sh: 1: /opt/mailhog/mhsendmail: not found
```

@geerlingguy says "we should either choose mailhog in installed_extras by default, or switch the PHP mail command back to what it was"

I confirmed that adding mailhog to installed_extras fixes it.

**Comment by geerlingguy** [comment]
See https://github.com/acquia/blt/pull/810 — this takes the former approach, and matches Drupal VM's default configuration. IMO this is better because having a mail catching utility running locally means no matter what, unless you explicitly override it, developers can't accidentally shoot out hundreds of emails to real email addresses :)
