### ISSUE TITLE
Add Pipelines documentation

### ISSUE THREAD

**Issue by grasmash** [acquia/blt#829]
This should outline:

* Intended Pipelines workflow
* Initialization instructions
* Links to external resources

**Comment by geerlingguy** [comment]
Following; I just integrated with BLT/GitHub, and have some notes.

**Comment by grasmash** [comment]
#828 merged.

**Comment by geerlingguy** [comment]
One note so far—it might be helpful to add a command to move the pipelines executable into a location that's in the default `$PATH`, like `mv pipelines /usr/local/bin` or something along those lines. Or just a note that you should place it in a place that's accessible in your $PATH.

Otherwise, people might end up committing the pipelines executable to their project repo :)
