### ISSUE TITLE
Investigate Adding Accessibility Tester to Automated Testing 

### ISSUE THREAD

**Issue by aweingarten** [acquia/blt#987]
Most projects have some accessibility requirements.  It would be a great if BLT added some accessibility testing out of the box.  

One idea that has been floated in the past has been to use http://pa11y.org/.

We could add a list of paths to test in project.yml and some acceptance threshold. Like we will allow 100 violations through.  As the site is more compliant that threshold could be dialed down.

**Comment by chrowe** [comment]
http://wave.webaim.org/api/ is another option

**Comment by grasmash** [comment]
This has been investigated. It's been determined that this will not be added directly to BLT. Rather, it would be housed in a separate project designed to be pulled into BLT via Composer.

The stopgap solution is to add pa11y to Cog.

Closing this issue because the work will be done in separate project.
